// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/identity.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.sismomesh.core.protocol.v1;

@kotlin.jvm.JvmName("-initializeemergencyDataPolicy")
public inline fun emergencyDataPolicy(block: co.sismomesh.core.protocol.v1.EmergencyDataPolicyKt.Dsl.() -> kotlin.Unit): co.sismomesh.core.protocol.v1.EmergencyDataPolicy =
  co.sismomesh.core.protocol.v1.EmergencyDataPolicyKt.Dsl._create(co.sismomesh.core.protocol.v1.EmergencyDataPolicy.newBuilder()).apply { block() }._build()
/**
 * ```
 * Definida por el usuario en modo "Preparación" (docs/architecture/OVERVIEW.md §1).
 * Determina qué campos del perfil son visibles para cada tipo de destinatario.
 * ```
 *
 * Protobuf type `sismomesh.v1.EmergencyDataPolicy`
 */
public object EmergencyDataPolicyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.sismomesh.core.protocol.v1.EmergencyDataPolicy.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.sismomesh.core.protocol.v1.EmergencyDataPolicy.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.sismomesh.core.protocol.v1.EmergencyDataPolicy = _builder.build()

    /**
     * `bool share_name_with_family = 1;`
     */
    public var shareNameWithFamily: kotlin.Boolean
      @kotlin.jvm.JvmName("getShareNameWithFamily")
        get() = _builder.shareNameWithFamily
      @kotlin.jvm.JvmName("setShareNameWithFamily")
        set(value) {
        _builder.shareNameWithFamily = value
      }
    /**
     * `bool share_name_with_family = 1;`
     */
    public fun clearShareNameWithFamily() {
      _builder.clearShareNameWithFamily()
    }

    /**
     * `bool share_name_with_authority = 2;`
     */
    public var shareNameWithAuthority: kotlin.Boolean
      @kotlin.jvm.JvmName("getShareNameWithAuthority")
        get() = _builder.shareNameWithAuthority
      @kotlin.jvm.JvmName("setShareNameWithAuthority")
        set(value) {
        _builder.shareNameWithAuthority = value
      }
    /**
     * `bool share_name_with_authority = 2;`
     */
    public fun clearShareNameWithAuthority() {
      _builder.clearShareNameWithAuthority()
    }

    /**
     * `bool share_medical_notes_with_family = 3;`
     */
    public var shareMedicalNotesWithFamily: kotlin.Boolean
      @kotlin.jvm.JvmName("getShareMedicalNotesWithFamily")
        get() = _builder.shareMedicalNotesWithFamily
      @kotlin.jvm.JvmName("setShareMedicalNotesWithFamily")
        set(value) {
        _builder.shareMedicalNotesWithFamily = value
      }
    /**
     * `bool share_medical_notes_with_family = 3;`
     */
    public fun clearShareMedicalNotesWithFamily() {
      _builder.clearShareMedicalNotesWithFamily()
    }

    /**
     * `bool share_medical_notes_with_authority = 4;`
     */
    public var shareMedicalNotesWithAuthority: kotlin.Boolean
      @kotlin.jvm.JvmName("getShareMedicalNotesWithAuthority")
        get() = _builder.shareMedicalNotesWithAuthority
      @kotlin.jvm.JvmName("setShareMedicalNotesWithAuthority")
        set(value) {
        _builder.shareMedicalNotesWithAuthority = value
      }
    /**
     * `bool share_medical_notes_with_authority = 4;`
     */
    public fun clearShareMedicalNotesWithAuthority() {
      _builder.clearShareMedicalNotesWithAuthority()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FamilyRecipientPublicKeysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     */
     public val familyRecipientPublicKeys: com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.familyRecipientPublicKeysList
      )
    /**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     * @param value The familyRecipientPublicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addFamilyRecipientPublicKeys")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.add(value: com.google.protobuf.ByteString) {
      _builder.addFamilyRecipientPublicKeys(value)
    }/**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     * @param value The familyRecipientPublicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignFamilyRecipientPublicKeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.plusAssign(value: com.google.protobuf.ByteString) {
      add(value)
    }/**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     * @param values The familyRecipientPublicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllFamilyRecipientPublicKeys")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      _builder.addAllFamilyRecipientPublicKeys(values)
    }/**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     * @param values The familyRecipientPublicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllFamilyRecipientPublicKeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.ByteString>) {
      addAll(values)
    }/**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     * @param index The index to set the value at.
     * @param value The familyRecipientPublicKeys to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setFamilyRecipientPublicKeys")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.set(index: kotlin.Int, value: com.google.protobuf.ByteString) {
      _builder.setFamilyRecipientPublicKeys(index, value)
    }/**
     * ```
     * X25519, uno por familiar vinculado y consentido
     * ```
     *
     * `repeated bytes family_recipient_public_keys = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearFamilyRecipientPublicKeys")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.ByteString, FamilyRecipientPublicKeysProxy>.clear() {
      _builder.clearFamilyRecipientPublicKeys()
    }
    /**
     * ```
     * de la autoridad del incidente activo
     * ```
     *
     * `bytes authority_public_key = 6;`
     */
    public var authorityPublicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getAuthorityPublicKey")
        get() = _builder.authorityPublicKey
      @kotlin.jvm.JvmName("setAuthorityPublicKey")
        set(value) {
        _builder.authorityPublicKey = value
      }
    /**
     * ```
     * de la autoridad del incidente activo
     * ```
     *
     * `bytes authority_public_key = 6;`
     */
    public fun clearAuthorityPublicKey() {
      _builder.clearAuthorityPublicKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.sismomesh.core.protocol.v1.EmergencyDataPolicy.copy(block: `co.sismomesh.core.protocol.v1`.EmergencyDataPolicyKt.Dsl.() -> kotlin.Unit): co.sismomesh.core.protocol.v1.EmergencyDataPolicy =
  `co.sismomesh.core.protocol.v1`.EmergencyDataPolicyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

