// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/motion.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.sismomesh.core.protocol.v1;

@kotlin.jvm.JvmName("-initializemotionEvidence")
public inline fun motionEvidence(block: co.sismomesh.core.protocol.v1.MotionEvidenceKt.Dsl.() -> kotlin.Unit): co.sismomesh.core.protocol.v1.MotionEvidence =
  co.sismomesh.core.protocol.v1.MotionEvidenceKt.Dsl._create(co.sismomesh.core.protocol.v1.MotionEvidence.newBuilder()).apply { block() }._build()
/**
 * ```
 * Evidencia de actividad/movimiento — Sección 10. Dueño: Alex.
 * Prohibido: DEAD/ALIVE/INJURED. Estados permitidos en el enum de arriba (bundle.proto).
 * ```
 *
 * Protobuf type `sismomesh.v1.MotionEvidence`
 */
public object MotionEvidenceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.sismomesh.core.protocol.v1.MotionEvidence.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.sismomesh.core.protocol.v1.MotionEvidence.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.sismomesh.core.protocol.v1.MotionEvidence = _builder.build()

    /**
     * ```
     * [0,1]
     * ```
     *
     * `double purposeful_motion_confidence = 1;`
     */
    public var purposefulMotionConfidence: kotlin.Double
      @kotlin.jvm.JvmName("getPurposefulMotionConfidence")
        get() = _builder.purposefulMotionConfidence
      @kotlin.jvm.JvmName("setPurposefulMotionConfidence")
        set(value) {
        _builder.purposefulMotionConfidence = value
      }
    /**
     * ```
     * [0,1]
     * ```
     *
     * `double purposeful_motion_confidence = 1;`
     */
    public fun clearPurposefulMotionConfidence() {
      _builder.clearPurposefulMotionConfidence()
    }

    /**
     * ```
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * ```
     *
     * `string pattern = 2;`
     */
    public var pattern: kotlin.String
      @kotlin.jvm.JvmName("getPattern")
        get() = _builder.pattern
      @kotlin.jvm.JvmName("setPattern")
        set(value) {
        _builder.pattern = value
      }
    /**
     * ```
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * ```
     *
     * `string pattern = 2;`
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }

    /**
     * `uint64 last_motion_ts = 3;`
     */
    public var lastMotionTs: kotlin.Long
      @kotlin.jvm.JvmName("getLastMotionTs")
        get() = _builder.lastMotionTs
      @kotlin.jvm.JvmName("setLastMotionTs")
        set(value) {
        _builder.lastMotionTs = value
      }
    /**
     * `uint64 last_motion_ts = 3;`
     */
    public fun clearLastMotionTs() {
      _builder.clearLastMotionTs()
    }

    /**
     * ```
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * ```
     *
     * `string activity_state = 4;`
     */
    public var activityState: kotlin.String
      @kotlin.jvm.JvmName("getActivityState")
        get() = _builder.activityState
      @kotlin.jvm.JvmName("setActivityState")
        set(value) {
        _builder.activityState = value
      }
    /**
     * ```
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * ```
     *
     * `string activity_state = 4;`
     */
    public fun clearActivityState() {
      _builder.clearActivityState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.sismomesh.core.protocol.v1.MotionEvidence.copy(block: `co.sismomesh.core.protocol.v1`.MotionEvidenceKt.Dsl.() -> kotlin.Unit): co.sismomesh.core.protocol.v1.MotionEvidence =
  `co.sismomesh.core.protocol.v1`.MotionEvidenceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

