# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helius/v1/motion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'helius/v1/motion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16helius/v1/motion.proto\x12\thelius.v1\"w\n\x0eMotionEvidence\x12$\n\x1cpurposeful_motion_confidence\x18\x01 \x01(\x01\x12\x0f\n\x07pattern\x18\x02 \x01(\t\x12\x16\n\x0elast_motion_ts\x18\x03 \x01(\x04\x12\x16\n\x0e\x61\x63tivity_state\x18\x04 \x01(\tB\x1e\n\x1a\x63o.helius.core.protocol.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helius.v1.motion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032co.helius.core.protocol.v1P\001'
  _globals['_MOTIONEVIDENCE']._serialized_start=37
  _globals['_MOTIONEVIDENCE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
