// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/bundle.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializebundleHeader")
public inline fun bundleHeader(block: co.helius.core.protocol.v1.BundleHeaderKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.BundleHeader =
  co.helius.core.protocol.v1.BundleHeaderKt.Dsl._create(co.helius.core.protocol.v1.BundleHeader.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `helius.v1.BundleHeader`
 */
public object BundleHeaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.BundleHeader.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.BundleHeader.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.BundleHeader = _builder.build()

    /**
     * `uint32 version = 1;`
     */
    public var version: kotlin.Int
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `uint32 version = 1;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string disaster_id = 2;`
     */
    public var disasterId: kotlin.String
      @kotlin.jvm.JvmName("getDisasterId")
        get() = _builder.disasterId
      @kotlin.jvm.JvmName("setDisasterId")
        set(value) {
        _builder.disasterId = value
      }
    /**
     * `string disaster_id = 2;`
     */
    public fun clearDisasterId() {
      _builder.clearDisasterId()
    }

    /**
     * ```
     * 16B, derivado de hash del contenido
     * ```
     *
     * `bytes bundle_id = 3;`
     */
    public var bundleId: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getBundleId")
        get() = _builder.bundleId
      @kotlin.jvm.JvmName("setBundleId")
        set(value) {
        _builder.bundleId = value
      }
    /**
     * ```
     * 16B, derivado de hash del contenido
     * ```
     *
     * `bytes bundle_id = 3;`
     */
    public fun clearBundleId() {
      _builder.clearBundleId()
    }

    /**
     * ```
     * pseudónimo efímero
     * ```
     *
     * `bytes node_id = 4;`
     */
    public var nodeId: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getNodeId")
        get() = _builder.nodeId
      @kotlin.jvm.JvmName("setNodeId")
        set(value) {
        _builder.nodeId = value
      }
    /**
     * ```
     * pseudónimo efímero
     * ```
     *
     * `bytes node_id = 4;`
     */
    public fun clearNodeId() {
      _builder.clearNodeId()
    }

    /**
     * `uint64 sequence = 5;`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * `uint64 sequence = 5;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * ```
     * epoch ms del emisor (no confiable)
     * ```
     *
     * `uint64 created_at = 6;`
     */
    public var createdAt: kotlin.Long
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * ```
     * epoch ms del emisor (no confiable)
     * ```
     *
     * `uint64 created_at = 6;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `uint64 expires_at = 7;`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * `uint64 expires_at = 7;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }

    /**
     * `uint32 hop_count = 8;`
     */
    public var hopCount: kotlin.Int
      @kotlin.jvm.JvmName("getHopCount")
        get() = _builder.hopCount
      @kotlin.jvm.JvmName("setHopCount")
        set(value) {
        _builder.hopCount = value
      }
    /**
     * `uint32 hop_count = 8;`
     */
    public fun clearHopCount() {
      _builder.clearHopCount()
    }

    /**
     * `.helius.v1.Priority priority = 9;`
     */
    public var priority: co.helius.core.protocol.v1.Priority
      @kotlin.jvm.JvmName("getPriority")
        get() = _builder.priority
      @kotlin.jvm.JvmName("setPriority")
        set(value) {
        _builder.priority = value
      }
    public var priorityValue: kotlin.Int
      @kotlin.jvm.JvmName("getPriorityValue")
        get() = _builder.priorityValue
      @kotlin.jvm.JvmName("setPriorityValue")
        set(value) {
        _builder.priorityValue = value
      }
    /**
     * `.helius.v1.Priority priority = 9;`
     */
    public fun clearPriority() {
      _builder.clearPriority()
    }

    /**
     * ```
     * monotónico + skew observado
     * ```
     *
     * `.helius.v1.ClockEvidence clock = 10;`
     */
    public var clock: co.helius.core.protocol.v1.ClockEvidence
      @kotlin.jvm.JvmName("getClock")
        get() = _builder.clock
      @kotlin.jvm.JvmName("setClock")
        set(value) {
        _builder.clock = value
      }
    /**
     * ```
     * monotónico + skew observado
     * ```
     *
     * `.helius.v1.ClockEvidence clock = 10;`
     */
    public fun clearClock() {
      _builder.clearClock()
    }
    /**
     * ```
     * monotónico + skew observado
     * ```
     *
     * `.helius.v1.ClockEvidence clock = 10;`
     * @return Whether the clock field is set.
     */
    public fun hasClock(): kotlin.Boolean {
      return _builder.hasClock()
    }

    public val BundleHeaderKt.Dsl.clockOrNull: co.helius.core.protocol.v1.ClockEvidence?
      get() = _builder.clockOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.BundleHeader.copy(block: `co.helius.core.protocol.v1`.BundleHeaderKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.BundleHeader =
  `co.helius.core.protocol.v1`.BundleHeaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val co.helius.core.protocol.v1.BundleHeaderOrBuilder.clockOrNull: co.helius.core.protocol.v1.ClockEvidence?
  get() = if (hasClock()) getClock() else null

