// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/bundle.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializebundle")
public inline fun bundle(block: co.helius.core.protocol.v1.BundleKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.Bundle =
  co.helius.core.protocol.v1.BundleKt.Dsl._create(co.helius.core.protocol.v1.Bundle.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `helius.v1.Bundle`
 */
public object BundleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.Bundle.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.Bundle.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.Bundle = _builder.build()

    /**
     * `.helius.v1.BundleHeader header = 1;`
     */
    public var header: co.helius.core.protocol.v1.BundleHeader
      @kotlin.jvm.JvmName("getHeader")
        get() = _builder.header
      @kotlin.jvm.JvmName("setHeader")
        set(value) {
        _builder.header = value
      }
    /**
     * `.helius.v1.BundleHeader header = 1;`
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * `.helius.v1.BundleHeader header = 1;`
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    public val BundleKt.Dsl.headerOrNull: co.helius.core.protocol.v1.BundleHeader?
      get() = _builder.headerOrNull

    /**
     * `.helius.v1.EmergencyStatus status = 10;`
     */
    public var status: co.helius.core.protocol.v1.EmergencyStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `.helius.v1.EmergencyStatus status = 10;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * `.helius.v1.EmergencyStatus status = 10;`
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * `.helius.v1.MotionEvidence motion = 11;`
     */
    public var motion: co.helius.core.protocol.v1.MotionEvidence
      @kotlin.jvm.JvmName("getMotion")
        get() = _builder.motion
      @kotlin.jvm.JvmName("setMotion")
        set(value) {
        _builder.motion = value
      }
    /**
     * `.helius.v1.MotionEvidence motion = 11;`
     */
    public fun clearMotion() {
      _builder.clearMotion()
    }
    /**
     * `.helius.v1.MotionEvidence motion = 11;`
     * @return Whether the motion field is set.
     */
    public fun hasMotion(): kotlin.Boolean {
      return _builder.hasMotion()
    }

    /**
     * ```
     * NUNCA "vitals" — ver docs/glossary.md
     * ```
     *
     * `.helius.v1.BiomarkerEvidence biomarker = 12;`
     */
    public var biomarker: co.helius.core.protocol.v1.BiomarkerEvidence
      @kotlin.jvm.JvmName("getBiomarker")
        get() = _builder.biomarker
      @kotlin.jvm.JvmName("setBiomarker")
        set(value) {
        _builder.biomarker = value
      }
    /**
     * ```
     * NUNCA "vitals" — ver docs/glossary.md
     * ```
     *
     * `.helius.v1.BiomarkerEvidence biomarker = 12;`
     */
    public fun clearBiomarker() {
      _builder.clearBiomarker()
    }
    /**
     * ```
     * NUNCA "vitals" — ver docs/glossary.md
     * ```
     *
     * `.helius.v1.BiomarkerEvidence biomarker = 12;`
     * @return Whether the biomarker field is set.
     */
    public fun hasBiomarker(): kotlin.Boolean {
      return _builder.hasBiomarker()
    }

    /**
     * `.helius.v1.PeerObservation observation = 13;`
     */
    public var observation: co.helius.core.protocol.v1.PeerObservation
      @kotlin.jvm.JvmName("getObservation")
        get() = _builder.observation
      @kotlin.jvm.JvmName("setObservation")
        set(value) {
        _builder.observation = value
      }
    /**
     * `.helius.v1.PeerObservation observation = 13;`
     */
    public fun clearObservation() {
      _builder.clearObservation()
    }
    /**
     * `.helius.v1.PeerObservation observation = 13;`
     * @return Whether the observation field is set.
     */
    public fun hasObservation(): kotlin.Boolean {
      return _builder.hasObservation()
    }

    /**
     * `.helius.v1.RawSensorChunk raw = 14;`
     */
    public var raw: co.helius.core.protocol.v1.RawSensorChunk
      @kotlin.jvm.JvmName("getRaw")
        get() = _builder.raw
      @kotlin.jvm.JvmName("setRaw")
        set(value) {
        _builder.raw = value
      }
    /**
     * `.helius.v1.RawSensorChunk raw = 14;`
     */
    public fun clearRaw() {
      _builder.clearRaw()
    }
    /**
     * `.helius.v1.RawSensorChunk raw = 14;`
     * @return Whether the raw field is set.
     */
    public fun hasRaw(): kotlin.Boolean {
      return _builder.hasRaw()
    }

    /**
     * ```
     * DTN inversa, ver Sección 8.6
     * ```
     *
     * `.helius.v1.ResponderMessage responder = 15;`
     */
    public var responder: co.helius.core.protocol.v1.ResponderMessage
      @kotlin.jvm.JvmName("getResponder")
        get() = _builder.responder
      @kotlin.jvm.JvmName("setResponder")
        set(value) {
        _builder.responder = value
      }
    /**
     * ```
     * DTN inversa, ver Sección 8.6
     * ```
     *
     * `.helius.v1.ResponderMessage responder = 15;`
     */
    public fun clearResponder() {
      _builder.clearResponder()
    }
    /**
     * ```
     * DTN inversa, ver Sección 8.6
     * ```
     *
     * `.helius.v1.ResponderMessage responder = 15;`
     * @return Whether the responder field is set.
     */
    public fun hasResponder(): kotlin.Boolean {
      return _builder.hasResponder()
    }

    /**
     * ```
     * Ed25519 sobre header||payload
     * ```
     *
     * `bytes signature = 20;`
     */
    public var signature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * ```
     * Ed25519 sobre header||payload
     * ```
     *
     * `bytes signature = 20;`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
    public val payloadCase: co.helius.core.protocol.v1.Bundle.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.Bundle.copy(block: `co.helius.core.protocol.v1`.BundleKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.Bundle =
  `co.helius.core.protocol.v1`.BundleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val co.helius.core.protocol.v1.BundleOrBuilder.headerOrNull: co.helius.core.protocol.v1.BundleHeader?
  get() = if (hasHeader()) getHeader() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.statusOrNull: co.helius.core.protocol.v1.EmergencyStatus?
  get() = if (hasStatus()) getStatus() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.motionOrNull: co.helius.core.protocol.v1.MotionEvidence?
  get() = if (hasMotion()) getMotion() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.biomarkerOrNull: co.helius.core.protocol.v1.BiomarkerEvidence?
  get() = if (hasBiomarker()) getBiomarker() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.observationOrNull: co.helius.core.protocol.v1.PeerObservation?
  get() = if (hasObservation()) getObservation() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.rawOrNull: co.helius.core.protocol.v1.RawSensorChunk?
  get() = if (hasRaw()) getRaw() else null

public val co.helius.core.protocol.v1.BundleOrBuilder.responderOrNull: co.helius.core.protocol.v1.ResponderMessage?
  get() = if (hasResponder()) getResponder() else null

