// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializecontactChannel")
public inline fun contactChannel(block: co.helius.core.protocol.v1.ContactChannelKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.ContactChannel =
  co.helius.core.protocol.v1.ContactChannelKt.Dsl._create(co.helius.core.protocol.v1.ContactChannel.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `helius.v1.ContactChannel`
 */
public object ContactChannelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.ContactChannel.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.ContactChannel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.ContactChannel = _builder.build()

    /**
     * `string kind = 1;`
     */
    public var kind: kotlin.String
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    /**
     * `string kind = 1;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `string value = 2;`
     */
    public var value: kotlin.String
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `string value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * `string belongs_to = 3;`
     */
    public var belongsTo: kotlin.String
      @kotlin.jvm.JvmName("getBelongsTo")
        get() = _builder.belongsTo
      @kotlin.jvm.JvmName("setBelongsTo")
        set(value) {
        _builder.belongsTo = value
      }
    /**
     * `string belongs_to = 3;`
     */
    public fun clearBelongsTo() {
      _builder.clearBelongsTo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.ContactChannel.copy(block: `co.helius.core.protocol.v1`.ContactChannelKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.ContactChannel =
  `co.helius.core.protocol.v1`.ContactChannelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

