// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializedeviceQuery")
public inline fun deviceQuery(block: co.helius.core.protocol.v1.DeviceQueryKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DeviceQuery =
  co.helius.core.protocol.v1.DeviceQueryKt.Dsl._create(co.helius.core.protocol.v1.DeviceQuery.newBuilder()).apply { block() }._build()
/**
 * ```
 * Consulta firmada de dispositivo a servicio.
 *
 * `lookup_token` es HMAC-SHA256(clave_del_incidente, documento_normalizado)
 * truncado a 16 bytes. Un dispositivo solo puede preguntar por alguien cuyo
 * documento ya conoce: no hay enumeración ni búsqueda por nombre.
 * ```
 *
 * Protobuf type `helius.v1.DeviceQuery`
 */
public object DeviceQueryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.DeviceQuery.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.DeviceQuery.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.DeviceQuery = _builder.build()

    /**
     * `string device_id = 1;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 1;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `string incident_id = 2;`
     */
    public var incidentId: kotlin.String
      @kotlin.jvm.JvmName("getIncidentId")
        get() = _builder.incidentId
      @kotlin.jvm.JvmName("setIncidentId")
        set(value) {
        _builder.incidentId = value
      }
    /**
     * `string incident_id = 2;`
     */
    public fun clearIncidentId() {
      _builder.clearIncidentId()
    }

    /**
     * `bytes lookup_token = 3;`
     */
    public var lookupToken: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getLookupToken")
        get() = _builder.lookupToken
      @kotlin.jvm.JvmName("setLookupToken")
        set(value) {
        _builder.lookupToken = value
      }
    /**
     * `bytes lookup_token = 3;`
     */
    public fun clearLookupToken() {
      _builder.clearLookupToken()
    }

    /**
     * `.helius.v1.DisclosurePurpose purpose = 4;`
     */
    public var purpose: co.helius.core.protocol.v1.DisclosurePurpose
      @kotlin.jvm.JvmName("getPurpose")
        get() = _builder.purpose
      @kotlin.jvm.JvmName("setPurpose")
        set(value) {
        _builder.purpose = value
      }
    public var purposeValue: kotlin.Int
      @kotlin.jvm.JvmName("getPurposeValue")
        get() = _builder.purposeValue
      @kotlin.jvm.JvmName("setPurposeValue")
        set(value) {
        _builder.purposeValue = value
      }
    /**
     * `.helius.v1.DisclosurePurpose purpose = 4;`
     */
    public fun clearPurpose() {
      _builder.clearPurpose()
    }

    /**
     * ```
     * va literal al audit_log; el Titular puede leerla
     * ```
     *
     * `string justification = 5;`
     */
    public var justification: kotlin.String
      @kotlin.jvm.JvmName("getJustification")
        get() = _builder.justification
      @kotlin.jvm.JvmName("setJustification")
        set(value) {
        _builder.justification = value
      }
    /**
     * ```
     * va literal al audit_log; el Titular puede leerla
     * ```
     *
     * `string justification = 5;`
     */
    public fun clearJustification() {
      _builder.clearJustification()
    }

    /**
     * ```
     * anti-replay
     * ```
     *
     * `bytes nonce = 6;`
     */
    public var nonce: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getNonce")
        get() = _builder.nonce
      @kotlin.jvm.JvmName("setNonce")
        set(value) {
        _builder.nonce = value
      }
    /**
     * ```
     * anti-replay
     * ```
     *
     * `bytes nonce = 6;`
     */
    public fun clearNonce() {
      _builder.clearNonce()
    }

    /**
     * `uint64 issued_at = 7;`
     */
    public var issuedAt: kotlin.Long
      @kotlin.jvm.JvmName("getIssuedAt")
        get() = _builder.issuedAt
      @kotlin.jvm.JvmName("setIssuedAt")
        set(value) {
        _builder.issuedAt = value
      }
    /**
     * `uint64 issued_at = 7;`
     */
    public fun clearIssuedAt() {
      _builder.clearIssuedAt()
    }

    /**
     * ```
     * vigencia máxima 15 min (credencial, no permiso)
     * ```
     *
     * `uint64 expires_at = 8;`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * ```
     * vigencia máxima 15 min (credencial, no permiso)
     * ```
     *
     * `uint64 expires_at = 8;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }

    /**
     * ```
     * Ed25519 sobre la forma canónica sin este campo
     * ```
     *
     * `bytes signature = 9;`
     */
    public var signature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * ```
     * Ed25519 sobre la forma canónica sin este campo
     * ```
     *
     * `bytes signature = 9;`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.DeviceQuery.copy(block: `co.helius.core.protocol.v1`.DeviceQueryKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DeviceQuery =
  `co.helius.core.protocol.v1`.DeviceQueryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

