// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializedisclosureView")
public inline fun disclosureView(block: co.helius.core.protocol.v1.DisclosureViewKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DisclosureView =
  co.helius.core.protocol.v1.DisclosureViewKt.Dsl._create(co.helius.core.protocol.v1.DisclosureView.newBuilder()).apply { block() }._build()
/**
 * ```
 * Contenido de la cápsula. Cada campo opcional está ausente porque su categoría no
 * fue concedida — la ausencia también es información honesta.
 * ```
 *
 * Protobuf type `helius.v1.DisclosureView`
 */
public object DisclosureViewKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.DisclosureView.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.DisclosureView.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.DisclosureView = _builder.build()

    /**
     * `string record_id = 1;`
     */
    public var recordId: kotlin.String
      @kotlin.jvm.JvmName("getRecordId")
        get() = _builder.recordId
      @kotlin.jvm.JvmName("setRecordId")
        set(value) {
        _builder.recordId = value
      }
    /**
     * `string record_id = 1;`
     */
    public fun clearRecordId() {
      _builder.clearRecordId()
    }

    /**
     * `string incident_id = 2;`
     */
    public var incidentId: kotlin.String
      @kotlin.jvm.JvmName("getIncidentId")
        get() = _builder.incidentId
      @kotlin.jvm.JvmName("setIncidentId")
        set(value) {
        _builder.incidentId = value
      }
    /**
     * `string incident_id = 2;`
     */
    public fun clearIncidentId() {
      _builder.clearIncidentId()
    }

    /**
     * `.helius.v1.SituationStatus status = 3;`
     */
    public var status: co.helius.core.protocol.v1.SituationStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.helius.v1.SituationStatus status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.helius.v1.VerificationLevel verification = 4;`
     */
    public var verification: co.helius.core.protocol.v1.VerificationLevel
      @kotlin.jvm.JvmName("getVerification")
        get() = _builder.verification
      @kotlin.jvm.JvmName("setVerification")
        set(value) {
        _builder.verification = value
      }
    public var verificationValue: kotlin.Int
      @kotlin.jvm.JvmName("getVerificationValue")
        get() = _builder.verificationValue
      @kotlin.jvm.JvmName("setVerificationValue")
        set(value) {
        _builder.verificationValue = value
      }
    /**
     * `.helius.v1.VerificationLevel verification = 4;`
     */
    public fun clearVerification() {
      _builder.clearVerification()
    }

    /**
     * `uint64 found_at = 5;`
     */
    public var foundAt: kotlin.Long
      @kotlin.jvm.JvmName("getFoundAt")
        get() = _builder.foundAt
      @kotlin.jvm.JvmName("setFoundAt")
        set(value) {
        _builder.foundAt = value
      }
    /**
     * `uint64 found_at = 5;`
     */
    public fun clearFoundAt() {
      _builder.clearFoundAt()
    }

    /**
     * `uint64 updated_at = 6;`
     */
    public var updatedAt: kotlin.Long
      @kotlin.jvm.JvmName("getUpdatedAt")
        get() = _builder.updatedAt
      @kotlin.jvm.JvmName("setUpdatedAt")
        set(value) {
        _builder.updatedAt = value
      }
    /**
     * `uint64 updated_at = 6;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }

    /**
     * `uint32 version = 7;`
     */
    public var version: kotlin.Int
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `uint32 version = 7;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `.helius.v1.DisclosureScope scope = 8;`
     */
    public var scope: co.helius.core.protocol.v1.DisclosureScope
      @kotlin.jvm.JvmName("getScope")
        get() = _builder.scope
      @kotlin.jvm.JvmName("setScope")
        set(value) {
        _builder.scope = value
      }
    public var scopeValue: kotlin.Int
      @kotlin.jvm.JvmName("getScopeValue")
        get() = _builder.scopeValue
      @kotlin.jvm.JvmName("setScopeValue")
        set(value) {
        _builder.scopeValue = value
      }
    /**
     * `.helius.v1.DisclosureScope scope = 8;`
     */
    public fun clearScope() {
      _builder.clearScope()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CategoriesDisclosedProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string categories_disclosed = 9;`
     * @return A list containing the categoriesDisclosed.
     */
    public val categoriesDisclosed: com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.categoriesDisclosedList
      )
    /**
     * `repeated string categories_disclosed = 9;`
     * @param value The categoriesDisclosed to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCategoriesDisclosed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.add(value: kotlin.String) {
      _builder.addCategoriesDisclosed(value)
    }
    /**
     * `repeated string categories_disclosed = 9;`
     * @param value The categoriesDisclosed to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCategoriesDisclosed")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string categories_disclosed = 9;`
     * @param values The categoriesDisclosed to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCategoriesDisclosed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllCategoriesDisclosed(values)
    }
    /**
     * `repeated string categories_disclosed = 9;`
     * @param values The categoriesDisclosed to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCategoriesDisclosed")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string categories_disclosed = 9;`
     * @param index The index to set the value at.
     * @param value The categoriesDisclosed to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCategoriesDisclosed")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setCategoriesDisclosed(index, value)
    }/**
     * `repeated string categories_disclosed = 9;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCategoriesDisclosed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, CategoriesDisclosedProxy>.clear() {
      _builder.clearCategoriesDisclosed()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WithheldCategoriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string withheld_categories = 10;`
     * @return A list containing the withheldCategories.
     */
    public val withheldCategories: com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.withheldCategoriesList
      )
    /**
     * `repeated string withheld_categories = 10;`
     * @param value The withheldCategories to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addWithheldCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.add(value: kotlin.String) {
      _builder.addWithheldCategories(value)
    }
    /**
     * `repeated string withheld_categories = 10;`
     * @param value The withheldCategories to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignWithheldCategories")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string withheld_categories = 10;`
     * @param values The withheldCategories to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllWithheldCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllWithheldCategories(values)
    }
    /**
     * `repeated string withheld_categories = 10;`
     * @param values The withheldCategories to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllWithheldCategories")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string withheld_categories = 10;`
     * @param index The index to set the value at.
     * @param value The withheldCategories to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setWithheldCategories")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setWithheldCategories(index, value)
    }/**
     * `repeated string withheld_categories = 10;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setWithheldCategories")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, WithheldCategoriesProxy>.clear() {
      _builder.clearWithheldCategories()
    }
    /**
     * `optional string display_name = 11;`
     */
    public var displayName: kotlin.String
      @kotlin.jvm.JvmName("getDisplayName")
        get() = _builder.displayName
      @kotlin.jvm.JvmName("setDisplayName")
        set(value) {
        _builder.displayName = value
      }
    /**
     * `optional string display_name = 11;`
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }
    /**
     * `optional string display_name = 11;`
     * @return Whether the displayName field is set.
     */
    public fun hasDisplayName(): kotlin.Boolean {
      return _builder.hasDisplayName()
    }

    /**
     * `optional string initials = 12;`
     */
    public var initials: kotlin.String
      @kotlin.jvm.JvmName("getInitials")
        get() = _builder.initials
      @kotlin.jvm.JvmName("setInitials")
        set(value) {
        _builder.initials = value
      }
    /**
     * `optional string initials = 12;`
     */
    public fun clearInitials() {
      _builder.clearInitials()
    }
    /**
     * `optional string initials = 12;`
     * @return Whether the initials field is set.
     */
    public fun hasInitials(): kotlin.Boolean {
      return _builder.hasInitials()
    }

    /**
     * `optional string document_type = 13;`
     */
    public var documentType: kotlin.String
      @kotlin.jvm.JvmName("getDocumentType")
        get() = _builder.documentType
      @kotlin.jvm.JvmName("setDocumentType")
        set(value) {
        _builder.documentType = value
      }
    /**
     * `optional string document_type = 13;`
     */
    public fun clearDocumentType() {
      _builder.clearDocumentType()
    }
    /**
     * `optional string document_type = 13;`
     * @return Whether the documentType field is set.
     */
    public fun hasDocumentType(): kotlin.Boolean {
      return _builder.hasDocumentType()
    }

    /**
     * `optional string document_number = 14;`
     */
    public var documentNumber: kotlin.String
      @kotlin.jvm.JvmName("getDocumentNumber")
        get() = _builder.documentNumber
      @kotlin.jvm.JvmName("setDocumentNumber")
        set(value) {
        _builder.documentNumber = value
      }
    /**
     * `optional string document_number = 14;`
     */
    public fun clearDocumentNumber() {
      _builder.clearDocumentNumber()
    }
    /**
     * `optional string document_number = 14;`
     * @return Whether the documentNumber field is set.
     */
    public fun hasDocumentNumber(): kotlin.Boolean {
      return _builder.hasDocumentNumber()
    }

    /**
     * `bool is_minor = 15;`
     */
    public var isMinor: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsMinor")
        get() = _builder.isMinor
      @kotlin.jvm.JvmName("setIsMinor")
        set(value) {
        _builder.isMinor = value
      }
    /**
     * `bool is_minor = 15;`
     */
    public fun clearIsMinor() {
      _builder.clearIsMinor()
    }

    /**
     * `optional string site_name = 16;`
     */
    public var siteName: kotlin.String
      @kotlin.jvm.JvmName("getSiteName")
        get() = _builder.siteName
      @kotlin.jvm.JvmName("setSiteName")
        set(value) {
        _builder.siteName = value
      }
    /**
     * `optional string site_name = 16;`
     */
    public fun clearSiteName() {
      _builder.clearSiteName()
    }
    /**
     * `optional string site_name = 16;`
     * @return Whether the siteName field is set.
     */
    public fun hasSiteName(): kotlin.Boolean {
      return _builder.hasSiteName()
    }

    /**
     * `optional string site_type = 17;`
     */
    public var siteType: kotlin.String
      @kotlin.jvm.JvmName("getSiteType")
        get() = _builder.siteType
      @kotlin.jvm.JvmName("setSiteType")
        set(value) {
        _builder.siteType = value
      }
    /**
     * `optional string site_type = 17;`
     */
    public fun clearSiteType() {
      _builder.clearSiteType()
    }
    /**
     * `optional string site_type = 17;`
     * @return Whether the siteType field is set.
     */
    public fun hasSiteType(): kotlin.Boolean {
      return _builder.hasSiteType()
    }

    /**
     * `optional string municipality = 18;`
     */
    public var municipality: kotlin.String
      @kotlin.jvm.JvmName("getMunicipality")
        get() = _builder.municipality
      @kotlin.jvm.JvmName("setMunicipality")
        set(value) {
        _builder.municipality = value
      }
    /**
     * `optional string municipality = 18;`
     */
    public fun clearMunicipality() {
      _builder.clearMunicipality()
    }
    /**
     * `optional string municipality = 18;`
     * @return Whether the municipality field is set.
     */
    public fun hasMunicipality(): kotlin.Boolean {
      return _builder.hasMunicipality()
    }

    /**
     * `optional string address = 19;`
     */
    public var address: kotlin.String
      @kotlin.jvm.JvmName("getAddress")
        get() = _builder.address
      @kotlin.jvm.JvmName("setAddress")
        set(value) {
        _builder.address = value
      }
    /**
     * `optional string address = 19;`
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }
    /**
     * `optional string address = 19;`
     * @return Whether the address field is set.
     */
    public fun hasAddress(): kotlin.Boolean {
      return _builder.hasAddress()
    }

    /**
     * `optional double lat = 20;`
     */
    public var lat: kotlin.Double
      @kotlin.jvm.JvmName("getLat")
        get() = _builder.lat
      @kotlin.jvm.JvmName("setLat")
        set(value) {
        _builder.lat = value
      }
    /**
     * `optional double lat = 20;`
     */
    public fun clearLat() {
      _builder.clearLat()
    }
    /**
     * `optional double lat = 20;`
     * @return Whether the lat field is set.
     */
    public fun hasLat(): kotlin.Boolean {
      return _builder.hasLat()
    }

    /**
     * `optional double lon = 24;`
     */
    public var lon: kotlin.Double
      @kotlin.jvm.JvmName("getLon")
        get() = _builder.lon
      @kotlin.jvm.JvmName("setLon")
        set(value) {
        _builder.lon = value
      }
    /**
     * `optional double lon = 24;`
     */
    public fun clearLon() {
      _builder.clearLon()
    }
    /**
     * `optional double lon = 24;`
     * @return Whether the lon field is set.
     */
    public fun hasLon(): kotlin.Boolean {
      return _builder.hasLon()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContactsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     */
     public val contacts: com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.contactsList
      )
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addContacts")
    public fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.add(value: co.helius.core.protocol.v1.ContactChannel) {
      _builder.addContacts(value)
    }
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.plusAssign(value: co.helius.core.protocol.v1.ContactChannel) {
      add(value)
    }
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllContacts")
    public fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.addAll(values: kotlin.collections.Iterable<co.helius.core.protocol.v1.ContactChannel>) {
      _builder.addAllContacts(values)
    }
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.plusAssign(values: kotlin.collections.Iterable<co.helius.core.protocol.v1.ContactChannel>) {
      addAll(values)
    }
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     * @param index The index to set the value at.
     * @param value The contacts to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setContacts")
    public operator fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.set(index: kotlin.Int, value: co.helius.core.protocol.v1.ContactChannel) {
      _builder.setContacts(index, value)
    }
    /**
     * `repeated .helius.v1.ContactChannel contacts = 21;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearContacts")
    public fun com.google.protobuf.kotlin.DslList<co.helius.core.protocol.v1.ContactChannel, ContactsProxy>.clear() {
      _builder.clearContacts()
    }

    /**
     * ```
     * dato sensible; NUNCA una valoración clínica
     * ```
     *
     * `optional string care_notes = 22;`
     */
    public var careNotes: kotlin.String
      @kotlin.jvm.JvmName("getCareNotes")
        get() = _builder.careNotes
      @kotlin.jvm.JvmName("setCareNotes")
        set(value) {
        _builder.careNotes = value
      }
    /**
     * ```
     * dato sensible; NUNCA una valoración clínica
     * ```
     *
     * `optional string care_notes = 22;`
     */
    public fun clearCareNotes() {
      _builder.clearCareNotes()
    }
    /**
     * ```
     * dato sensible; NUNCA una valoración clínica
     * ```
     *
     * `optional string care_notes = 22;`
     * @return Whether the careNotes field is set.
     */
    public fun hasCareNotes(): kotlin.Boolean {
      return _builder.hasCareNotes()
    }

    /**
     * ```
     * dato sensible
     * ```
     *
     * `optional string biometric_ref = 23;`
     */
    public var biometricRef: kotlin.String
      @kotlin.jvm.JvmName("getBiometricRef")
        get() = _builder.biometricRef
      @kotlin.jvm.JvmName("setBiometricRef")
        set(value) {
        _builder.biometricRef = value
      }
    /**
     * ```
     * dato sensible
     * ```
     *
     * `optional string biometric_ref = 23;`
     */
    public fun clearBiometricRef() {
      _builder.clearBiometricRef()
    }
    /**
     * ```
     * dato sensible
     * ```
     *
     * `optional string biometric_ref = 23;`
     * @return Whether the biometricRef field is set.
     */
    public fun hasBiometricRef(): kotlin.Boolean {
      return _builder.hasBiometricRef()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.DisclosureView.copy(block: `co.helius.core.protocol.v1`.DisclosureViewKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DisclosureView =
  `co.helius.core.protocol.v1`.DisclosureViewKt.Dsl._create(this.toBuilder()).apply { block() }._build()

