// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializedisclosureCapsule")
public inline fun disclosureCapsule(block: co.helius.core.protocol.v1.DisclosureCapsuleKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DisclosureCapsule =
  co.helius.core.protocol.v1.DisclosureCapsuleKt.Dsl._create(co.helius.core.protocol.v1.DisclosureCapsule.newBuilder()).apply { block() }._build()
/**
 * ```
 * Respuesta autocontenida, minimizada, sellada y con caducidad.
 *
 * Autocontenida porque quien la recibe puede estar a varios saltos del servicio.
 * Sellada porque los saltos intermedios no son de confianza. Caducada porque un
 * dato de emergencia que sobrevive a la emergencia deja de ser proporcionado.
 * ```
 *
 * Protobuf type `helius.v1.DisclosureCapsule`
 */
public object DisclosureCapsuleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.DisclosureCapsule.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.DisclosureCapsule.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.DisclosureCapsule = _builder.build()

    /**
     * `string capsule_id = 1;`
     */
    public var capsuleId: kotlin.String
      @kotlin.jvm.JvmName("getCapsuleId")
        get() = _builder.capsuleId
      @kotlin.jvm.JvmName("setCapsuleId")
        set(value) {
        _builder.capsuleId = value
      }
    /**
     * `string capsule_id = 1;`
     */
    public fun clearCapsuleId() {
      _builder.clearCapsuleId()
    }

    /**
     * `string incident_id = 2;`
     */
    public var incidentId: kotlin.String
      @kotlin.jvm.JvmName("getIncidentId")
        get() = _builder.incidentId
      @kotlin.jvm.JvmName("setIncidentId")
        set(value) {
        _builder.incidentId = value
      }
    /**
     * `string incident_id = 2;`
     */
    public fun clearIncidentId() {
      _builder.clearIncidentId()
    }

    /**
     * ```
     * único destinatario legítimo
     * ```
     *
     * `string audience_device_id = 3;`
     */
    public var audienceDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getAudienceDeviceId")
        get() = _builder.audienceDeviceId
      @kotlin.jvm.JvmName("setAudienceDeviceId")
        set(value) {
        _builder.audienceDeviceId = value
      }
    /**
     * ```
     * único destinatario legítimo
     * ```
     *
     * `string audience_device_id = 3;`
     */
    public fun clearAudienceDeviceId() {
      _builder.clearAudienceDeviceId()
    }

    /**
     * `.helius.v1.DisclosureScope scope = 4;`
     */
    public var scope: co.helius.core.protocol.v1.DisclosureScope
      @kotlin.jvm.JvmName("getScope")
        get() = _builder.scope
      @kotlin.jvm.JvmName("setScope")
        set(value) {
        _builder.scope = value
      }
    public var scopeValue: kotlin.Int
      @kotlin.jvm.JvmName("getScopeValue")
        get() = _builder.scopeValue
      @kotlin.jvm.JvmName("setScopeValue")
        set(value) {
        _builder.scopeValue = value
      }
    /**
     * `.helius.v1.DisclosureScope scope = 4;`
     */
    public fun clearScope() {
      _builder.clearScope()
    }

    /**
     * `.helius.v1.DisclosurePurpose purpose = 5;`
     */
    public var purpose: co.helius.core.protocol.v1.DisclosurePurpose
      @kotlin.jvm.JvmName("getPurpose")
        get() = _builder.purpose
      @kotlin.jvm.JvmName("setPurpose")
        set(value) {
        _builder.purpose = value
      }
    public var purposeValue: kotlin.Int
      @kotlin.jvm.JvmName("getPurposeValue")
        get() = _builder.purposeValue
      @kotlin.jvm.JvmName("setPurposeValue")
        set(value) {
        _builder.purposeValue = value
      }
    /**
     * `.helius.v1.DisclosurePurpose purpose = 5;`
     */
    public fun clearPurpose() {
      _builder.clearPurpose()
    }

    /**
     * `.helius.v1.CapsuleOutcome outcome = 6;`
     */
    public var outcome: co.helius.core.protocol.v1.CapsuleOutcome
      @kotlin.jvm.JvmName("getOutcome")
        get() = _builder.outcome
      @kotlin.jvm.JvmName("setOutcome")
        set(value) {
        _builder.outcome = value
      }
    public var outcomeValue: kotlin.Int
      @kotlin.jvm.JvmName("getOutcomeValue")
        get() = _builder.outcomeValue
      @kotlin.jvm.JvmName("setOutcomeValue")
        set(value) {
        _builder.outcomeValue = value
      }
    /**
     * `.helius.v1.CapsuleOutcome outcome = 6;`
     */
    public fun clearOutcome() {
      _builder.clearOutcome()
    }

    /**
     * `uint64 issued_at = 7;`
     */
    public var issuedAt: kotlin.Long
      @kotlin.jvm.JvmName("getIssuedAt")
        get() = _builder.issuedAt
      @kotlin.jvm.JvmName("setIssuedAt")
        set(value) {
        _builder.issuedAt = value
      }
    /**
     * `uint64 issued_at = 7;`
     */
    public fun clearIssuedAt() {
      _builder.clearIssuedAt()
    }

    /**
     * `uint64 expires_at = 8;`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * `uint64 expires_at = 8;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }

    /**
     * ```
     * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
     * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
     * ```
     *
     * `bytes payload = 9;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
     * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
     * ```
     *
     * `bytes payload = 9;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `bool payload_encrypted = 10;`
     */
    public var payloadEncrypted: kotlin.Boolean
      @kotlin.jvm.JvmName("getPayloadEncrypted")
        get() = _builder.payloadEncrypted
      @kotlin.jvm.JvmName("setPayloadEncrypted")
        set(value) {
        _builder.payloadEncrypted = value
      }
    /**
     * `bool payload_encrypted = 10;`
     */
    public fun clearPayloadEncrypted() {
      _builder.clearPayloadEncrypted()
    }

    /**
     * `optional string record_id = 11;`
     */
    public var recordId: kotlin.String
      @kotlin.jvm.JvmName("getRecordId")
        get() = _builder.recordId
      @kotlin.jvm.JvmName("setRecordId")
        set(value) {
        _builder.recordId = value
      }
    /**
     * `optional string record_id = 11;`
     */
    public fun clearRecordId() {
      _builder.clearRecordId()
    }
    /**
     * `optional string record_id = 11;`
     * @return Whether the recordId field is set.
     */
    public fun hasRecordId(): kotlin.Boolean {
      return _builder.hasRecordId()
    }

    /**
     * ```
     * descarta copias viejas de otra ruta
     * ```
     *
     * `optional uint32 record_version = 12;`
     */
    public var recordVersion: kotlin.Int
      @kotlin.jvm.JvmName("getRecordVersion")
        get() = _builder.recordVersion
      @kotlin.jvm.JvmName("setRecordVersion")
        set(value) {
        _builder.recordVersion = value
      }
    /**
     * ```
     * descarta copias viejas de otra ruta
     * ```
     *
     * `optional uint32 record_version = 12;`
     */
    public fun clearRecordVersion() {
      _builder.clearRecordVersion()
    }
    /**
     * ```
     * descarta copias viejas de otra ruta
     * ```
     *
     * `optional uint32 record_version = 12;`
     * @return Whether the recordVersion field is set.
     */
    public fun hasRecordVersion(): kotlin.Boolean {
      return _builder.hasRecordVersion()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReasonsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @return A list containing the reasons.
     */
    public val reasons: com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.reasonsList
      )
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @param value The reasons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addReasons")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.add(value: kotlin.String) {
      _builder.addReasons(value)
    }
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @param value The reasons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignReasons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @param values The reasons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllReasons")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllReasons(values)
    }
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @param values The reasons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllReasons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     * @param index The index to set the value at.
     * @param value The reasons to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReasons")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setReasons(index, value)
    }/**
     * ```
     * por qué se negó o qué se recortó
     * ```
     *
     * `repeated string reasons = 13;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReasons")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReasonsProxy>.clear() {
      _builder.clearReasons()
    }
    /**
     * `string audit_id = 14;`
     */
    public var auditId: kotlin.String
      @kotlin.jvm.JvmName("getAuditId")
        get() = _builder.auditId
      @kotlin.jvm.JvmName("setAuditId")
        set(value) {
        _builder.auditId = value
      }
    /**
     * `string audit_id = 14;`
     */
    public fun clearAuditId() {
      _builder.clearAuditId()
    }

    /**
     * `uint32 max_hops = 15;`
     */
    public var maxHops: kotlin.Int
      @kotlin.jvm.JvmName("getMaxHops")
        get() = _builder.maxHops
      @kotlin.jvm.JvmName("setMaxHops")
        set(value) {
        _builder.maxHops = value
      }
    /**
     * `uint32 max_hops = 15;`
     */
    public fun clearMaxHops() {
      _builder.clearMaxHops()
    }

    /**
     * `bool retransmit_allowed = 16;`
     */
    public var retransmitAllowed: kotlin.Boolean
      @kotlin.jvm.JvmName("getRetransmitAllowed")
        get() = _builder.retransmitAllowed
      @kotlin.jvm.JvmName("setRetransmitAllowed")
        set(value) {
        _builder.retransmitAllowed = value
      }
    /**
     * `bool retransmit_allowed = 16;`
     */
    public fun clearRetransmitAllowed() {
      _builder.clearRetransmitAllowed()
    }

    /**
     * ```
     * Ed25519 del servicio
     * ```
     *
     * `bytes signature = 17;`
     */
    public var signature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * ```
     * Ed25519 del servicio
     * ```
     *
     * `bytes signature = 17;`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.DisclosureCapsule.copy(block: `co.helius.core.protocol.v1`.DisclosureCapsuleKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.DisclosureCapsule =
  `co.helius.core.protocol.v1`.DisclosureCapsuleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

