// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/identity.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializeencryptedIdentityProfile")
public inline fun encryptedIdentityProfile(block: co.helius.core.protocol.v1.EncryptedIdentityProfileKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.EncryptedIdentityProfile =
  co.helius.core.protocol.v1.EncryptedIdentityProfileKt.Dsl._create(co.helius.core.protocol.v1.EncryptedIdentityProfile.newBuilder()).apply { block() }._build()
/**
 * ```
 * Un blob cifrado por destinatario (nunca un único blob "para cualquiera").
 * El relay transporta bytes opacos; no puede leer ni el nombre ni el contenido.
 * ```
 *
 * Protobuf type `helius.v1.EncryptedIdentityProfile`
 */
public object EncryptedIdentityProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.EncryptedIdentityProfile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.EncryptedIdentityProfile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.EncryptedIdentityProfile = _builder.build()

    /**
     * `.helius.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;`
     */
    public var recipientClass: co.helius.core.protocol.v1.EncryptedIdentityProfile.RecipientClass
      @kotlin.jvm.JvmName("getRecipientClass")
        get() = _builder.recipientClass
      @kotlin.jvm.JvmName("setRecipientClass")
        set(value) {
        _builder.recipientClass = value
      }
    public var recipientClassValue: kotlin.Int
      @kotlin.jvm.JvmName("getRecipientClassValue")
        get() = _builder.recipientClassValue
      @kotlin.jvm.JvmName("setRecipientClassValue")
        set(value) {
        _builder.recipientClassValue = value
      }
    /**
     * `.helius.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;`
     */
    public fun clearRecipientClass() {
      _builder.clearRecipientClass()
    }

    /**
     * ```
     * a qué clave X25519 va cifrado este blob
     * ```
     *
     * `bytes recipient_public_key = 2;`
     */
    public var recipientPublicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getRecipientPublicKey")
        get() = _builder.recipientPublicKey
      @kotlin.jvm.JvmName("setRecipientPublicKey")
        set(value) {
        _builder.recipientPublicKey = value
      }
    /**
     * ```
     * a qué clave X25519 va cifrado este blob
     * ```
     *
     * `bytes recipient_public_key = 2;`
     */
    public fun clearRecipientPublicKey() {
      _builder.clearRecipientPublicKey()
    }

    /**
     * ```
     * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
     * ```
     *
     * `bytes ciphertext = 3;`
     */
    public var ciphertext: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getCiphertext")
        get() = _builder.ciphertext
      @kotlin.jvm.JvmName("setCiphertext")
        set(value) {
        _builder.ciphertext = value
      }
    /**
     * ```
     * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
     * ```
     *
     * `bytes ciphertext = 3;`
     */
    public fun clearCiphertext() {
      _builder.clearCiphertext()
    }

    /**
     * `uint64 policy_version = 4;`
     */
    public var policyVersion: kotlin.Long
      @kotlin.jvm.JvmName("getPolicyVersion")
        get() = _builder.policyVersion
      @kotlin.jvm.JvmName("setPolicyVersion")
        set(value) {
        _builder.policyVersion = value
      }
    /**
     * `uint64 policy_version = 4;`
     */
    public fun clearPolicyVersion() {
      _builder.clearPolicyVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.EncryptedIdentityProfile.copy(block: `co.helius.core.protocol.v1`.EncryptedIdentityProfileKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.EncryptedIdentityProfile =
  `co.helius.core.protocol.v1`.EncryptedIdentityProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

