// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/common.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializegeoPoint")
public inline fun geoPoint(block: co.helius.core.protocol.v1.GeoPointKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.GeoPoint =
  co.helius.core.protocol.v1.GeoPointKt.Dsl._create(co.helius.core.protocol.v1.GeoPoint.newBuilder()).apply { block() }._build()
/**
 * ```
 * Ver ADR-0009 (localización 3D) para el origen de altitude_m/acc.
 * ```
 *
 * Protobuf type `helius.v1.GeoPoint`
 */
public object GeoPointKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.GeoPoint.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.GeoPoint.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.GeoPoint = _builder.build()

    /**
     * `double lat = 1;`
     */
    public var lat: kotlin.Double
      @kotlin.jvm.JvmName("getLat")
        get() = _builder.lat
      @kotlin.jvm.JvmName("setLat")
        set(value) {
        _builder.lat = value
      }
    /**
     * `double lat = 1;`
     */
    public fun clearLat() {
      _builder.clearLat()
    }

    /**
     * `double lon = 2;`
     */
    public var lon: kotlin.Double
      @kotlin.jvm.JvmName("getLon")
        get() = _builder.lon
      @kotlin.jvm.JvmName("setLon")
        set(value) {
        _builder.lon = value
      }
    /**
     * `double lon = 2;`
     */
    public fun clearLon() {
      _builder.clearLon()
    }

    /**
     * `optional double acc_m = 3;`
     */
    public var accM: kotlin.Double
      @kotlin.jvm.JvmName("getAccM")
        get() = _builder.accM
      @kotlin.jvm.JvmName("setAccM")
        set(value) {
        _builder.accM = value
      }
    /**
     * `optional double acc_m = 3;`
     */
    public fun clearAccM() {
      _builder.clearAccM()
    }
    /**
     * `optional double acc_m = 3;`
     * @return Whether the accM field is set.
     */
    public fun hasAccM(): kotlin.Boolean {
      return _builder.hasAccM()
    }

    /**
     * ```
     * relativa al nivel del suelo del edificio si se conoce, si no MSL/GNSS
     * ```
     *
     * `optional double altitude_m = 4;`
     */
    public var altitudeM: kotlin.Double
      @kotlin.jvm.JvmName("getAltitudeM")
        get() = _builder.altitudeM
      @kotlin.jvm.JvmName("setAltitudeM")
        set(value) {
        _builder.altitudeM = value
      }
    /**
     * ```
     * relativa al nivel del suelo del edificio si se conoce, si no MSL/GNSS
     * ```
     *
     * `optional double altitude_m = 4;`
     */
    public fun clearAltitudeM() {
      _builder.clearAltitudeM()
    }
    /**
     * ```
     * relativa al nivel del suelo del edificio si se conoce, si no MSL/GNSS
     * ```
     *
     * `optional double altitude_m = 4;`
     * @return Whether the altitudeM field is set.
     */
    public fun hasAltitudeM(): kotlin.Boolean {
      return _builder.hasAltitudeM()
    }

    /**
     * ```
     * ASSUMED hasta calibración — ver docs/validation/VALIDATION.md
     * ```
     *
     * `optional double altitude_acc_m = 5;`
     */
    public var altitudeAccM: kotlin.Double
      @kotlin.jvm.JvmName("getAltitudeAccM")
        get() = _builder.altitudeAccM
      @kotlin.jvm.JvmName("setAltitudeAccM")
        set(value) {
        _builder.altitudeAccM = value
      }
    /**
     * ```
     * ASSUMED hasta calibración — ver docs/validation/VALIDATION.md
     * ```
     *
     * `optional double altitude_acc_m = 5;`
     */
    public fun clearAltitudeAccM() {
      _builder.clearAltitudeAccM()
    }
    /**
     * ```
     * ASSUMED hasta calibración — ver docs/validation/VALIDATION.md
     * ```
     *
     * `optional double altitude_acc_m = 5;`
     * @return Whether the altitudeAccM field is set.
     */
    public fun hasAltitudeAccM(): kotlin.Boolean {
      return _builder.hasAltitudeAccM()
    }

    /**
     * `optional .helius.v1.AltitudeSource altitude_source = 6;`
     */
    public var altitudeSource: co.helius.core.protocol.v1.AltitudeSource
      @kotlin.jvm.JvmName("getAltitudeSource")
        get() = _builder.altitudeSource
      @kotlin.jvm.JvmName("setAltitudeSource")
        set(value) {
        _builder.altitudeSource = value
      }
    public var altitudeSourceValue: kotlin.Int
      @kotlin.jvm.JvmName("getAltitudeSourceValue")
        get() = _builder.altitudeSourceValue
      @kotlin.jvm.JvmName("setAltitudeSourceValue")
        set(value) {
        _builder.altitudeSourceValue = value
      }
    /**
     * `optional .helius.v1.AltitudeSource altitude_source = 6;`
     */
    public fun clearAltitudeSource() {
      _builder.clearAltitudeSource()
    }
    /**
     * `optional .helius.v1.AltitudeSource altitude_source = 6;`
     * @return Whether the altitudeSource field is set.
     */
    public fun hasAltitudeSource(): kotlin.Boolean {
      return _builder.hasAltitudeSource()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.GeoPoint.copy(block: `co.helius.core.protocol.v1`.GeoPointKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.GeoPoint =
  `co.helius.core.protocol.v1`.GeoPointKt.Dsl._create(this.toBuilder()).apply { block() }._build()

