// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/observation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializepeerObservation")
public inline fun peerObservation(block: co.helius.core.protocol.v1.PeerObservationKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.PeerObservation =
  co.helius.core.protocol.v1.PeerObservationKt.Dsl._create(co.helius.core.protocol.v1.PeerObservation.newBuilder()).apply { block() }._build()
/**
 * ```
 * PeerObservation: lo que un nodo registra al ver a otro (RSSI, transporte, timestamp) —
 * alimenta la localización probabilística 2D/3D (Sección 9, ADR-0009).
 * Dueño: Helmut (captura) / Miguel (backend, factor graph).
 * ```
 *
 * Protobuf type `helius.v1.PeerObservation`
 */
public object PeerObservationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.PeerObservation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.PeerObservation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.PeerObservation = _builder.build()

    /**
     * `bytes incident_id = 1;`
     */
    public var incidentId: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getIncidentId")
        get() = _builder.incidentId
      @kotlin.jvm.JvmName("setIncidentId")
        set(value) {
        _builder.incidentId = value
      }
    /**
     * `bytes incident_id = 1;`
     */
    public fun clearIncidentId() {
      _builder.clearIncidentId()
    }

    /**
     * `bytes node_a = 2;`
     */
    public var nodeA: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getNodeA")
        get() = _builder.nodeA
      @kotlin.jvm.JvmName("setNodeA")
        set(value) {
        _builder.nodeA = value
      }
    /**
     * `bytes node_a = 2;`
     */
    public fun clearNodeA() {
      _builder.clearNodeA()
    }

    /**
     * `bytes node_b = 3;`
     */
    public var nodeB: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getNodeB")
        get() = _builder.nodeB
      @kotlin.jvm.JvmName("setNodeB")
        set(value) {
        _builder.nodeB = value
      }
    /**
     * `bytes node_b = 3;`
     */
    public fun clearNodeB() {
      _builder.clearNodeB()
    }

    /**
     * `double rssi_dbm = 4;`
     */
    public var rssiDbm: kotlin.Double
      @kotlin.jvm.JvmName("getRssiDbm")
        get() = _builder.rssiDbm
      @kotlin.jvm.JvmName("setRssiDbm")
        set(value) {
        _builder.rssiDbm = value
      }
    /**
     * `double rssi_dbm = 4;`
     */
    public fun clearRssiDbm() {
      _builder.clearRssiDbm()
    }

    /**
     * `string transport = 5;`
     */
    public var transport: kotlin.String
      @kotlin.jvm.JvmName("getTransport")
        get() = _builder.transport
      @kotlin.jvm.JvmName("setTransport")
        set(value) {
        _builder.transport = value
      }
    /**
     * `string transport = 5;`
     */
    public fun clearTransport() {
      _builder.clearTransport()
    }

    /**
     * `optional .helius.v1.GeoPoint observer_geo = 6;`
     */
    public var observerGeo: co.helius.core.protocol.v1.GeoPoint
      @kotlin.jvm.JvmName("getObserverGeo")
        get() = _builder.observerGeo
      @kotlin.jvm.JvmName("setObserverGeo")
        set(value) {
        _builder.observerGeo = value
      }
    /**
     * `optional .helius.v1.GeoPoint observer_geo = 6;`
     */
    public fun clearObserverGeo() {
      _builder.clearObserverGeo()
    }
    /**
     * `optional .helius.v1.GeoPoint observer_geo = 6;`
     * @return Whether the observerGeo field is set.
     */
    public fun hasObserverGeo(): kotlin.Boolean {
      return _builder.hasObserverGeo()
    }

    public val PeerObservationKt.Dsl.observerGeoOrNull: co.helius.core.protocol.v1.GeoPoint?
      get() = _builder.observerGeoOrNull

    /**
     * `optional double observer_acc_m = 7;`
     */
    public var observerAccM: kotlin.Double
      @kotlin.jvm.JvmName("getObserverAccM")
        get() = _builder.observerAccM
      @kotlin.jvm.JvmName("setObserverAccM")
        set(value) {
        _builder.observerAccM = value
      }
    /**
     * `optional double observer_acc_m = 7;`
     */
    public fun clearObserverAccM() {
      _builder.clearObserverAccM()
    }
    /**
     * `optional double observer_acc_m = 7;`
     * @return Whether the observerAccM field is set.
     */
    public fun hasObserverAccM(): kotlin.Boolean {
      return _builder.hasObserverAccM()
    }

    /**
     * `uint64 observed_at = 8;`
     */
    public var observedAt: kotlin.Long
      @kotlin.jvm.JvmName("getObservedAt")
        get() = _builder.observedAt
      @kotlin.jvm.JvmName("setObservedAt")
        set(value) {
        _builder.observedAt = value
      }
    /**
     * `uint64 observed_at = 8;`
     */
    public fun clearObservedAt() {
      _builder.clearObservedAt()
    }

    /**
     * ```
     * Aporte vertical opcional para el factor graph 3D (ADR-0009). Solo se llena
     * cuando el transporte es UWB (azimuth/elevation reales) o cuando el
     * dispositivo tiene barómetro calibrado. NUNCA inferir profundidad solo de RSSI.
     * ```
     *
     * `optional double uwb_elevation_deg = 9;`
     */
    public var uwbElevationDeg: kotlin.Double
      @kotlin.jvm.JvmName("getUwbElevationDeg")
        get() = _builder.uwbElevationDeg
      @kotlin.jvm.JvmName("setUwbElevationDeg")
        set(value) {
        _builder.uwbElevationDeg = value
      }
    /**
     * ```
     * Aporte vertical opcional para el factor graph 3D (ADR-0009). Solo se llena
     * cuando el transporte es UWB (azimuth/elevation reales) o cuando el
     * dispositivo tiene barómetro calibrado. NUNCA inferir profundidad solo de RSSI.
     * ```
     *
     * `optional double uwb_elevation_deg = 9;`
     */
    public fun clearUwbElevationDeg() {
      _builder.clearUwbElevationDeg()
    }
    /**
     * ```
     * Aporte vertical opcional para el factor graph 3D (ADR-0009). Solo se llena
     * cuando el transporte es UWB (azimuth/elevation reales) o cuando el
     * dispositivo tiene barómetro calibrado. NUNCA inferir profundidad solo de RSSI.
     * ```
     *
     * `optional double uwb_elevation_deg = 9;`
     * @return Whether the uwbElevationDeg field is set.
     */
    public fun hasUwbElevationDeg(): kotlin.Boolean {
      return _builder.hasUwbElevationDeg()
    }

    /**
     * `optional double uwb_azimuth_deg = 10;`
     */
    public var uwbAzimuthDeg: kotlin.Double
      @kotlin.jvm.JvmName("getUwbAzimuthDeg")
        get() = _builder.uwbAzimuthDeg
      @kotlin.jvm.JvmName("setUwbAzimuthDeg")
        set(value) {
        _builder.uwbAzimuthDeg = value
      }
    /**
     * `optional double uwb_azimuth_deg = 10;`
     */
    public fun clearUwbAzimuthDeg() {
      _builder.clearUwbAzimuthDeg()
    }
    /**
     * `optional double uwb_azimuth_deg = 10;`
     * @return Whether the uwbAzimuthDeg field is set.
     */
    public fun hasUwbAzimuthDeg(): kotlin.Boolean {
      return _builder.hasUwbAzimuthDeg()
    }

    /**
     * `optional double uwb_distance_m = 11;`
     */
    public var uwbDistanceM: kotlin.Double
      @kotlin.jvm.JvmName("getUwbDistanceM")
        get() = _builder.uwbDistanceM
      @kotlin.jvm.JvmName("setUwbDistanceM")
        set(value) {
        _builder.uwbDistanceM = value
      }
    /**
     * `optional double uwb_distance_m = 11;`
     */
    public fun clearUwbDistanceM() {
      _builder.clearUwbDistanceM()
    }
    /**
     * `optional double uwb_distance_m = 11;`
     * @return Whether the uwbDistanceM field is set.
     */
    public fun hasUwbDistanceM(): kotlin.Boolean {
      return _builder.hasUwbDistanceM()
    }

    /**
     * `optional double barometric_pressure_hpa = 12;`
     */
    public var barometricPressureHpa: kotlin.Double
      @kotlin.jvm.JvmName("getBarometricPressureHpa")
        get() = _builder.barometricPressureHpa
      @kotlin.jvm.JvmName("setBarometricPressureHpa")
        set(value) {
        _builder.barometricPressureHpa = value
      }
    /**
     * `optional double barometric_pressure_hpa = 12;`
     */
    public fun clearBarometricPressureHpa() {
      _builder.clearBarometricPressureHpa()
    }
    /**
     * `optional double barometric_pressure_hpa = 12;`
     * @return Whether the barometricPressureHpa field is set.
     */
    public fun hasBarometricPressureHpa(): kotlin.Boolean {
      return _builder.hasBarometricPressureHpa()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.PeerObservation.copy(block: `co.helius.core.protocol.v1`.PeerObservationKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.PeerObservation =
  `co.helius.core.protocol.v1`.PeerObservationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val co.helius.core.protocol.v1.PeerObservationOrBuilder.observerGeoOrNull: co.helius.core.protocol.v1.GeoPoint?
  get() = if (hasObserverGeo()) getObserverGeo() else null

