// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package co.helius.core.protocol.v1;

@kotlin.jvm.JvmName("-initializetombstone")
public inline fun tombstone(block: co.helius.core.protocol.v1.TombstoneKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.Tombstone =
  co.helius.core.protocol.v1.TombstoneKt.Dsl._create(co.helius.core.protocol.v1.Tombstone.newBuilder()).apply { block() }._build()
/**
 * ```
 * Lápida de supresión. Se propaga por la malla para que los teléfonos borren sus
 * copias: sin este canal, el derecho de supresión no alcanzaría fuera del servidor.
 * No lleva PII — un dispositivo sin cápsula de ese registro no aprende nada.
 * ```
 *
 * Protobuf type `helius.v1.Tombstone`
 */
public object TombstoneKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: co.helius.core.protocol.v1.Tombstone.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: co.helius.core.protocol.v1.Tombstone.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): co.helius.core.protocol.v1.Tombstone = _builder.build()

    /**
     * `string record_id = 1;`
     */
    public var recordId: kotlin.String
      @kotlin.jvm.JvmName("getRecordId")
        get() = _builder.recordId
      @kotlin.jvm.JvmName("setRecordId")
        set(value) {
        _builder.recordId = value
      }
    /**
     * `string record_id = 1;`
     */
    public fun clearRecordId() {
      _builder.clearRecordId()
    }

    /**
     * `string incident_id = 2;`
     */
    public var incidentId: kotlin.String
      @kotlin.jvm.JvmName("getIncidentId")
        get() = _builder.incidentId
      @kotlin.jvm.JvmName("setIncidentId")
        set(value) {
        _builder.incidentId = value
      }
    /**
     * `string incident_id = 2;`
     */
    public fun clearIncidentId() {
      _builder.clearIncidentId()
    }

    /**
     * `uint64 issued_at = 3;`
     */
    public var issuedAt: kotlin.Long
      @kotlin.jvm.JvmName("getIssuedAt")
        get() = _builder.issuedAt
      @kotlin.jvm.JvmName("setIssuedAt")
        set(value) {
        _builder.issuedAt = value
      }
    /**
     * `uint64 issued_at = 3;`
     */
    public fun clearIssuedAt() {
      _builder.clearIssuedAt()
    }

    /**
     * `.helius.v1.TombstoneReason reason = 4;`
     */
    public var reason: co.helius.core.protocol.v1.TombstoneReason
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    public var reasonValue: kotlin.Int
      @kotlin.jvm.JvmName("getReasonValue")
        get() = _builder.reasonValue
      @kotlin.jvm.JvmName("setReasonValue")
        set(value) {
        _builder.reasonValue = value
      }
    /**
     * `.helius.v1.TombstoneReason reason = 4;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }

    /**
     * ```
     * monótono por incidente; permite sincronizar solo lo nuevo
     * ```
     *
     * `uint64 sequence = 5;`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * ```
     * monótono por incidente; permite sincronizar solo lo nuevo
     * ```
     *
     * `uint64 sequence = 5;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * ```
     * Ed25519 del servicio
     * ```
     *
     * `bytes signature = 6;`
     */
    public var signature: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * ```
     * Ed25519 del servicio
     * ```
     *
     * `bytes signature = 6;`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun co.helius.core.protocol.v1.Tombstone.copy(block: `co.helius.core.protocol.v1`.TombstoneKt.Dsl.() -> kotlin.Unit): co.helius.core.protocol.v1.Tombstone =
  `co.helius.core.protocol.v1`.TombstoneKt.Dsl._create(this.toBuilder()).apply { block() }._build()

