# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sismomesh/v1/identity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sismomesh/v1/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsismomesh/v1/identity.proto\x12\x0csismomesh.v1\"\xf1\x01\n\x13\x45mergencyDataPolicy\x12\x1e\n\x16share_name_with_family\x18\x01 \x01(\x08\x12!\n\x19share_name_with_authority\x18\x02 \x01(\x08\x12\'\n\x1fshare_medical_notes_with_family\x18\x03 \x01(\x08\x12*\n\"share_medical_notes_with_authority\x18\x04 \x01(\x08\x12$\n\x1c\x66\x61mily_recipient_public_keys\x18\x05 \x03(\x0c\x12\x1c\n\x14\x61uthority_public_key\x18\x06 \x01(\x0c\"\xff\x01\n\x18\x45ncryptedIdentityProfile\x12N\n\x0frecipient_class\x18\x01 \x01(\x0e\x32\x35.sismomesh.v1.EncryptedIdentityProfile.RecipientClass\x12\x1c\n\x14recipient_public_key\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\x12\x16\n\x0epolicy_version\x18\x04 \x01(\x04\"I\n\x0eRecipientClass\x12\x15\n\x11UNKNOWN_RECIPIENT\x10\x00\x12\n\n\x06\x46\x41MILY\x10\x01\x12\x14\n\x10RESCUE_AUTHORITY\x10\x02\"b\n\x18IdentityProfilePlaintext\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x15\n\rmedical_notes\x18\x02 \x01(\t\x12\x19\n\x11\x65mergency_contact\x18\x03 \x01(\tB!\n\x1d\x63o.sismomesh.core.protocol.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sismomesh.v1.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035co.sismomesh.core.protocol.v1P\001'
  _globals['_EMERGENCYDATAPOLICY']._serialized_start=46
  _globals['_EMERGENCYDATAPOLICY']._serialized_end=287
  _globals['_ENCRYPTEDIDENTITYPROFILE']._serialized_start=290
  _globals['_ENCRYPTEDIDENTITYPROFILE']._serialized_end=545
  _globals['_ENCRYPTEDIDENTITYPROFILE_RECIPIENTCLASS']._serialized_start=472
  _globals['_ENCRYPTEDIDENTITYPROFILE_RECIPIENTCLASS']._serialized_end=545
  _globals['_IDENTITYPROFILEPLAINTEXT']._serialized_start=547
  _globals['_IDENTITYPROFILEPLAINTEXT']._serialized_end=645
# @@protoc_insertion_point(module_scope)
