# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sismomesh/v1/inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sismomesh/v1/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csismomesh/v1/inventory.proto\x12\x0csismomesh.v1\"F\n\x0fInventoryFilter\x12\x11\n\tbit_count\x18\x01 \x01(\r\x12\x12\n\nhash_count\x18\x02 \x01(\r\x12\x0c\n\x04\x62its\x18\x03 \x01(\x0c\x42!\n\x1d\x63o.sismomesh.core.protocol.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sismomesh.v1.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035co.sismomesh.core.protocol.v1P\001'
  _globals['_INVENTORYFILTER']._serialized_start=46
  _globals['_INVENTORYFILTER']._serialized_end=116
# @@protoc_insertion_point(module_scope)
