// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * Protobuf enum {@code helius.v1.CapsuleOutcome}
 */
@com.google.protobuf.Generated
public enum CapsuleOutcome
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  OUTCOME_UNSPECIFIED(0),
  /**
   * <code>OUTCOME_GRANTED = 1;</code>
   */
  OUTCOME_GRANTED(1),
  /**
   * <code>OUTCOME_DENIED = 2;</code>
   */
  OUTCOME_DENIED(2),
  /**
   * <code>OUTCOME_NOT_FOUND = 3;</code>
   */
  OUTCOME_NOT_FOUND(3),
  /**
   * <code>OUTCOME_ERASED = 4;</code>
   */
  OUTCOME_ERASED(4),
  /**
   * <pre>
   * Respuesta única de los ámbitos PUBLIC y FAMILY. Deliberadamente incapaz de
   * distinguir "no existe" de "existe pero no te corresponde": si se distinguieran,
   * la consulta sería un oráculo para averiguar si alguien está registrado.
   * </pre>
   *
   * <code>OUTCOME_NO_DISCLOSURE = 5;</code>
   */
  OUTCOME_NO_DISCLOSURE(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CapsuleOutcome");
  }
  /**
   * <code>OUTCOME_UNSPECIFIED = 0;</code>
   */
  public static final int OUTCOME_UNSPECIFIED_VALUE = 0;
  /**
   * <code>OUTCOME_GRANTED = 1;</code>
   */
  public static final int OUTCOME_GRANTED_VALUE = 1;
  /**
   * <code>OUTCOME_DENIED = 2;</code>
   */
  public static final int OUTCOME_DENIED_VALUE = 2;
  /**
   * <code>OUTCOME_NOT_FOUND = 3;</code>
   */
  public static final int OUTCOME_NOT_FOUND_VALUE = 3;
  /**
   * <code>OUTCOME_ERASED = 4;</code>
   */
  public static final int OUTCOME_ERASED_VALUE = 4;
  /**
   * <pre>
   * Respuesta única de los ámbitos PUBLIC y FAMILY. Deliberadamente incapaz de
   * distinguir "no existe" de "existe pero no te corresponde": si se distinguieran,
   * la consulta sería un oráculo para averiguar si alguien está registrado.
   * </pre>
   *
   * <code>OUTCOME_NO_DISCLOSURE = 5;</code>
   */
  public static final int OUTCOME_NO_DISCLOSURE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CapsuleOutcome valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CapsuleOutcome forNumber(int value) {
    switch (value) {
      case 0: return OUTCOME_UNSPECIFIED;
      case 1: return OUTCOME_GRANTED;
      case 2: return OUTCOME_DENIED;
      case 3: return OUTCOME_NOT_FOUND;
      case 4: return OUTCOME_ERASED;
      case 5: return OUTCOME_NO_DISCLOSURE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CapsuleOutcome>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CapsuleOutcome> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CapsuleOutcome>() {
          public CapsuleOutcome findValueByNumber(int number) {
            return CapsuleOutcome.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.FoundPerson.getDescriptor().getEnumType(4);
  }

  private static final CapsuleOutcome[] VALUES = values();

  public static CapsuleOutcome valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CapsuleOutcome(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:helius.v1.CapsuleOutcome)
}

