// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

@com.google.protobuf.Generated
public interface ClockEvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helius.v1.ClockEvidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 monotonic_ms = 1;</code>
   * @return The monotonicMs.
   */
  long getMonotonicMs();

  /**
   * <code>optional int64 observed_skew_ms = 2;</code>
   * @return Whether the observedSkewMs field is set.
   */
  boolean hasObservedSkewMs();
  /**
   * <code>optional int64 observed_skew_ms = 2;</code>
   * @return The observedSkewMs.
   */
  long getObservedSkewMs();
}
