// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/common.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

@com.google.protobuf.Generated
public final class Common extends com.google.protobuf.GeneratedFile {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Common");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helius_v1_GeoPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_helius_v1_GeoPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026helius/v1/common.proto\022\thelius.v1\"\347\001\n\010" +
      "GeoPoint\022\013\n\003lat\030\001 \001(\001\022\013\n\003lon\030\002 \001(\001\022\022\n\005ac" +
      "c_m\030\003 \001(\001H\000\210\001\001\022\027\n\naltitude_m\030\004 \001(\001H\001\210\001\001\022" +
      "\033\n\016altitude_acc_m\030\005 \001(\001H\002\210\001\001\0227\n\017altitude" +
      "_source\030\006 \001(\0162\031.helius.v1.AltitudeSource" +
      "H\003\210\001\001B\010\n\006_acc_mB\r\n\013_altitude_mB\021\n\017_altit" +
      "ude_acc_mB\022\n\020_altitude_source*z\n\010Priorit" +
      "y\022\024\n\020P0_LIFE_CRITICAL\020\000\022\017\n\013P1_LOCATION\020\001" +
      "\022\r\n\tP2_STATUS\020\002\022\022\n\016P3_NETWORK_OBS\020\003\022\021\n\rP" +
      "4_RAW_SENSOR\020\004\022\021\n\rP5_DIAGNOSTIC\020\005*l\n\rRes" +
      "ponseState\022\013\n\007UNKNOWN\020\000\022\010\n\004SAFE\020\001\022\016\n\nNEE" +
      "DS_HELP\020\002\022\013\n\007TRAPPED\020\003\022\017\n\013UNCONFIRMED\020\004\022" +
      "\026\n\022NO_RECENT_EVIDENCE\020\005*^\n\016AltitudeSourc" +
      "e\022\024\n\020ALTITUDE_UNKNOWN\020\000\022\010\n\004GNSS\020\001\022\016\n\nBAR" +
      "OMETRIC\020\002\022\021\n\rUWB_ELEVATION\020\003\022\t\n\005FUSED\020\004B" +
      "\036\n\032co.helius.core.protocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helius_v1_GeoPoint_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_helius_v1_GeoPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_helius_v1_GeoPoint_descriptor,
        new java.lang.String[] { "Lat", "Lon", "AccM", "AltitudeM", "AltitudeAccM", "AltitudeSource", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
