// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Finalidad del Tratamiento (Ley 1581 art. 4 lit. b). Viaja firmada dentro de la
 * consulta: firmar solo el token permitiría reciclarla con otro propósito.
 * </pre>
 *
 * Protobuf enum {@code helius.v1.DisclosurePurpose}
 */
@com.google.protobuf.Generated
public enum DisclosurePurpose
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PURPOSE_UNSPECIFIED = 0;</code>
   */
  PURPOSE_UNSPECIFIED(0),
  /**
   * <code>PURPOSE_FAMILY_REUNIFICATION = 1;</code>
   */
  PURPOSE_FAMILY_REUNIFICATION(1),
  /**
   * <code>PURPOSE_RESPONSE_COORDINATION = 2;</code>
   */
  PURPOSE_RESPONSE_COORDINATION(2),
  /**
   * <code>PURPOSE_AUTHORITY_NOTIFICATION = 3;</code>
   */
  PURPOSE_AUTHORITY_NOTIFICATION(3),
  /**
   * <code>PURPOSE_ANONYMIZED_STATISTICS = 4;</code>
   */
  PURPOSE_ANONYMIZED_STATISTICS(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DisclosurePurpose");
  }
  /**
   * <code>PURPOSE_UNSPECIFIED = 0;</code>
   */
  public static final int PURPOSE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PURPOSE_FAMILY_REUNIFICATION = 1;</code>
   */
  public static final int PURPOSE_FAMILY_REUNIFICATION_VALUE = 1;
  /**
   * <code>PURPOSE_RESPONSE_COORDINATION = 2;</code>
   */
  public static final int PURPOSE_RESPONSE_COORDINATION_VALUE = 2;
  /**
   * <code>PURPOSE_AUTHORITY_NOTIFICATION = 3;</code>
   */
  public static final int PURPOSE_AUTHORITY_NOTIFICATION_VALUE = 3;
  /**
   * <code>PURPOSE_ANONYMIZED_STATISTICS = 4;</code>
   */
  public static final int PURPOSE_ANONYMIZED_STATISTICS_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DisclosurePurpose valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DisclosurePurpose forNumber(int value) {
    switch (value) {
      case 0: return PURPOSE_UNSPECIFIED;
      case 1: return PURPOSE_FAMILY_REUNIFICATION;
      case 2: return PURPOSE_RESPONSE_COORDINATION;
      case 3: return PURPOSE_AUTHORITY_NOTIFICATION;
      case 4: return PURPOSE_ANONYMIZED_STATISTICS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DisclosurePurpose>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DisclosurePurpose> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DisclosurePurpose>() {
          public DisclosurePurpose findValueByNumber(int number) {
            return DisclosurePurpose.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.FoundPerson.getDescriptor().getEnumType(3);
  }

  private static final DisclosurePurpose[] VALUES = values();

  public static DisclosurePurpose valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DisclosurePurpose(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:helius.v1.DisclosurePurpose)
}

