// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Nivel de exposición. Espeja las tres vistas del ADR-0007 más la autoridad.
 * </pre>
 *
 * Protobuf enum {@code helius.v1.DisclosureScope}
 */
@com.google.protobuf.Generated
public enum DisclosureScope
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SCOPE_UNSPECIFIED = 0;</code>
   */
  SCOPE_UNSPECIFIED(0),
  /**
   * <pre>
   * cero PII
   * </pre>
   *
   * <code>SCOPE_PUBLIC = 1;</code>
   */
  SCOPE_PUBLIC(1),
  /**
   * <code>SCOPE_FAMILY = 2;</code>
   */
  SCOPE_FAMILY(2),
  /**
   * <code>SCOPE_RESPONDER = 3;</code>
   */
  SCOPE_RESPONDER(3),
  /**
   * <code>SCOPE_AUTHORITY = 4;</code>
   */
  SCOPE_AUTHORITY(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DisclosureScope");
  }
  /**
   * <code>SCOPE_UNSPECIFIED = 0;</code>
   */
  public static final int SCOPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * cero PII
   * </pre>
   *
   * <code>SCOPE_PUBLIC = 1;</code>
   */
  public static final int SCOPE_PUBLIC_VALUE = 1;
  /**
   * <code>SCOPE_FAMILY = 2;</code>
   */
  public static final int SCOPE_FAMILY_VALUE = 2;
  /**
   * <code>SCOPE_RESPONDER = 3;</code>
   */
  public static final int SCOPE_RESPONDER_VALUE = 3;
  /**
   * <code>SCOPE_AUTHORITY = 4;</code>
   */
  public static final int SCOPE_AUTHORITY_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DisclosureScope valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DisclosureScope forNumber(int value) {
    switch (value) {
      case 0: return SCOPE_UNSPECIFIED;
      case 1: return SCOPE_PUBLIC;
      case 2: return SCOPE_FAMILY;
      case 3: return SCOPE_RESPONDER;
      case 4: return SCOPE_AUTHORITY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DisclosureScope>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DisclosureScope> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DisclosureScope>() {
          public DisclosureScope findValueByNumber(int number) {
            return DisclosureScope.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.FoundPerson.getDescriptor().getEnumType(2);
  }

  private static final DisclosureScope[] VALUES = values();

  public static DisclosureScope valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DisclosureScope(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:helius.v1.DisclosureScope)
}

