// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Respuesta autocontenida, minimizada, sellada y con caducidad.
 *
 * Autocontenida porque quien la recibe puede estar a varios saltos del servicio.
 * Sellada porque los saltos intermedios no son de confianza. Caducada porque un
 * dato de emergencia que sobrevive a la emergencia deja de ser proporcionado.
 * </pre>
 *
 * Protobuf type {@code helius.v1.DisclosureCapsule}
 */
@com.google.protobuf.Generated
public final class DisclosureCapsule extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helius.v1.DisclosureCapsule)
    DisclosureCapsuleOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "DisclosureCapsule");
  }
  // Use DisclosureCapsule.newBuilder() to construct.
  private DisclosureCapsule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DisclosureCapsule() {
    capsuleId_ = "";
    incidentId_ = "";
    audienceDeviceId_ = "";
    scope_ = 0;
    purpose_ = 0;
    outcome_ = 0;
    payload_ = com.google.protobuf.ByteString.EMPTY;
    recordId_ = "";
    reasons_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    auditId_ = "";
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.helius.core.protocol.v1.DisclosureCapsule.class, co.helius.core.protocol.v1.DisclosureCapsule.Builder.class);
  }

  private int bitField0_;
  public static final int CAPSULE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object capsuleId_ = "";
  /**
   * <code>string capsule_id = 1;</code>
   * @return The capsuleId.
   */
  @java.lang.Override
  public java.lang.String getCapsuleId() {
    java.lang.Object ref = capsuleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      capsuleId_ = s;
      return s;
    }
  }
  /**
   * <code>string capsule_id = 1;</code>
   * @return The bytes for capsuleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCapsuleIdBytes() {
    java.lang.Object ref = capsuleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      capsuleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCIDENT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object incidentId_ = "";
  /**
   * <code>string incident_id = 2;</code>
   * @return The incidentId.
   */
  @java.lang.Override
  public java.lang.String getIncidentId() {
    java.lang.Object ref = incidentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      incidentId_ = s;
      return s;
    }
  }
  /**
   * <code>string incident_id = 2;</code>
   * @return The bytes for incidentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIncidentIdBytes() {
    java.lang.Object ref = incidentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      incidentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUDIENCE_DEVICE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object audienceDeviceId_ = "";
  /**
   * <pre>
   * único destinatario legítimo
   * </pre>
   *
   * <code>string audience_device_id = 3;</code>
   * @return The audienceDeviceId.
   */
  @java.lang.Override
  public java.lang.String getAudienceDeviceId() {
    java.lang.Object ref = audienceDeviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      audienceDeviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * único destinatario legítimo
   * </pre>
   *
   * <code>string audience_device_id = 3;</code>
   * @return The bytes for audienceDeviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAudienceDeviceIdBytes() {
    java.lang.Object ref = audienceDeviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      audienceDeviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCOPE_FIELD_NUMBER = 4;
  private int scope_ = 0;
  /**
   * <code>.helius.v1.DisclosureScope scope = 4;</code>
   * @return The enum numeric value on the wire for scope.
   */
  @java.lang.Override public int getScopeValue() {
    return scope_;
  }
  /**
   * <code>.helius.v1.DisclosureScope scope = 4;</code>
   * @return The scope.
   */
  @java.lang.Override public co.helius.core.protocol.v1.DisclosureScope getScope() {
    co.helius.core.protocol.v1.DisclosureScope result = co.helius.core.protocol.v1.DisclosureScope.forNumber(scope_);
    return result == null ? co.helius.core.protocol.v1.DisclosureScope.UNRECOGNIZED : result;
  }

  public static final int PURPOSE_FIELD_NUMBER = 5;
  private int purpose_ = 0;
  /**
   * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
   * @return The enum numeric value on the wire for purpose.
   */
  @java.lang.Override public int getPurposeValue() {
    return purpose_;
  }
  /**
   * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
   * @return The purpose.
   */
  @java.lang.Override public co.helius.core.protocol.v1.DisclosurePurpose getPurpose() {
    co.helius.core.protocol.v1.DisclosurePurpose result = co.helius.core.protocol.v1.DisclosurePurpose.forNumber(purpose_);
    return result == null ? co.helius.core.protocol.v1.DisclosurePurpose.UNRECOGNIZED : result;
  }

  public static final int OUTCOME_FIELD_NUMBER = 6;
  private int outcome_ = 0;
  /**
   * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  @java.lang.Override public int getOutcomeValue() {
    return outcome_;
  }
  /**
   * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
   * @return The outcome.
   */
  @java.lang.Override public co.helius.core.protocol.v1.CapsuleOutcome getOutcome() {
    co.helius.core.protocol.v1.CapsuleOutcome result = co.helius.core.protocol.v1.CapsuleOutcome.forNumber(outcome_);
    return result == null ? co.helius.core.protocol.v1.CapsuleOutcome.UNRECOGNIZED : result;
  }

  public static final int ISSUED_AT_FIELD_NUMBER = 7;
  private long issuedAt_ = 0L;
  /**
   * <code>uint64 issued_at = 7;</code>
   * @return The issuedAt.
   */
  @java.lang.Override
  public long getIssuedAt() {
    return issuedAt_;
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 8;
  private long expiresAt_ = 0L;
  /**
   * <code>uint64 expires_at = 8;</code>
   * @return The expiresAt.
   */
  @java.lang.Override
  public long getExpiresAt() {
    return expiresAt_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
   * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
   * </pre>
   *
   * <code>bytes payload = 9;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int PAYLOAD_ENCRYPTED_FIELD_NUMBER = 10;
  private boolean payloadEncrypted_ = false;
  /**
   * <code>bool payload_encrypted = 10;</code>
   * @return The payloadEncrypted.
   */
  @java.lang.Override
  public boolean getPayloadEncrypted() {
    return payloadEncrypted_;
  }

  public static final int RECORD_ID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recordId_ = "";
  /**
   * <code>optional string record_id = 11;</code>
   * @return Whether the recordId field is set.
   */
  @java.lang.Override
  public boolean hasRecordId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string record_id = 11;</code>
   * @return The recordId.
   */
  @java.lang.Override
  public java.lang.String getRecordId() {
    java.lang.Object ref = recordId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string record_id = 11;</code>
   * @return The bytes for recordId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordIdBytes() {
    java.lang.Object ref = recordId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORD_VERSION_FIELD_NUMBER = 12;
  private int recordVersion_ = 0;
  /**
   * <pre>
   * descarta copias viejas de otra ruta
   * </pre>
   *
   * <code>optional uint32 record_version = 12;</code>
   * @return Whether the recordVersion field is set.
   */
  @java.lang.Override
  public boolean hasRecordVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * descarta copias viejas de otra ruta
   * </pre>
   *
   * <code>optional uint32 record_version = 12;</code>
   * @return The recordVersion.
   */
  @java.lang.Override
  public int getRecordVersion() {
    return recordVersion_;
  }

  public static final int REASONS_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList reasons_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * por qué se negó o qué se recortó
   * </pre>
   *
   * <code>repeated string reasons = 13;</code>
   * @return A list containing the reasons.
   */
  public com.google.protobuf.ProtocolStringList
      getReasonsList() {
    return reasons_;
  }
  /**
   * <pre>
   * por qué se negó o qué se recortó
   * </pre>
   *
   * <code>repeated string reasons = 13;</code>
   * @return The count of reasons.
   */
  public int getReasonsCount() {
    return reasons_.size();
  }
  /**
   * <pre>
   * por qué se negó o qué se recortó
   * </pre>
   *
   * <code>repeated string reasons = 13;</code>
   * @param index The index of the element to return.
   * @return The reasons at the given index.
   */
  public java.lang.String getReasons(int index) {
    return reasons_.get(index);
  }
  /**
   * <pre>
   * por qué se negó o qué se recortó
   * </pre>
   *
   * <code>repeated string reasons = 13;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasons at the given index.
   */
  public com.google.protobuf.ByteString
      getReasonsBytes(int index) {
    return reasons_.getByteString(index);
  }

  public static final int AUDIT_ID_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object auditId_ = "";
  /**
   * <code>string audit_id = 14;</code>
   * @return The auditId.
   */
  @java.lang.Override
  public java.lang.String getAuditId() {
    java.lang.Object ref = auditId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      auditId_ = s;
      return s;
    }
  }
  /**
   * <code>string audit_id = 14;</code>
   * @return The bytes for auditId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuditIdBytes() {
    java.lang.Object ref = auditId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      auditId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_HOPS_FIELD_NUMBER = 15;
  private int maxHops_ = 0;
  /**
   * <code>uint32 max_hops = 15;</code>
   * @return The maxHops.
   */
  @java.lang.Override
  public int getMaxHops() {
    return maxHops_;
  }

  public static final int RETRANSMIT_ALLOWED_FIELD_NUMBER = 16;
  private boolean retransmitAllowed_ = false;
  /**
   * <code>bool retransmit_allowed = 16;</code>
   * @return The retransmitAllowed.
   */
  @java.lang.Override
  public boolean getRetransmitAllowed() {
    return retransmitAllowed_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 17;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Ed25519 del servicio
   * </pre>
   *
   * <code>bytes signature = 17;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(capsuleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, capsuleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(incidentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, incidentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audienceDeviceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, audienceDeviceId_);
    }
    if (scope_ != co.helius.core.protocol.v1.DisclosureScope.SCOPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, scope_);
    }
    if (purpose_ != co.helius.core.protocol.v1.DisclosurePurpose.PURPOSE_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, purpose_);
    }
    if (outcome_ != co.helius.core.protocol.v1.CapsuleOutcome.OUTCOME_UNSPECIFIED.getNumber()) {
      output.writeEnum(6, outcome_);
    }
    if (issuedAt_ != 0L) {
      output.writeUInt64(7, issuedAt_);
    }
    if (expiresAt_ != 0L) {
      output.writeUInt64(8, expiresAt_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(9, payload_);
    }
    if (payloadEncrypted_ != false) {
      output.writeBool(10, payloadEncrypted_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, recordId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(12, recordVersion_);
    }
    for (int i = 0; i < reasons_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, reasons_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(auditId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 14, auditId_);
    }
    if (maxHops_ != 0) {
      output.writeUInt32(15, maxHops_);
    }
    if (retransmitAllowed_ != false) {
      output.writeBool(16, retransmitAllowed_);
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(17, signature_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(capsuleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, capsuleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(incidentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, incidentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audienceDeviceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, audienceDeviceId_);
    }
    if (scope_ != co.helius.core.protocol.v1.DisclosureScope.SCOPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, scope_);
    }
    if (purpose_ != co.helius.core.protocol.v1.DisclosurePurpose.PURPOSE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, purpose_);
    }
    if (outcome_ != co.helius.core.protocol.v1.CapsuleOutcome.OUTCOME_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, outcome_);
    }
    if (issuedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, issuedAt_);
    }
    if (expiresAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, expiresAt_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, payload_);
    }
    if (payloadEncrypted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, payloadEncrypted_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, recordId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(12, recordVersion_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reasons_.size(); i++) {
        dataSize += computeStringSizeNoTag(reasons_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReasonsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(auditId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(14, auditId_);
    }
    if (maxHops_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(15, maxHops_);
    }
    if (retransmitAllowed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, retransmitAllowed_);
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, signature_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.helius.core.protocol.v1.DisclosureCapsule)) {
      return super.equals(obj);
    }
    co.helius.core.protocol.v1.DisclosureCapsule other = (co.helius.core.protocol.v1.DisclosureCapsule) obj;

    if (!getCapsuleId()
        .equals(other.getCapsuleId())) return false;
    if (!getIncidentId()
        .equals(other.getIncidentId())) return false;
    if (!getAudienceDeviceId()
        .equals(other.getAudienceDeviceId())) return false;
    if (scope_ != other.scope_) return false;
    if (purpose_ != other.purpose_) return false;
    if (outcome_ != other.outcome_) return false;
    if (getIssuedAt()
        != other.getIssuedAt()) return false;
    if (getExpiresAt()
        != other.getExpiresAt()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getPayloadEncrypted()
        != other.getPayloadEncrypted()) return false;
    if (hasRecordId() != other.hasRecordId()) return false;
    if (hasRecordId()) {
      if (!getRecordId()
          .equals(other.getRecordId())) return false;
    }
    if (hasRecordVersion() != other.hasRecordVersion()) return false;
    if (hasRecordVersion()) {
      if (getRecordVersion()
          != other.getRecordVersion()) return false;
    }
    if (!getReasonsList()
        .equals(other.getReasonsList())) return false;
    if (!getAuditId()
        .equals(other.getAuditId())) return false;
    if (getMaxHops()
        != other.getMaxHops()) return false;
    if (getRetransmitAllowed()
        != other.getRetransmitAllowed()) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAPSULE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCapsuleId().hashCode();
    hash = (37 * hash) + INCIDENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIncidentId().hashCode();
    hash = (37 * hash) + AUDIENCE_DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAudienceDeviceId().hashCode();
    hash = (37 * hash) + SCOPE_FIELD_NUMBER;
    hash = (53 * hash) + scope_;
    hash = (37 * hash) + PURPOSE_FIELD_NUMBER;
    hash = (53 * hash) + purpose_;
    hash = (37 * hash) + OUTCOME_FIELD_NUMBER;
    hash = (53 * hash) + outcome_;
    hash = (37 * hash) + ISSUED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIssuedAt());
    hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiresAt());
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + PAYLOAD_ENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPayloadEncrypted());
    if (hasRecordId()) {
      hash = (37 * hash) + RECORD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRecordId().hashCode();
    }
    if (hasRecordVersion()) {
      hash = (37 * hash) + RECORD_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getRecordVersion();
    }
    if (getReasonsCount() > 0) {
      hash = (37 * hash) + REASONS_FIELD_NUMBER;
      hash = (53 * hash) + getReasonsList().hashCode();
    }
    hash = (37 * hash) + AUDIT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAuditId().hashCode();
    hash = (37 * hash) + MAX_HOPS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxHops();
    hash = (37 * hash) + RETRANSMIT_ALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetransmitAllowed());
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.helius.core.protocol.v1.DisclosureCapsule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.helius.core.protocol.v1.DisclosureCapsule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.DisclosureCapsule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.helius.core.protocol.v1.DisclosureCapsule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Respuesta autocontenida, minimizada, sellada y con caducidad.
   *
   * Autocontenida porque quien la recibe puede estar a varios saltos del servicio.
   * Sellada porque los saltos intermedios no son de confianza. Caducada porque un
   * dato de emergencia que sobrevive a la emergencia deja de ser proporcionado.
   * </pre>
   *
   * Protobuf type {@code helius.v1.DisclosureCapsule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helius.v1.DisclosureCapsule)
      co.helius.core.protocol.v1.DisclosureCapsuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.helius.core.protocol.v1.DisclosureCapsule.class, co.helius.core.protocol.v1.DisclosureCapsule.Builder.class);
    }

    // Construct using co.helius.core.protocol.v1.DisclosureCapsule.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      capsuleId_ = "";
      incidentId_ = "";
      audienceDeviceId_ = "";
      scope_ = 0;
      purpose_ = 0;
      outcome_ = 0;
      issuedAt_ = 0L;
      expiresAt_ = 0L;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      payloadEncrypted_ = false;
      recordId_ = "";
      recordVersion_ = 0;
      reasons_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      auditId_ = "";
      maxHops_ = 0;
      retransmitAllowed_ = false;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.helius.core.protocol.v1.FoundPerson.internal_static_helius_v1_DisclosureCapsule_descriptor;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.DisclosureCapsule getDefaultInstanceForType() {
      return co.helius.core.protocol.v1.DisclosureCapsule.getDefaultInstance();
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.DisclosureCapsule build() {
      co.helius.core.protocol.v1.DisclosureCapsule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.DisclosureCapsule buildPartial() {
      co.helius.core.protocol.v1.DisclosureCapsule result = new co.helius.core.protocol.v1.DisclosureCapsule(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.helius.core.protocol.v1.DisclosureCapsule result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.capsuleId_ = capsuleId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.incidentId_ = incidentId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.audienceDeviceId_ = audienceDeviceId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.scope_ = scope_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.purpose_ = purpose_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.outcome_ = outcome_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.issuedAt_ = issuedAt_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.expiresAt_ = expiresAt_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.payload_ = payload_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.payloadEncrypted_ = payloadEncrypted_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.recordId_ = recordId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.recordVersion_ = recordVersion_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        reasons_.makeImmutable();
        result.reasons_ = reasons_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.auditId_ = auditId_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.maxHops_ = maxHops_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.retransmitAllowed_ = retransmitAllowed_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.signature_ = signature_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.helius.core.protocol.v1.DisclosureCapsule) {
        return mergeFrom((co.helius.core.protocol.v1.DisclosureCapsule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.helius.core.protocol.v1.DisclosureCapsule other) {
      if (other == co.helius.core.protocol.v1.DisclosureCapsule.getDefaultInstance()) return this;
      if (!other.getCapsuleId().isEmpty()) {
        capsuleId_ = other.capsuleId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIncidentId().isEmpty()) {
        incidentId_ = other.incidentId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAudienceDeviceId().isEmpty()) {
        audienceDeviceId_ = other.audienceDeviceId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.scope_ != 0) {
        setScopeValue(other.getScopeValue());
      }
      if (other.purpose_ != 0) {
        setPurposeValue(other.getPurposeValue());
      }
      if (other.outcome_ != 0) {
        setOutcomeValue(other.getOutcomeValue());
      }
      if (other.getIssuedAt() != 0L) {
        setIssuedAt(other.getIssuedAt());
      }
      if (other.getExpiresAt() != 0L) {
        setExpiresAt(other.getExpiresAt());
      }
      if (!other.getPayload().isEmpty()) {
        setPayload(other.getPayload());
      }
      if (other.getPayloadEncrypted() != false) {
        setPayloadEncrypted(other.getPayloadEncrypted());
      }
      if (other.hasRecordId()) {
        recordId_ = other.recordId_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.hasRecordVersion()) {
        setRecordVersion(other.getRecordVersion());
      }
      if (!other.reasons_.isEmpty()) {
        if (reasons_.isEmpty()) {
          reasons_ = other.reasons_;
          bitField0_ |= 0x00001000;
        } else {
          ensureReasonsIsMutable();
          reasons_.addAll(other.reasons_);
        }
        onChanged();
      }
      if (!other.getAuditId().isEmpty()) {
        auditId_ = other.auditId_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (other.getMaxHops() != 0) {
        setMaxHops(other.getMaxHops());
      }
      if (other.getRetransmitAllowed() != false) {
        setRetransmitAllowed(other.getRetransmitAllowed());
      }
      if (!other.getSignature().isEmpty()) {
        setSignature(other.getSignature());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              capsuleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              incidentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              audienceDeviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              scope_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              purpose_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              outcome_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              issuedAt_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              expiresAt_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              payloadEncrypted_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              recordId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              recordVersion_ = input.readUInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 106: {
              ensureReasonsIsMutable();
              reasons_.add(input.readStringRequireUtf8());
              break;
            } // case 106
            case 114: {
              auditId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 120: {
              maxHops_ = input.readUInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              retransmitAllowed_ = input.readBool();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 138: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00010000;
              break;
            } // case 138
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object capsuleId_ = "";
    /**
     * <code>string capsule_id = 1;</code>
     * @return The capsuleId.
     */
    public java.lang.String getCapsuleId() {
      java.lang.Object ref = capsuleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        capsuleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string capsule_id = 1;</code>
     * @return The bytes for capsuleId.
     */
    public com.google.protobuf.ByteString
        getCapsuleIdBytes() {
      java.lang.Object ref = capsuleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capsuleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string capsule_id = 1;</code>
     * @param value The capsuleId to set.
     * @return This builder for chaining.
     */
    public Builder setCapsuleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      capsuleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string capsule_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapsuleId() {
      capsuleId_ = getDefaultInstance().getCapsuleId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string capsule_id = 1;</code>
     * @param value The bytes for capsuleId to set.
     * @return This builder for chaining.
     */
    public Builder setCapsuleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      capsuleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object incidentId_ = "";
    /**
     * <code>string incident_id = 2;</code>
     * @return The incidentId.
     */
    public java.lang.String getIncidentId() {
      java.lang.Object ref = incidentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        incidentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string incident_id = 2;</code>
     * @return The bytes for incidentId.
     */
    public com.google.protobuf.ByteString
        getIncidentIdBytes() {
      java.lang.Object ref = incidentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        incidentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string incident_id = 2;</code>
     * @param value The incidentId to set.
     * @return This builder for chaining.
     */
    public Builder setIncidentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      incidentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string incident_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncidentId() {
      incidentId_ = getDefaultInstance().getIncidentId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string incident_id = 2;</code>
     * @param value The bytes for incidentId to set.
     * @return This builder for chaining.
     */
    public Builder setIncidentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      incidentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object audienceDeviceId_ = "";
    /**
     * <pre>
     * único destinatario legítimo
     * </pre>
     *
     * <code>string audience_device_id = 3;</code>
     * @return The audienceDeviceId.
     */
    public java.lang.String getAudienceDeviceId() {
      java.lang.Object ref = audienceDeviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        audienceDeviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * único destinatario legítimo
     * </pre>
     *
     * <code>string audience_device_id = 3;</code>
     * @return The bytes for audienceDeviceId.
     */
    public com.google.protobuf.ByteString
        getAudienceDeviceIdBytes() {
      java.lang.Object ref = audienceDeviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audienceDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * único destinatario legítimo
     * </pre>
     *
     * <code>string audience_device_id = 3;</code>
     * @param value The audienceDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setAudienceDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      audienceDeviceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * único destinatario legítimo
     * </pre>
     *
     * <code>string audience_device_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudienceDeviceId() {
      audienceDeviceId_ = getDefaultInstance().getAudienceDeviceId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * único destinatario legítimo
     * </pre>
     *
     * <code>string audience_device_id = 3;</code>
     * @param value The bytes for audienceDeviceId to set.
     * @return This builder for chaining.
     */
    public Builder setAudienceDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      audienceDeviceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int scope_ = 0;
    /**
     * <code>.helius.v1.DisclosureScope scope = 4;</code>
     * @return The enum numeric value on the wire for scope.
     */
    @java.lang.Override public int getScopeValue() {
      return scope_;
    }
    /**
     * <code>.helius.v1.DisclosureScope scope = 4;</code>
     * @param value The enum numeric value on the wire for scope to set.
     * @return This builder for chaining.
     */
    public Builder setScopeValue(int value) {
      scope_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.DisclosureScope scope = 4;</code>
     * @return The scope.
     */
    @java.lang.Override
    public co.helius.core.protocol.v1.DisclosureScope getScope() {
      co.helius.core.protocol.v1.DisclosureScope result = co.helius.core.protocol.v1.DisclosureScope.forNumber(scope_);
      return result == null ? co.helius.core.protocol.v1.DisclosureScope.UNRECOGNIZED : result;
    }
    /**
     * <code>.helius.v1.DisclosureScope scope = 4;</code>
     * @param value The scope to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setScope(co.helius.core.protocol.v1.DisclosureScope value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      scope_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.DisclosureScope scope = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      bitField0_ = (bitField0_ & ~0x00000008);
      scope_ = 0;
      onChanged();
      return this;
    }

    private int purpose_ = 0;
    /**
     * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
     * @return The enum numeric value on the wire for purpose.
     */
    @java.lang.Override public int getPurposeValue() {
      return purpose_;
    }
    /**
     * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
     * @param value The enum numeric value on the wire for purpose to set.
     * @return This builder for chaining.
     */
    public Builder setPurposeValue(int value) {
      purpose_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
     * @return The purpose.
     */
    @java.lang.Override
    public co.helius.core.protocol.v1.DisclosurePurpose getPurpose() {
      co.helius.core.protocol.v1.DisclosurePurpose result = co.helius.core.protocol.v1.DisclosurePurpose.forNumber(purpose_);
      return result == null ? co.helius.core.protocol.v1.DisclosurePurpose.UNRECOGNIZED : result;
    }
    /**
     * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
     * @param value The purpose to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setPurpose(co.helius.core.protocol.v1.DisclosurePurpose value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000010;
      purpose_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.DisclosurePurpose purpose = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurpose() {
      bitField0_ = (bitField0_ & ~0x00000010);
      purpose_ = 0;
      onChanged();
      return this;
    }

    private int outcome_ = 0;
    /**
     * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
     * @return The enum numeric value on the wire for outcome.
     */
    @java.lang.Override public int getOutcomeValue() {
      return outcome_;
    }
    /**
     * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
     * @param value The enum numeric value on the wire for outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcomeValue(int value) {
      outcome_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
     * @return The outcome.
     */
    @java.lang.Override
    public co.helius.core.protocol.v1.CapsuleOutcome getOutcome() {
      co.helius.core.protocol.v1.CapsuleOutcome result = co.helius.core.protocol.v1.CapsuleOutcome.forNumber(outcome_);
      return result == null ? co.helius.core.protocol.v1.CapsuleOutcome.UNRECOGNIZED : result;
    }
    /**
     * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
     * @param value The outcome to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setOutcome(co.helius.core.protocol.v1.CapsuleOutcome value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000020;
      outcome_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.CapsuleOutcome outcome = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutcome() {
      bitField0_ = (bitField0_ & ~0x00000020);
      outcome_ = 0;
      onChanged();
      return this;
    }

    private long issuedAt_ ;
    /**
     * <code>uint64 issued_at = 7;</code>
     * @return The issuedAt.
     */
    @java.lang.Override
    public long getIssuedAt() {
      return issuedAt_;
    }
    /**
     * <code>uint64 issued_at = 7;</code>
     * @param value The issuedAt to set.
     * @return This builder for chaining.
     */
    public Builder setIssuedAt(long value) {

      issuedAt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 issued_at = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIssuedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      issuedAt_ = 0L;
      onChanged();
      return this;
    }

    private long expiresAt_ ;
    /**
     * <code>uint64 expires_at = 8;</code>
     * @return The expiresAt.
     */
    @java.lang.Override
    public long getExpiresAt() {
      return expiresAt_;
    }
    /**
     * <code>uint64 expires_at = 8;</code>
     * @param value The expiresAt to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresAt(long value) {

      expiresAt_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 expires_at = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresAt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      expiresAt_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
     * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
     * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * DisclosureView serializada. Texto cifrado (X25519 + HKDF + ChaCha20-Poly1305)
     * hacia la clave del destinatario si `payload_encrypted`; si no, proto en claro.
     * </pre>
     *
     * <code>bytes payload = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000100);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private boolean payloadEncrypted_ ;
    /**
     * <code>bool payload_encrypted = 10;</code>
     * @return The payloadEncrypted.
     */
    @java.lang.Override
    public boolean getPayloadEncrypted() {
      return payloadEncrypted_;
    }
    /**
     * <code>bool payload_encrypted = 10;</code>
     * @param value The payloadEncrypted to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadEncrypted(boolean value) {

      payloadEncrypted_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool payload_encrypted = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadEncrypted() {
      bitField0_ = (bitField0_ & ~0x00000200);
      payloadEncrypted_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object recordId_ = "";
    /**
     * <code>optional string record_id = 11;</code>
     * @return Whether the recordId field is set.
     */
    public boolean hasRecordId() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string record_id = 11;</code>
     * @return The recordId.
     */
    public java.lang.String getRecordId() {
      java.lang.Object ref = recordId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string record_id = 11;</code>
     * @return The bytes for recordId.
     */
    public com.google.protobuf.ByteString
        getRecordIdBytes() {
      java.lang.Object ref = recordId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string record_id = 11;</code>
     * @param value The recordId to set.
     * @return This builder for chaining.
     */
    public Builder setRecordId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recordId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>optional string record_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordId() {
      recordId_ = getDefaultInstance().getRecordId();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>optional string record_id = 11;</code>
     * @param value The bytes for recordId to set.
     * @return This builder for chaining.
     */
    public Builder setRecordIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recordId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private int recordVersion_ ;
    /**
     * <pre>
     * descarta copias viejas de otra ruta
     * </pre>
     *
     * <code>optional uint32 record_version = 12;</code>
     * @return Whether the recordVersion field is set.
     */
    @java.lang.Override
    public boolean hasRecordVersion() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     * descarta copias viejas de otra ruta
     * </pre>
     *
     * <code>optional uint32 record_version = 12;</code>
     * @return The recordVersion.
     */
    @java.lang.Override
    public int getRecordVersion() {
      return recordVersion_;
    }
    /**
     * <pre>
     * descarta copias viejas de otra ruta
     * </pre>
     *
     * <code>optional uint32 record_version = 12;</code>
     * @param value The recordVersion to set.
     * @return This builder for chaining.
     */
    public Builder setRecordVersion(int value) {

      recordVersion_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * descarta copias viejas de otra ruta
     * </pre>
     *
     * <code>optional uint32 record_version = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordVersion() {
      bitField0_ = (bitField0_ & ~0x00000800);
      recordVersion_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList reasons_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReasonsIsMutable() {
      if (!reasons_.isModifiable()) {
        reasons_ = new com.google.protobuf.LazyStringArrayList(reasons_);
      }
      bitField0_ |= 0x00001000;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @return A list containing the reasons.
     */
    public com.google.protobuf.ProtocolStringList
        getReasonsList() {
      reasons_.makeImmutable();
      return reasons_;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @return The count of reasons.
     */
    public int getReasonsCount() {
      return reasons_.size();
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param index The index of the element to return.
     * @return The reasons at the given index.
     */
    public java.lang.String getReasons(int index) {
      return reasons_.get(index);
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reasons at the given index.
     */
    public com.google.protobuf.ByteString
        getReasonsBytes(int index) {
      return reasons_.getByteString(index);
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param index The index to set the value at.
     * @param value The reasons to set.
     * @return This builder for chaining.
     */
    public Builder setReasons(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReasonsIsMutable();
      reasons_.set(index, value);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param value The reasons to add.
     * @return This builder for chaining.
     */
    public Builder addReasons(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReasonsIsMutable();
      reasons_.add(value);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param values The reasons to add.
     * @return This builder for chaining.
     */
    public Builder addAllReasons(
        java.lang.Iterable<java.lang.String> values) {
      ensureReasonsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reasons_);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasons() {
      reasons_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00001000);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * por qué se negó o qué se recortó
     * </pre>
     *
     * <code>repeated string reasons = 13;</code>
     * @param value The bytes of the reasons to add.
     * @return This builder for chaining.
     */
    public Builder addReasonsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReasonsIsMutable();
      reasons_.add(value);
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object auditId_ = "";
    /**
     * <code>string audit_id = 14;</code>
     * @return The auditId.
     */
    public java.lang.String getAuditId() {
      java.lang.Object ref = auditId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        auditId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string audit_id = 14;</code>
     * @return The bytes for auditId.
     */
    public com.google.protobuf.ByteString
        getAuditIdBytes() {
      java.lang.Object ref = auditId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auditId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string audit_id = 14;</code>
     * @param value The auditId to set.
     * @return This builder for chaining.
     */
    public Builder setAuditId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      auditId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>string audit_id = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuditId() {
      auditId_ = getDefaultInstance().getAuditId();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <code>string audit_id = 14;</code>
     * @param value The bytes for auditId to set.
     * @return This builder for chaining.
     */
    public Builder setAuditIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      auditId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private int maxHops_ ;
    /**
     * <code>uint32 max_hops = 15;</code>
     * @return The maxHops.
     */
    @java.lang.Override
    public int getMaxHops() {
      return maxHops_;
    }
    /**
     * <code>uint32 max_hops = 15;</code>
     * @param value The maxHops to set.
     * @return This builder for chaining.
     */
    public Builder setMaxHops(int value) {

      maxHops_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 max_hops = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxHops() {
      bitField0_ = (bitField0_ & ~0x00004000);
      maxHops_ = 0;
      onChanged();
      return this;
    }

    private boolean retransmitAllowed_ ;
    /**
     * <code>bool retransmit_allowed = 16;</code>
     * @return The retransmitAllowed.
     */
    @java.lang.Override
    public boolean getRetransmitAllowed() {
      return retransmitAllowed_;
    }
    /**
     * <code>bool retransmit_allowed = 16;</code>
     * @param value The retransmitAllowed to set.
     * @return This builder for chaining.
     */
    public Builder setRetransmitAllowed(boolean value) {

      retransmitAllowed_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>bool retransmit_allowed = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetransmitAllowed() {
      bitField0_ = (bitField0_ & ~0x00008000);
      retransmitAllowed_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Ed25519 del servicio
     * </pre>
     *
     * <code>bytes signature = 17;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * Ed25519 del servicio
     * </pre>
     *
     * <code>bytes signature = 17;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ed25519 del servicio
     * </pre>
     *
     * <code>bytes signature = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00010000);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helius.v1.DisclosureCapsule)
  }

  // @@protoc_insertion_point(class_scope:helius.v1.DisclosureCapsule)
  private static final co.helius.core.protocol.v1.DisclosureCapsule DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.helius.core.protocol.v1.DisclosureCapsule();
  }

  public static co.helius.core.protocol.v1.DisclosureCapsule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DisclosureCapsule>
      PARSER = new com.google.protobuf.AbstractParser<DisclosureCapsule>() {
    @java.lang.Override
    public DisclosureCapsule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DisclosureCapsule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DisclosureCapsule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.helius.core.protocol.v1.DisclosureCapsule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

