// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/status.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * Protobuf type {@code helius.v1.EmergencyStatus}
 */
@com.google.protobuf.Generated
public final class EmergencyStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helius.v1.EmergencyStatus)
    EmergencyStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "EmergencyStatus");
  }
  // Use EmergencyStatus.newBuilder() to construct.
  private EmergencyStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmergencyStatus() {
    source_ = "";
    responseState_ = 0;
    deviceState_ = "";
    evidenceRefs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.helius.core.protocol.v1.EmergencyStatus.class, co.helius.core.protocol.v1.EmergencyStatus.Builder.class);
  }

  private int bitField0_;
  public static final int LOCATION_FIELD_NUMBER = 1;
  private co.helius.core.protocol.v1.GeoPoint location_;
  /**
   * <code>optional .helius.v1.GeoPoint location = 1;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .helius.v1.GeoPoint location = 1;</code>
   * @return The location.
   */
  @java.lang.Override
  public co.helius.core.protocol.v1.GeoPoint getLocation() {
    return location_ == null ? co.helius.core.protocol.v1.GeoPoint.getDefaultInstance() : location_;
  }
  /**
   * <code>optional .helius.v1.GeoPoint location = 1;</code>
   */
  @java.lang.Override
  public co.helius.core.protocol.v1.GeoPointOrBuilder getLocationOrBuilder() {
    return location_ == null ? co.helius.core.protocol.v1.GeoPoint.getDefaultInstance() : location_;
  }

  public static final int TS_FIELD_NUMBER = 2;
  private long ts_ = 0L;
  /**
   * <code>uint64 ts = 2;</code>
   * @return The ts.
   */
  @java.lang.Override
  public long getTs() {
    return ts_;
  }

  public static final int SOURCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <code>string source = 3;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>string source = 3;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_STATE_FIELD_NUMBER = 4;
  private int responseState_ = 0;
  /**
   * <code>.helius.v1.ResponseState response_state = 4;</code>
   * @return The enum numeric value on the wire for responseState.
   */
  @java.lang.Override public int getResponseStateValue() {
    return responseState_;
  }
  /**
   * <code>.helius.v1.ResponseState response_state = 4;</code>
   * @return The responseState.
   */
  @java.lang.Override public co.helius.core.protocol.v1.ResponseState getResponseState() {
    co.helius.core.protocol.v1.ResponseState result = co.helius.core.protocol.v1.ResponseState.forNumber(responseState_);
    return result == null ? co.helius.core.protocol.v1.ResponseState.UNRECOGNIZED : result;
  }

  public static final int BATTERY_FIELD_NUMBER = 5;
  private int battery_ = 0;
  /**
   * <pre>
   * 0-100
   * </pre>
   *
   * <code>uint32 battery = 5;</code>
   * @return The battery.
   */
  @java.lang.Override
  public int getBattery() {
    return battery_;
  }

  public static final int DEVICE_STATE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceState_ = "";
  /**
   * <code>string device_state = 6;</code>
   * @return The deviceState.
   */
  @java.lang.Override
  public java.lang.String getDeviceState() {
    java.lang.Object ref = deviceState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceState_ = s;
      return s;
    }
  }
  /**
   * <code>string device_state = 6;</code>
   * @return The bytes for deviceState.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceStateBytes() {
    java.lang.Object ref = deviceState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVIDENCE_REFS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList evidenceRefs_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string evidence_refs = 7;</code>
   * @return A list containing the evidenceRefs.
   */
  public com.google.protobuf.ProtocolStringList
      getEvidenceRefsList() {
    return evidenceRefs_;
  }
  /**
   * <code>repeated string evidence_refs = 7;</code>
   * @return The count of evidenceRefs.
   */
  public int getEvidenceRefsCount() {
    return evidenceRefs_.size();
  }
  /**
   * <code>repeated string evidence_refs = 7;</code>
   * @param index The index of the element to return.
   * @return The evidenceRefs at the given index.
   */
  public java.lang.String getEvidenceRefs(int index) {
    return evidenceRefs_.get(index);
  }
  /**
   * <code>repeated string evidence_refs = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the evidenceRefs at the given index.
   */
  public com.google.protobuf.ByteString
      getEvidenceRefsBytes(int index) {
    return evidenceRefs_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLocation());
    }
    if (ts_ != 0L) {
      output.writeUInt64(2, ts_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, source_);
    }
    if (responseState_ != co.helius.core.protocol.v1.ResponseState.UNKNOWN.getNumber()) {
      output.writeEnum(4, responseState_);
    }
    if (battery_ != 0) {
      output.writeUInt32(5, battery_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceState_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, deviceState_);
    }
    for (int i = 0; i < evidenceRefs_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, evidenceRefs_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLocation());
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ts_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, source_);
    }
    if (responseState_ != co.helius.core.protocol.v1.ResponseState.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, responseState_);
    }
    if (battery_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, battery_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceState_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, deviceState_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < evidenceRefs_.size(); i++) {
        dataSize += computeStringSizeNoTag(evidenceRefs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEvidenceRefsList().size();
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.helius.core.protocol.v1.EmergencyStatus)) {
      return super.equals(obj);
    }
    co.helius.core.protocol.v1.EmergencyStatus other = (co.helius.core.protocol.v1.EmergencyStatus) obj;

    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (getTs()
        != other.getTs()) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (responseState_ != other.responseState_) return false;
    if (getBattery()
        != other.getBattery()) return false;
    if (!getDeviceState()
        .equals(other.getDeviceState())) return false;
    if (!getEvidenceRefsList()
        .equals(other.getEvidenceRefsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + RESPONSE_STATE_FIELD_NUMBER;
    hash = (53 * hash) + responseState_;
    hash = (37 * hash) + BATTERY_FIELD_NUMBER;
    hash = (53 * hash) + getBattery();
    hash = (37 * hash) + DEVICE_STATE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceState().hashCode();
    if (getEvidenceRefsCount() > 0) {
      hash = (37 * hash) + EVIDENCE_REFS_FIELD_NUMBER;
      hash = (53 * hash) + getEvidenceRefsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.helius.core.protocol.v1.EmergencyStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.helius.core.protocol.v1.EmergencyStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.EmergencyStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.helius.core.protocol.v1.EmergencyStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helius.v1.EmergencyStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helius.v1.EmergencyStatus)
      co.helius.core.protocol.v1.EmergencyStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.helius.core.protocol.v1.EmergencyStatus.class, co.helius.core.protocol.v1.EmergencyStatus.Builder.class);
    }

    // Construct using co.helius.core.protocol.v1.EmergencyStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      ts_ = 0L;
      source_ = "";
      responseState_ = 0;
      battery_ = 0;
      deviceState_ = "";
      evidenceRefs_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.helius.core.protocol.v1.Status.internal_static_helius_v1_EmergencyStatus_descriptor;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyStatus getDefaultInstanceForType() {
      return co.helius.core.protocol.v1.EmergencyStatus.getDefaultInstance();
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyStatus build() {
      co.helius.core.protocol.v1.EmergencyStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyStatus buildPartial() {
      co.helius.core.protocol.v1.EmergencyStatus result = new co.helius.core.protocol.v1.EmergencyStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.helius.core.protocol.v1.EmergencyStatus result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.location_ = locationBuilder_ == null
            ? location_
            : locationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ts_ = ts_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.responseState_ = responseState_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.battery_ = battery_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.deviceState_ = deviceState_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        evidenceRefs_.makeImmutable();
        result.evidenceRefs_ = evidenceRefs_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.helius.core.protocol.v1.EmergencyStatus) {
        return mergeFrom((co.helius.core.protocol.v1.EmergencyStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.helius.core.protocol.v1.EmergencyStatus other) {
      if (other == co.helius.core.protocol.v1.EmergencyStatus.getDefaultInstance()) return this;
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.responseState_ != 0) {
        setResponseStateValue(other.getResponseStateValue());
      }
      if (other.getBattery() != 0) {
        setBattery(other.getBattery());
      }
      if (!other.getDeviceState().isEmpty()) {
        deviceState_ = other.deviceState_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.evidenceRefs_.isEmpty()) {
        if (evidenceRefs_.isEmpty()) {
          evidenceRefs_ = other.evidenceRefs_;
          bitField0_ |= 0x00000040;
        } else {
          ensureEvidenceRefsIsMutable();
          evidenceRefs_.addAll(other.evidenceRefs_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              ts_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              responseState_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              battery_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              deviceState_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              ensureEvidenceRefsIsMutable();
              evidenceRefs_.add(input.readStringRequireUtf8());
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private co.helius.core.protocol.v1.GeoPoint location_;
    private com.google.protobuf.SingleFieldBuilder<
        co.helius.core.protocol.v1.GeoPoint, co.helius.core.protocol.v1.GeoPoint.Builder, co.helius.core.protocol.v1.GeoPointOrBuilder> locationBuilder_;
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     * @return The location.
     */
    public co.helius.core.protocol.v1.GeoPoint getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? co.helius.core.protocol.v1.GeoPoint.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public Builder setLocation(co.helius.core.protocol.v1.GeoPoint value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
      } else {
        locationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public Builder setLocation(
        co.helius.core.protocol.v1.GeoPoint.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public Builder mergeLocation(co.helius.core.protocol.v1.GeoPoint value) {
      if (locationBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          location_ != null &&
          location_ != co.helius.core.protocol.v1.GeoPoint.getDefaultInstance()) {
          getLocationBuilder().mergeFrom(value);
        } else {
          location_ = value;
        }
      } else {
        locationBuilder_.mergeFrom(value);
      }
      if (location_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000001);
      location_ = null;
      if (locationBuilder_ != null) {
        locationBuilder_.dispose();
        locationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public co.helius.core.protocol.v1.GeoPoint.Builder getLocationBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    public co.helius.core.protocol.v1.GeoPointOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            co.helius.core.protocol.v1.GeoPoint.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>optional .helius.v1.GeoPoint location = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.helius.core.protocol.v1.GeoPoint, co.helius.core.protocol.v1.GeoPoint.Builder, co.helius.core.protocol.v1.GeoPointOrBuilder> 
        internalGetLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.helius.core.protocol.v1.GeoPoint, co.helius.core.protocol.v1.GeoPoint.Builder, co.helius.core.protocol.v1.GeoPointOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private long ts_ ;
    /**
     * <code>uint64 ts = 2;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return ts_;
    }
    /**
     * <code>uint64 ts = 2;</code>
     * @param value The ts to set.
     * @return This builder for chaining.
     */
    public Builder setTs(long value) {

      ts_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ts = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ts_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <code>string source = 3;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source = 3;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source = 3;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string source = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string source = 3;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int responseState_ = 0;
    /**
     * <code>.helius.v1.ResponseState response_state = 4;</code>
     * @return The enum numeric value on the wire for responseState.
     */
    @java.lang.Override public int getResponseStateValue() {
      return responseState_;
    }
    /**
     * <code>.helius.v1.ResponseState response_state = 4;</code>
     * @param value The enum numeric value on the wire for responseState to set.
     * @return This builder for chaining.
     */
    public Builder setResponseStateValue(int value) {
      responseState_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.ResponseState response_state = 4;</code>
     * @return The responseState.
     */
    @java.lang.Override
    public co.helius.core.protocol.v1.ResponseState getResponseState() {
      co.helius.core.protocol.v1.ResponseState result = co.helius.core.protocol.v1.ResponseState.forNumber(responseState_);
      return result == null ? co.helius.core.protocol.v1.ResponseState.UNRECOGNIZED : result;
    }
    /**
     * <code>.helius.v1.ResponseState response_state = 4;</code>
     * @param value The responseState to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setResponseState(co.helius.core.protocol.v1.ResponseState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      responseState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.helius.v1.ResponseState response_state = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseState() {
      bitField0_ = (bitField0_ & ~0x00000008);
      responseState_ = 0;
      onChanged();
      return this;
    }

    private int battery_ ;
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>uint32 battery = 5;</code>
     * @return The battery.
     */
    @java.lang.Override
    public int getBattery() {
      return battery_;
    }
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>uint32 battery = 5;</code>
     * @param value The battery to set.
     * @return This builder for chaining.
     */
    public Builder setBattery(int value) {

      battery_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-100
     * </pre>
     *
     * <code>uint32 battery = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBattery() {
      bitField0_ = (bitField0_ & ~0x00000010);
      battery_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceState_ = "";
    /**
     * <code>string device_state = 6;</code>
     * @return The deviceState.
     */
    public java.lang.String getDeviceState() {
      java.lang.Object ref = deviceState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_state = 6;</code>
     * @return The bytes for deviceState.
     */
    public com.google.protobuf.ByteString
        getDeviceStateBytes() {
      java.lang.Object ref = deviceState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_state = 6;</code>
     * @param value The deviceState to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceState(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceState_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string device_state = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceState() {
      deviceState_ = getDefaultInstance().getDeviceState();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string device_state = 6;</code>
     * @param value The bytes for deviceState to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceState_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList evidenceRefs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureEvidenceRefsIsMutable() {
      if (!evidenceRefs_.isModifiable()) {
        evidenceRefs_ = new com.google.protobuf.LazyStringArrayList(evidenceRefs_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @return A list containing the evidenceRefs.
     */
    public com.google.protobuf.ProtocolStringList
        getEvidenceRefsList() {
      evidenceRefs_.makeImmutable();
      return evidenceRefs_;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @return The count of evidenceRefs.
     */
    public int getEvidenceRefsCount() {
      return evidenceRefs_.size();
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param index The index of the element to return.
     * @return The evidenceRefs at the given index.
     */
    public java.lang.String getEvidenceRefs(int index) {
      return evidenceRefs_.get(index);
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the evidenceRefs at the given index.
     */
    public com.google.protobuf.ByteString
        getEvidenceRefsBytes(int index) {
      return evidenceRefs_.getByteString(index);
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param index The index to set the value at.
     * @param value The evidenceRefs to set.
     * @return This builder for chaining.
     */
    public Builder setEvidenceRefs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEvidenceRefsIsMutable();
      evidenceRefs_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param value The evidenceRefs to add.
     * @return This builder for chaining.
     */
    public Builder addEvidenceRefs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEvidenceRefsIsMutable();
      evidenceRefs_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param values The evidenceRefs to add.
     * @return This builder for chaining.
     */
    public Builder addAllEvidenceRefs(
        java.lang.Iterable<java.lang.String> values) {
      ensureEvidenceRefsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, evidenceRefs_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvidenceRefs() {
      evidenceRefs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string evidence_refs = 7;</code>
     * @param value The bytes of the evidenceRefs to add.
     * @return This builder for chaining.
     */
    public Builder addEvidenceRefsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEvidenceRefsIsMutable();
      evidenceRefs_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helius.v1.EmergencyStatus)
  }

  // @@protoc_insertion_point(class_scope:helius.v1.EmergencyStatus)
  private static final co.helius.core.protocol.v1.EmergencyStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.helius.core.protocol.v1.EmergencyStatus();
  }

  public static co.helius.core.protocol.v1.EmergencyStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmergencyStatus>
      PARSER = new com.google.protobuf.AbstractParser<EmergencyStatus>() {
    @java.lang.Override
    public EmergencyStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmergencyStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmergencyStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.helius.core.protocol.v1.EmergencyStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

