// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/identity.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Definida por el usuario en modo "Preparación" (docs/architecture/OVERVIEW.md §1).
 * Determina qué campos del perfil son visibles para cada tipo de destinatario.
 * </pre>
 *
 * Protobuf type {@code helius.v1.EmergencyDataPolicy}
 */
@com.google.protobuf.Generated
public final class EmergencyDataPolicy extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helius.v1.EmergencyDataPolicy)
    EmergencyDataPolicyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "EmergencyDataPolicy");
  }
  // Use EmergencyDataPolicy.newBuilder() to construct.
  private EmergencyDataPolicy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmergencyDataPolicy() {
    familyRecipientPublicKeys_ = emptyList(com.google.protobuf.ByteString.class);
    authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.helius.core.protocol.v1.EmergencyDataPolicy.class, co.helius.core.protocol.v1.EmergencyDataPolicy.Builder.class);
  }

  public static final int SHARE_NAME_WITH_FAMILY_FIELD_NUMBER = 1;
  private boolean shareNameWithFamily_ = false;
  /**
   * <code>bool share_name_with_family = 1;</code>
   * @return The shareNameWithFamily.
   */
  @java.lang.Override
  public boolean getShareNameWithFamily() {
    return shareNameWithFamily_;
  }

  public static final int SHARE_NAME_WITH_AUTHORITY_FIELD_NUMBER = 2;
  private boolean shareNameWithAuthority_ = false;
  /**
   * <code>bool share_name_with_authority = 2;</code>
   * @return The shareNameWithAuthority.
   */
  @java.lang.Override
  public boolean getShareNameWithAuthority() {
    return shareNameWithAuthority_;
  }

  public static final int SHARE_MEDICAL_NOTES_WITH_FAMILY_FIELD_NUMBER = 3;
  private boolean shareMedicalNotesWithFamily_ = false;
  /**
   * <code>bool share_medical_notes_with_family = 3;</code>
   * @return The shareMedicalNotesWithFamily.
   */
  @java.lang.Override
  public boolean getShareMedicalNotesWithFamily() {
    return shareMedicalNotesWithFamily_;
  }

  public static final int SHARE_MEDICAL_NOTES_WITH_AUTHORITY_FIELD_NUMBER = 4;
  private boolean shareMedicalNotesWithAuthority_ = false;
  /**
   * <code>bool share_medical_notes_with_authority = 4;</code>
   * @return The shareMedicalNotesWithAuthority.
   */
  @java.lang.Override
  public boolean getShareMedicalNotesWithAuthority() {
    return shareMedicalNotesWithAuthority_;
  }

  public static final int FAMILY_RECIPIENT_PUBLIC_KEYS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> familyRecipientPublicKeys_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <pre>
   * X25519, uno por familiar vinculado y consentido
   * </pre>
   *
   * <code>repeated bytes family_recipient_public_keys = 5;</code>
   * @return A list containing the familyRecipientPublicKeys.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getFamilyRecipientPublicKeysList() {
    return familyRecipientPublicKeys_;
  }
  /**
   * <pre>
   * X25519, uno por familiar vinculado y consentido
   * </pre>
   *
   * <code>repeated bytes family_recipient_public_keys = 5;</code>
   * @return The count of familyRecipientPublicKeys.
   */
  public int getFamilyRecipientPublicKeysCount() {
    return familyRecipientPublicKeys_.size();
  }
  /**
   * <pre>
   * X25519, uno por familiar vinculado y consentido
   * </pre>
   *
   * <code>repeated bytes family_recipient_public_keys = 5;</code>
   * @param index The index of the element to return.
   * @return The familyRecipientPublicKeys at the given index.
   */
  public com.google.protobuf.ByteString getFamilyRecipientPublicKeys(int index) {
    return familyRecipientPublicKeys_.get(index);
  }

  public static final int AUTHORITY_PUBLIC_KEY_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * de la autoridad del incidente activo
   * </pre>
   *
   * <code>bytes authority_public_key = 6;</code>
   * @return The authorityPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAuthorityPublicKey() {
    return authorityPublicKey_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (shareNameWithFamily_ != false) {
      output.writeBool(1, shareNameWithFamily_);
    }
    if (shareNameWithAuthority_ != false) {
      output.writeBool(2, shareNameWithAuthority_);
    }
    if (shareMedicalNotesWithFamily_ != false) {
      output.writeBool(3, shareMedicalNotesWithFamily_);
    }
    if (shareMedicalNotesWithAuthority_ != false) {
      output.writeBool(4, shareMedicalNotesWithAuthority_);
    }
    for (int i = 0; i < familyRecipientPublicKeys_.size(); i++) {
      output.writeBytes(5, familyRecipientPublicKeys_.get(i));
    }
    if (!authorityPublicKey_.isEmpty()) {
      output.writeBytes(6, authorityPublicKey_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (shareNameWithFamily_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, shareNameWithFamily_);
    }
    if (shareNameWithAuthority_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, shareNameWithAuthority_);
    }
    if (shareMedicalNotesWithFamily_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, shareMedicalNotesWithFamily_);
    }
    if (shareMedicalNotesWithAuthority_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, shareMedicalNotesWithAuthority_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < familyRecipientPublicKeys_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(familyRecipientPublicKeys_.get(i));
      }
      size += dataSize;
      size += 1 * getFamilyRecipientPublicKeysList().size();
    }
    if (!authorityPublicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, authorityPublicKey_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.helius.core.protocol.v1.EmergencyDataPolicy)) {
      return super.equals(obj);
    }
    co.helius.core.protocol.v1.EmergencyDataPolicy other = (co.helius.core.protocol.v1.EmergencyDataPolicy) obj;

    if (getShareNameWithFamily()
        != other.getShareNameWithFamily()) return false;
    if (getShareNameWithAuthority()
        != other.getShareNameWithAuthority()) return false;
    if (getShareMedicalNotesWithFamily()
        != other.getShareMedicalNotesWithFamily()) return false;
    if (getShareMedicalNotesWithAuthority()
        != other.getShareMedicalNotesWithAuthority()) return false;
    if (!getFamilyRecipientPublicKeysList()
        .equals(other.getFamilyRecipientPublicKeysList())) return false;
    if (!getAuthorityPublicKey()
        .equals(other.getAuthorityPublicKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHARE_NAME_WITH_FAMILY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShareNameWithFamily());
    hash = (37 * hash) + SHARE_NAME_WITH_AUTHORITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShareNameWithAuthority());
    hash = (37 * hash) + SHARE_MEDICAL_NOTES_WITH_FAMILY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShareMedicalNotesWithFamily());
    hash = (37 * hash) + SHARE_MEDICAL_NOTES_WITH_AUTHORITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShareMedicalNotesWithAuthority());
    if (getFamilyRecipientPublicKeysCount() > 0) {
      hash = (37 * hash) + FAMILY_RECIPIENT_PUBLIC_KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getFamilyRecipientPublicKeysList().hashCode();
    }
    hash = (37 * hash) + AUTHORITY_PUBLIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorityPublicKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.EmergencyDataPolicy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.helius.core.protocol.v1.EmergencyDataPolicy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Definida por el usuario en modo "Preparación" (docs/architecture/OVERVIEW.md §1).
   * Determina qué campos del perfil son visibles para cada tipo de destinatario.
   * </pre>
   *
   * Protobuf type {@code helius.v1.EmergencyDataPolicy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helius.v1.EmergencyDataPolicy)
      co.helius.core.protocol.v1.EmergencyDataPolicyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.helius.core.protocol.v1.EmergencyDataPolicy.class, co.helius.core.protocol.v1.EmergencyDataPolicy.Builder.class);
    }

    // Construct using co.helius.core.protocol.v1.EmergencyDataPolicy.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      shareNameWithFamily_ = false;
      shareNameWithAuthority_ = false;
      shareMedicalNotesWithFamily_ = false;
      shareMedicalNotesWithAuthority_ = false;
      familyRecipientPublicKeys_ = emptyList(com.google.protobuf.ByteString.class);
      authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.helius.core.protocol.v1.Identity.internal_static_helius_v1_EmergencyDataPolicy_descriptor;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyDataPolicy getDefaultInstanceForType() {
      return co.helius.core.protocol.v1.EmergencyDataPolicy.getDefaultInstance();
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyDataPolicy build() {
      co.helius.core.protocol.v1.EmergencyDataPolicy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.EmergencyDataPolicy buildPartial() {
      co.helius.core.protocol.v1.EmergencyDataPolicy result = new co.helius.core.protocol.v1.EmergencyDataPolicy(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.helius.core.protocol.v1.EmergencyDataPolicy result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.shareNameWithFamily_ = shareNameWithFamily_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.shareNameWithAuthority_ = shareNameWithAuthority_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.shareMedicalNotesWithFamily_ = shareMedicalNotesWithFamily_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.shareMedicalNotesWithAuthority_ = shareMedicalNotesWithAuthority_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        familyRecipientPublicKeys_.makeImmutable();
        result.familyRecipientPublicKeys_ = familyRecipientPublicKeys_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.authorityPublicKey_ = authorityPublicKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.helius.core.protocol.v1.EmergencyDataPolicy) {
        return mergeFrom((co.helius.core.protocol.v1.EmergencyDataPolicy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.helius.core.protocol.v1.EmergencyDataPolicy other) {
      if (other == co.helius.core.protocol.v1.EmergencyDataPolicy.getDefaultInstance()) return this;
      if (other.getShareNameWithFamily() != false) {
        setShareNameWithFamily(other.getShareNameWithFamily());
      }
      if (other.getShareNameWithAuthority() != false) {
        setShareNameWithAuthority(other.getShareNameWithAuthority());
      }
      if (other.getShareMedicalNotesWithFamily() != false) {
        setShareMedicalNotesWithFamily(other.getShareMedicalNotesWithFamily());
      }
      if (other.getShareMedicalNotesWithAuthority() != false) {
        setShareMedicalNotesWithAuthority(other.getShareMedicalNotesWithAuthority());
      }
      if (!other.familyRecipientPublicKeys_.isEmpty()) {
        if (familyRecipientPublicKeys_.isEmpty()) {
          familyRecipientPublicKeys_ = other.familyRecipientPublicKeys_;
          familyRecipientPublicKeys_.makeImmutable();
          bitField0_ |= 0x00000010;
        } else {
          ensureFamilyRecipientPublicKeysIsMutable();
          familyRecipientPublicKeys_.addAll(other.familyRecipientPublicKeys_);
        }
        onChanged();
      }
      if (!other.getAuthorityPublicKey().isEmpty()) {
        setAuthorityPublicKey(other.getAuthorityPublicKey());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              shareNameWithFamily_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              shareNameWithAuthority_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              shareMedicalNotesWithFamily_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              shareMedicalNotesWithAuthority_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureFamilyRecipientPublicKeysIsMutable();
              familyRecipientPublicKeys_.add(v);
              break;
            } // case 42
            case 50: {
              authorityPublicKey_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean shareNameWithFamily_ ;
    /**
     * <code>bool share_name_with_family = 1;</code>
     * @return The shareNameWithFamily.
     */
    @java.lang.Override
    public boolean getShareNameWithFamily() {
      return shareNameWithFamily_;
    }
    /**
     * <code>bool share_name_with_family = 1;</code>
     * @param value The shareNameWithFamily to set.
     * @return This builder for chaining.
     */
    public Builder setShareNameWithFamily(boolean value) {

      shareNameWithFamily_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool share_name_with_family = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearShareNameWithFamily() {
      bitField0_ = (bitField0_ & ~0x00000001);
      shareNameWithFamily_ = false;
      onChanged();
      return this;
    }

    private boolean shareNameWithAuthority_ ;
    /**
     * <code>bool share_name_with_authority = 2;</code>
     * @return The shareNameWithAuthority.
     */
    @java.lang.Override
    public boolean getShareNameWithAuthority() {
      return shareNameWithAuthority_;
    }
    /**
     * <code>bool share_name_with_authority = 2;</code>
     * @param value The shareNameWithAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setShareNameWithAuthority(boolean value) {

      shareNameWithAuthority_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool share_name_with_authority = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearShareNameWithAuthority() {
      bitField0_ = (bitField0_ & ~0x00000002);
      shareNameWithAuthority_ = false;
      onChanged();
      return this;
    }

    private boolean shareMedicalNotesWithFamily_ ;
    /**
     * <code>bool share_medical_notes_with_family = 3;</code>
     * @return The shareMedicalNotesWithFamily.
     */
    @java.lang.Override
    public boolean getShareMedicalNotesWithFamily() {
      return shareMedicalNotesWithFamily_;
    }
    /**
     * <code>bool share_medical_notes_with_family = 3;</code>
     * @param value The shareMedicalNotesWithFamily to set.
     * @return This builder for chaining.
     */
    public Builder setShareMedicalNotesWithFamily(boolean value) {

      shareMedicalNotesWithFamily_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool share_medical_notes_with_family = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearShareMedicalNotesWithFamily() {
      bitField0_ = (bitField0_ & ~0x00000004);
      shareMedicalNotesWithFamily_ = false;
      onChanged();
      return this;
    }

    private boolean shareMedicalNotesWithAuthority_ ;
    /**
     * <code>bool share_medical_notes_with_authority = 4;</code>
     * @return The shareMedicalNotesWithAuthority.
     */
    @java.lang.Override
    public boolean getShareMedicalNotesWithAuthority() {
      return shareMedicalNotesWithAuthority_;
    }
    /**
     * <code>bool share_medical_notes_with_authority = 4;</code>
     * @param value The shareMedicalNotesWithAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setShareMedicalNotesWithAuthority(boolean value) {

      shareMedicalNotesWithAuthority_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool share_medical_notes_with_authority = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearShareMedicalNotesWithAuthority() {
      bitField0_ = (bitField0_ & ~0x00000008);
      shareMedicalNotesWithAuthority_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> familyRecipientPublicKeys_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureFamilyRecipientPublicKeysIsMutable() {
      if (!familyRecipientPublicKeys_.isModifiable()) {
        familyRecipientPublicKeys_ = makeMutableCopy(familyRecipientPublicKeys_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @return A list containing the familyRecipientPublicKeys.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getFamilyRecipientPublicKeysList() {
      familyRecipientPublicKeys_.makeImmutable();
      return familyRecipientPublicKeys_;
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @return The count of familyRecipientPublicKeys.
     */
    public int getFamilyRecipientPublicKeysCount() {
      return familyRecipientPublicKeys_.size();
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @param index The index of the element to return.
     * @return The familyRecipientPublicKeys at the given index.
     */
    public com.google.protobuf.ByteString getFamilyRecipientPublicKeys(int index) {
      return familyRecipientPublicKeys_.get(index);
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @param index The index to set the value at.
     * @param value The familyRecipientPublicKeys to set.
     * @return This builder for chaining.
     */
    public Builder setFamilyRecipientPublicKeys(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFamilyRecipientPublicKeysIsMutable();
      familyRecipientPublicKeys_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @param value The familyRecipientPublicKeys to add.
     * @return This builder for chaining.
     */
    public Builder addFamilyRecipientPublicKeys(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFamilyRecipientPublicKeysIsMutable();
      familyRecipientPublicKeys_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @param values The familyRecipientPublicKeys to add.
     * @return This builder for chaining.
     */
    public Builder addAllFamilyRecipientPublicKeys(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureFamilyRecipientPublicKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, familyRecipientPublicKeys_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * X25519, uno por familiar vinculado y consentido
     * </pre>
     *
     * <code>repeated bytes family_recipient_public_keys = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFamilyRecipientPublicKeys() {
      familyRecipientPublicKeys_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * de la autoridad del incidente activo
     * </pre>
     *
     * <code>bytes authority_public_key = 6;</code>
     * @return The authorityPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAuthorityPublicKey() {
      return authorityPublicKey_;
    }
    /**
     * <pre>
     * de la autoridad del incidente activo
     * </pre>
     *
     * <code>bytes authority_public_key = 6;</code>
     * @param value The authorityPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorityPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      authorityPublicKey_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * de la autoridad del incidente activo
     * </pre>
     *
     * <code>bytes authority_public_key = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorityPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000020);
      authorityPublicKey_ = getDefaultInstance().getAuthorityPublicKey();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helius.v1.EmergencyDataPolicy)
  }

  // @@protoc_insertion_point(class_scope:helius.v1.EmergencyDataPolicy)
  private static final co.helius.core.protocol.v1.EmergencyDataPolicy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.helius.core.protocol.v1.EmergencyDataPolicy();
  }

  public static co.helius.core.protocol.v1.EmergencyDataPolicy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmergencyDataPolicy>
      PARSER = new com.google.protobuf.AbstractParser<EmergencyDataPolicy>() {
    @java.lang.Override
    public EmergencyDataPolicy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmergencyDataPolicy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmergencyDataPolicy> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.helius.core.protocol.v1.EmergencyDataPolicy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

