// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/incident.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Configuración de incidente que el gateway inyecta hacia la malla (DTN inversa,
 * Sección 8.6): IDs ya confirmados, pesos de prioridad, clave pública de la autoridad.
 * Dueño: Helmut.
 * </pre>
 *
 * Protobuf type {@code helius.v1.IncidentConfig}
 */
@com.google.protobuf.Generated
public final class IncidentConfig extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helius.v1.IncidentConfig)
    IncidentConfigOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "IncidentConfig");
  }
  // Use IncidentConfig.newBuilder() to construct.
  private IncidentConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IncidentConfig() {
    incidentId_ = com.google.protobuf.ByteString.EMPTY;
    confirmedBundleIds_ = emptyList(com.google.protobuf.ByteString.class);
    priorityWeightsJson_ = com.google.protobuf.ByteString.EMPTY;
    authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    safetyInstructionsCiphertext_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.helius.core.protocol.v1.IncidentConfig.class, co.helius.core.protocol.v1.IncidentConfig.Builder.class);
  }

  public static final int INCIDENT_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString incidentId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes incident_id = 1;</code>
   * @return The incidentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIncidentId() {
    return incidentId_;
  }

  public static final int CONFIRMED_BUNDLE_IDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> confirmedBundleIds_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <code>repeated bytes confirmed_bundle_ids = 2;</code>
   * @return A list containing the confirmedBundleIds.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getConfirmedBundleIdsList() {
    return confirmedBundleIds_;
  }
  /**
   * <code>repeated bytes confirmed_bundle_ids = 2;</code>
   * @return The count of confirmedBundleIds.
   */
  public int getConfirmedBundleIdsCount() {
    return confirmedBundleIds_.size();
  }
  /**
   * <code>repeated bytes confirmed_bundle_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The confirmedBundleIds at the given index.
   */
  public com.google.protobuf.ByteString getConfirmedBundleIds(int index) {
    return confirmedBundleIds_.get(index);
  }

  public static final int PRIORITY_WEIGHTS_JSON_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString priorityWeightsJson_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * ver protocol/docs/PRIORITIES.md
   * </pre>
   *
   * <code>bytes priority_weights_json = 3;</code>
   * @return The priorityWeightsJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPriorityWeightsJson() {
    return priorityWeightsJson_;
  }

  public static final int AUTHORITY_PUBLIC_KEY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes authority_public_key = 4;</code>
   * @return The authorityPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAuthorityPublicKey() {
    return authorityPublicKey_;
  }

  public static final int SAFETY_INSTRUCTIONS_CIPHERTEXT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString safetyInstructionsCiphertext_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes safety_instructions_ciphertext = 5;</code>
   * @return The safetyInstructionsCiphertext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSafetyInstructionsCiphertext() {
    return safetyInstructionsCiphertext_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!incidentId_.isEmpty()) {
      output.writeBytes(1, incidentId_);
    }
    for (int i = 0; i < confirmedBundleIds_.size(); i++) {
      output.writeBytes(2, confirmedBundleIds_.get(i));
    }
    if (!priorityWeightsJson_.isEmpty()) {
      output.writeBytes(3, priorityWeightsJson_);
    }
    if (!authorityPublicKey_.isEmpty()) {
      output.writeBytes(4, authorityPublicKey_);
    }
    if (!safetyInstructionsCiphertext_.isEmpty()) {
      output.writeBytes(5, safetyInstructionsCiphertext_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!incidentId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, incidentId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < confirmedBundleIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(confirmedBundleIds_.get(i));
      }
      size += dataSize;
      size += 1 * getConfirmedBundleIdsList().size();
    }
    if (!priorityWeightsJson_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, priorityWeightsJson_);
    }
    if (!authorityPublicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, authorityPublicKey_);
    }
    if (!safetyInstructionsCiphertext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, safetyInstructionsCiphertext_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.helius.core.protocol.v1.IncidentConfig)) {
      return super.equals(obj);
    }
    co.helius.core.protocol.v1.IncidentConfig other = (co.helius.core.protocol.v1.IncidentConfig) obj;

    if (!getIncidentId()
        .equals(other.getIncidentId())) return false;
    if (!getConfirmedBundleIdsList()
        .equals(other.getConfirmedBundleIdsList())) return false;
    if (!getPriorityWeightsJson()
        .equals(other.getPriorityWeightsJson())) return false;
    if (!getAuthorityPublicKey()
        .equals(other.getAuthorityPublicKey())) return false;
    if (!getSafetyInstructionsCiphertext()
        .equals(other.getSafetyInstructionsCiphertext())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INCIDENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIncidentId().hashCode();
    if (getConfirmedBundleIdsCount() > 0) {
      hash = (37 * hash) + CONFIRMED_BUNDLE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getConfirmedBundleIdsList().hashCode();
    }
    hash = (37 * hash) + PRIORITY_WEIGHTS_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getPriorityWeightsJson().hashCode();
    hash = (37 * hash) + AUTHORITY_PUBLIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorityPublicKey().hashCode();
    hash = (37 * hash) + SAFETY_INSTRUCTIONS_CIPHERTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getSafetyInstructionsCiphertext().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.helius.core.protocol.v1.IncidentConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.helius.core.protocol.v1.IncidentConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.IncidentConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.helius.core.protocol.v1.IncidentConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Configuración de incidente que el gateway inyecta hacia la malla (DTN inversa,
   * Sección 8.6): IDs ya confirmados, pesos de prioridad, clave pública de la autoridad.
   * Dueño: Helmut.
   * </pre>
   *
   * Protobuf type {@code helius.v1.IncidentConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helius.v1.IncidentConfig)
      co.helius.core.protocol.v1.IncidentConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.helius.core.protocol.v1.IncidentConfig.class, co.helius.core.protocol.v1.IncidentConfig.Builder.class);
    }

    // Construct using co.helius.core.protocol.v1.IncidentConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      incidentId_ = com.google.protobuf.ByteString.EMPTY;
      confirmedBundleIds_ = emptyList(com.google.protobuf.ByteString.class);
      priorityWeightsJson_ = com.google.protobuf.ByteString.EMPTY;
      authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      safetyInstructionsCiphertext_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.helius.core.protocol.v1.Incident.internal_static_helius_v1_IncidentConfig_descriptor;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.IncidentConfig getDefaultInstanceForType() {
      return co.helius.core.protocol.v1.IncidentConfig.getDefaultInstance();
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.IncidentConfig build() {
      co.helius.core.protocol.v1.IncidentConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.IncidentConfig buildPartial() {
      co.helius.core.protocol.v1.IncidentConfig result = new co.helius.core.protocol.v1.IncidentConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.helius.core.protocol.v1.IncidentConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.incidentId_ = incidentId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        confirmedBundleIds_.makeImmutable();
        result.confirmedBundleIds_ = confirmedBundleIds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.priorityWeightsJson_ = priorityWeightsJson_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.authorityPublicKey_ = authorityPublicKey_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.safetyInstructionsCiphertext_ = safetyInstructionsCiphertext_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.helius.core.protocol.v1.IncidentConfig) {
        return mergeFrom((co.helius.core.protocol.v1.IncidentConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.helius.core.protocol.v1.IncidentConfig other) {
      if (other == co.helius.core.protocol.v1.IncidentConfig.getDefaultInstance()) return this;
      if (!other.getIncidentId().isEmpty()) {
        setIncidentId(other.getIncidentId());
      }
      if (!other.confirmedBundleIds_.isEmpty()) {
        if (confirmedBundleIds_.isEmpty()) {
          confirmedBundleIds_ = other.confirmedBundleIds_;
          confirmedBundleIds_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureConfirmedBundleIdsIsMutable();
          confirmedBundleIds_.addAll(other.confirmedBundleIds_);
        }
        onChanged();
      }
      if (!other.getPriorityWeightsJson().isEmpty()) {
        setPriorityWeightsJson(other.getPriorityWeightsJson());
      }
      if (!other.getAuthorityPublicKey().isEmpty()) {
        setAuthorityPublicKey(other.getAuthorityPublicKey());
      }
      if (!other.getSafetyInstructionsCiphertext().isEmpty()) {
        setSafetyInstructionsCiphertext(other.getSafetyInstructionsCiphertext());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              incidentId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureConfirmedBundleIdsIsMutable();
              confirmedBundleIds_.add(v);
              break;
            } // case 18
            case 26: {
              priorityWeightsJson_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              authorityPublicKey_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              safetyInstructionsCiphertext_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString incidentId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes incident_id = 1;</code>
     * @return The incidentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIncidentId() {
      return incidentId_;
    }
    /**
     * <code>bytes incident_id = 1;</code>
     * @param value The incidentId to set.
     * @return This builder for chaining.
     */
    public Builder setIncidentId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      incidentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes incident_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncidentId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      incidentId_ = getDefaultInstance().getIncidentId();
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> confirmedBundleIds_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureConfirmedBundleIdsIsMutable() {
      if (!confirmedBundleIds_.isModifiable()) {
        confirmedBundleIds_ = makeMutableCopy(confirmedBundleIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @return A list containing the confirmedBundleIds.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getConfirmedBundleIdsList() {
      confirmedBundleIds_.makeImmutable();
      return confirmedBundleIds_;
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @return The count of confirmedBundleIds.
     */
    public int getConfirmedBundleIdsCount() {
      return confirmedBundleIds_.size();
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The confirmedBundleIds at the given index.
     */
    public com.google.protobuf.ByteString getConfirmedBundleIds(int index) {
      return confirmedBundleIds_.get(index);
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The confirmedBundleIds to set.
     * @return This builder for chaining.
     */
    public Builder setConfirmedBundleIds(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureConfirmedBundleIdsIsMutable();
      confirmedBundleIds_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @param value The confirmedBundleIds to add.
     * @return This builder for chaining.
     */
    public Builder addConfirmedBundleIds(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureConfirmedBundleIdsIsMutable();
      confirmedBundleIds_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @param values The confirmedBundleIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllConfirmedBundleIds(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureConfirmedBundleIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, confirmedBundleIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes confirmed_bundle_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfirmedBundleIds() {
      confirmedBundleIds_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString priorityWeightsJson_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * ver protocol/docs/PRIORITIES.md
     * </pre>
     *
     * <code>bytes priority_weights_json = 3;</code>
     * @return The priorityWeightsJson.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPriorityWeightsJson() {
      return priorityWeightsJson_;
    }
    /**
     * <pre>
     * ver protocol/docs/PRIORITIES.md
     * </pre>
     *
     * <code>bytes priority_weights_json = 3;</code>
     * @param value The priorityWeightsJson to set.
     * @return This builder for chaining.
     */
    public Builder setPriorityWeightsJson(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      priorityWeightsJson_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ver protocol/docs/PRIORITIES.md
     * </pre>
     *
     * <code>bytes priority_weights_json = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriorityWeightsJson() {
      bitField0_ = (bitField0_ & ~0x00000004);
      priorityWeightsJson_ = getDefaultInstance().getPriorityWeightsJson();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString authorityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes authority_public_key = 4;</code>
     * @return The authorityPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAuthorityPublicKey() {
      return authorityPublicKey_;
    }
    /**
     * <code>bytes authority_public_key = 4;</code>
     * @param value The authorityPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorityPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      authorityPublicKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bytes authority_public_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorityPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      authorityPublicKey_ = getDefaultInstance().getAuthorityPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString safetyInstructionsCiphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes safety_instructions_ciphertext = 5;</code>
     * @return The safetyInstructionsCiphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSafetyInstructionsCiphertext() {
      return safetyInstructionsCiphertext_;
    }
    /**
     * <code>bytes safety_instructions_ciphertext = 5;</code>
     * @param value The safetyInstructionsCiphertext to set.
     * @return This builder for chaining.
     */
    public Builder setSafetyInstructionsCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      safetyInstructionsCiphertext_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bytes safety_instructions_ciphertext = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSafetyInstructionsCiphertext() {
      bitField0_ = (bitField0_ & ~0x00000010);
      safetyInstructionsCiphertext_ = getDefaultInstance().getSafetyInstructionsCiphertext();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helius.v1.IncidentConfig)
  }

  // @@protoc_insertion_point(class_scope:helius.v1.IncidentConfig)
  private static final co.helius.core.protocol.v1.IncidentConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.helius.core.protocol.v1.IncidentConfig();
  }

  public static co.helius.core.protocol.v1.IncidentConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IncidentConfig>
      PARSER = new com.google.protobuf.AbstractParser<IncidentConfig>() {
    @java.lang.Override
    public IncidentConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IncidentConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IncidentConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.helius.core.protocol.v1.IncidentConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

