// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/motion.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * <pre>
 * Evidencia de actividad/movimiento — Sección 10. Dueño: Alex.
 * Prohibido: DEAD/ALIVE/INJURED. Estados permitidos en el enum de arriba (bundle.proto).
 * </pre>
 *
 * Protobuf type {@code helius.v1.MotionEvidence}
 */
@com.google.protobuf.Generated
public final class MotionEvidence extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:helius.v1.MotionEvidence)
    MotionEvidenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MotionEvidence");
  }
  // Use MotionEvidence.newBuilder() to construct.
  private MotionEvidence(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MotionEvidence() {
    pattern_ = "";
    activityState_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.helius.core.protocol.v1.MotionEvidence.class, co.helius.core.protocol.v1.MotionEvidence.Builder.class);
  }

  public static final int PURPOSEFUL_MOTION_CONFIDENCE_FIELD_NUMBER = 1;
  private double purposefulMotionConfidence_ = 0D;
  /**
   * <pre>
   * [0,1]
   * </pre>
   *
   * <code>double purposeful_motion_confidence = 1;</code>
   * @return The purposefulMotionConfidence.
   */
  @java.lang.Override
  public double getPurposefulMotionConfidence() {
    return purposefulMotionConfidence_;
  }

  public static final int PATTERN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pattern_ = "";
  /**
   * <pre>
   * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
   * </pre>
   *
   * <code>string pattern = 2;</code>
   * @return The pattern.
   */
  @java.lang.Override
  public java.lang.String getPattern() {
    java.lang.Object ref = pattern_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pattern_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
   * </pre>
   *
   * <code>string pattern = 2;</code>
   * @return The bytes for pattern.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatternBytes() {
    java.lang.Object ref = pattern_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pattern_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MOTION_TS_FIELD_NUMBER = 3;
  private long lastMotionTs_ = 0L;
  /**
   * <code>uint64 last_motion_ts = 3;</code>
   * @return The lastMotionTs.
   */
  @java.lang.Override
  public long getLastMotionTs() {
    return lastMotionTs_;
  }

  public static final int ACTIVITY_STATE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object activityState_ = "";
  /**
   * <pre>
   * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
   * </pre>
   *
   * <code>string activity_state = 4;</code>
   * @return The activityState.
   */
  @java.lang.Override
  public java.lang.String getActivityState() {
    java.lang.Object ref = activityState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activityState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
   * </pre>
   *
   * <code>string activity_state = 4;</code>
   * @return The bytes for activityState.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActivityStateBytes() {
    java.lang.Object ref = activityState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activityState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(purposefulMotionConfidence_) != 0) {
      output.writeDouble(1, purposefulMotionConfidence_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pattern_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, pattern_);
    }
    if (lastMotionTs_ != 0L) {
      output.writeUInt64(3, lastMotionTs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(activityState_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, activityState_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (java.lang.Double.doubleToRawLongBits(purposefulMotionConfidence_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, purposefulMotionConfidence_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pattern_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pattern_);
    }
    if (lastMotionTs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, lastMotionTs_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(activityState_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, activityState_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.helius.core.protocol.v1.MotionEvidence)) {
      return super.equals(obj);
    }
    co.helius.core.protocol.v1.MotionEvidence other = (co.helius.core.protocol.v1.MotionEvidence) obj;

    if (java.lang.Double.doubleToLongBits(getPurposefulMotionConfidence())
        != java.lang.Double.doubleToLongBits(
            other.getPurposefulMotionConfidence())) return false;
    if (!getPattern()
        .equals(other.getPattern())) return false;
    if (getLastMotionTs()
        != other.getLastMotionTs()) return false;
    if (!getActivityState()
        .equals(other.getActivityState())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PURPOSEFUL_MOTION_CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPurposefulMotionConfidence()));
    hash = (37 * hash) + PATTERN_FIELD_NUMBER;
    hash = (53 * hash) + getPattern().hashCode();
    hash = (37 * hash) + LAST_MOTION_TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastMotionTs());
    hash = (37 * hash) + ACTIVITY_STATE_FIELD_NUMBER;
    hash = (53 * hash) + getActivityState().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.helius.core.protocol.v1.MotionEvidence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.helius.core.protocol.v1.MotionEvidence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.helius.core.protocol.v1.MotionEvidence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.helius.core.protocol.v1.MotionEvidence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Evidencia de actividad/movimiento — Sección 10. Dueño: Alex.
   * Prohibido: DEAD/ALIVE/INJURED. Estados permitidos en el enum de arriba (bundle.proto).
   * </pre>
   *
   * Protobuf type {@code helius.v1.MotionEvidence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helius.v1.MotionEvidence)
      co.helius.core.protocol.v1.MotionEvidenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.helius.core.protocol.v1.MotionEvidence.class, co.helius.core.protocol.v1.MotionEvidence.Builder.class);
    }

    // Construct using co.helius.core.protocol.v1.MotionEvidence.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      purposefulMotionConfidence_ = 0D;
      pattern_ = "";
      lastMotionTs_ = 0L;
      activityState_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.helius.core.protocol.v1.Motion.internal_static_helius_v1_MotionEvidence_descriptor;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.MotionEvidence getDefaultInstanceForType() {
      return co.helius.core.protocol.v1.MotionEvidence.getDefaultInstance();
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.MotionEvidence build() {
      co.helius.core.protocol.v1.MotionEvidence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.helius.core.protocol.v1.MotionEvidence buildPartial() {
      co.helius.core.protocol.v1.MotionEvidence result = new co.helius.core.protocol.v1.MotionEvidence(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.helius.core.protocol.v1.MotionEvidence result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.purposefulMotionConfidence_ = purposefulMotionConfidence_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pattern_ = pattern_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastMotionTs_ = lastMotionTs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.activityState_ = activityState_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.helius.core.protocol.v1.MotionEvidence) {
        return mergeFrom((co.helius.core.protocol.v1.MotionEvidence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.helius.core.protocol.v1.MotionEvidence other) {
      if (other == co.helius.core.protocol.v1.MotionEvidence.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getPurposefulMotionConfidence()) != 0) {
        setPurposefulMotionConfidence(other.getPurposefulMotionConfidence());
      }
      if (!other.getPattern().isEmpty()) {
        pattern_ = other.pattern_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getLastMotionTs() != 0L) {
        setLastMotionTs(other.getLastMotionTs());
      }
      if (!other.getActivityState().isEmpty()) {
        activityState_ = other.activityState_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              purposefulMotionConfidence_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 18: {
              pattern_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              lastMotionTs_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              activityState_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double purposefulMotionConfidence_ ;
    /**
     * <pre>
     * [0,1]
     * </pre>
     *
     * <code>double purposeful_motion_confidence = 1;</code>
     * @return The purposefulMotionConfidence.
     */
    @java.lang.Override
    public double getPurposefulMotionConfidence() {
      return purposefulMotionConfidence_;
    }
    /**
     * <pre>
     * [0,1]
     * </pre>
     *
     * <code>double purposeful_motion_confidence = 1;</code>
     * @param value The purposefulMotionConfidence to set.
     * @return This builder for chaining.
     */
    public Builder setPurposefulMotionConfidence(double value) {

      purposefulMotionConfidence_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [0,1]
     * </pre>
     *
     * <code>double purposeful_motion_confidence = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurposefulMotionConfidence() {
      bitField0_ = (bitField0_ & ~0x00000001);
      purposefulMotionConfidence_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object pattern_ = "";
    /**
     * <pre>
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * </pre>
     *
     * <code>string pattern = 2;</code>
     * @return The pattern.
     */
    public java.lang.String getPattern() {
      java.lang.Object ref = pattern_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pattern_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * </pre>
     *
     * <code>string pattern = 2;</code>
     * @return The bytes for pattern.
     */
    public com.google.protobuf.ByteString
        getPatternBytes() {
      java.lang.Object ref = pattern_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pattern_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * </pre>
     *
     * <code>string pattern = 2;</code>
     * @param value The pattern to set.
     * @return This builder for chaining.
     */
    public Builder setPattern(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pattern_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * </pre>
     *
     * <code>string pattern = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPattern() {
      pattern_ = getDefaultInstance().getPattern();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
     * </pre>
     *
     * <code>string pattern = 2;</code>
     * @param value The bytes for pattern to set.
     * @return This builder for chaining.
     */
    public Builder setPatternBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pattern_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long lastMotionTs_ ;
    /**
     * <code>uint64 last_motion_ts = 3;</code>
     * @return The lastMotionTs.
     */
    @java.lang.Override
    public long getLastMotionTs() {
      return lastMotionTs_;
    }
    /**
     * <code>uint64 last_motion_ts = 3;</code>
     * @param value The lastMotionTs to set.
     * @return This builder for chaining.
     */
    public Builder setLastMotionTs(long value) {

      lastMotionTs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 last_motion_ts = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMotionTs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastMotionTs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object activityState_ = "";
    /**
     * <pre>
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * </pre>
     *
     * <code>string activity_state = 4;</code>
     * @return The activityState.
     */
    public java.lang.String getActivityState() {
      java.lang.Object ref = activityState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activityState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * </pre>
     *
     * <code>string activity_state = 4;</code>
     * @return The bytes for activityState.
     */
    public com.google.protobuf.ByteString
        getActivityStateBytes() {
      java.lang.Object ref = activityState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activityState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * </pre>
     *
     * <code>string activity_state = 4;</code>
     * @param value The activityState to set.
     * @return This builder for chaining.
     */
    public Builder setActivityState(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      activityState_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * </pre>
     *
     * <code>string activity_state = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearActivityState() {
      activityState_ = getDefaultInstance().getActivityState();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
     * </pre>
     *
     * <code>string activity_state = 4;</code>
     * @param value The bytes for activityState to set.
     * @return This builder for chaining.
     */
    public Builder setActivityStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      activityState_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:helius.v1.MotionEvidence)
  }

  // @@protoc_insertion_point(class_scope:helius.v1.MotionEvidence)
  private static final co.helius.core.protocol.v1.MotionEvidence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.helius.core.protocol.v1.MotionEvidence();
  }

  public static co.helius.core.protocol.v1.MotionEvidence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MotionEvidence>
      PARSER = new com.google.protobuf.AbstractParser<MotionEvidence>() {
    @java.lang.Override
    public MotionEvidence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MotionEvidence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MotionEvidence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.helius.core.protocol.v1.MotionEvidence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

