// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/motion.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

@com.google.protobuf.Generated
public interface MotionEvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helius.v1.MotionEvidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * [0,1]
   * </pre>
   *
   * <code>double purposeful_motion_confidence = 1;</code>
   * @return The purposefulMotionConfidence.
   */
  double getPurposefulMotionConfidence();

  /**
   * <pre>
   * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
   * </pre>
   *
   * <code>string pattern = 2;</code>
   * @return The pattern.
   */
  java.lang.String getPattern();
  /**
   * <pre>
   * p.ej. "3-3" (tipo SOS), vacío si no hay patrón
   * </pre>
   *
   * <code>string pattern = 2;</code>
   * @return The bytes for pattern.
   */
  com.google.protobuf.ByteString
      getPatternBytes();

  /**
   * <code>uint64 last_motion_ts = 3;</code>
   * @return The lastMotionTs.
   */
  long getLastMotionTs();

  /**
   * <pre>
   * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
   * </pre>
   *
   * <code>string activity_state = 4;</code>
   * @return The activityState.
   */
  java.lang.String getActivityState();
  /**
   * <pre>
   * RESPONSIVE | RECENT_INTERACTION | PURPOSEFUL_MOTION |
   * </pre>
   *
   * <code>string activity_state = 4;</code>
   * @return The bytes for activityState.
   */
  com.google.protobuf.ByteString
      getActivityStateBytes();
}
