// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

@com.google.protobuf.Generated
public interface RelayMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helius.v1.RelayMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes received_from = 1;</code>
   * @return The receivedFrom.
   */
  com.google.protobuf.ByteString getReceivedFrom();

  /**
   * <code>string transport = 2;</code>
   * @return The transport.
   */
  java.lang.String getTransport();
  /**
   * <code>string transport = 2;</code>
   * @return The bytes for transport.
   */
  com.google.protobuf.ByteString
      getTransportBytes();

  /**
   * <code>int32 rssi_dbm = 3;</code>
   * @return The rssiDbm.
   */
  int getRssiDbm();

  /**
   * <code>uint64 rx_timestamp = 4;</code>
   * @return The rxTimestamp.
   */
  long getRxTimestamp();

  /**
   * <code>bytes observer_geo = 5;</code>
   * @return The observerGeo.
   */
  com.google.protobuf.ByteString getObserverGeo();

  /**
   * <code>double observer_acc_m = 6;</code>
   * @return The observerAccM.
   */
  double getObserverAccM();
}
