// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

@com.google.protobuf.Generated
public interface ResponderMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helius.v1.ResponderMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * instrucciones del gateway, cifrado extremo a extremo
   * </pre>
   *
   * <code>bytes ciphertext = 1;</code>
   * @return The ciphertext.
   */
  com.google.protobuf.ByteString getCiphertext();
}
