// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: helius/v1/found_person.proto
// Protobuf Java Version: 4.35.1

package co.helius.core.protocol.v1;

/**
 * Protobuf enum {@code helius.v1.VerificationLevel}
 */
@com.google.protobuf.Generated
public enum VerificationLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>VERIFICATION_UNSPECIFIED = 0;</code>
   */
  VERIFICATION_UNSPECIFIED(0),
  /**
   * <code>VERIFICATION_THIRD_PARTY_REPORTED = 1;</code>
   */
  VERIFICATION_THIRD_PARTY_REPORTED(1),
  /**
   * <code>VERIFICATION_SELF_REPORTED = 2;</code>
   */
  VERIFICATION_SELF_REPORTED(2),
  /**
   * <code>VERIFICATION_RESPONDER_VERIFIED = 3;</code>
   */
  VERIFICATION_RESPONDER_VERIFIED(3),
  /**
   * <code>VERIFICATION_AUTHORITY_VERIFIED = 4;</code>
   */
  VERIFICATION_AUTHORITY_VERIFIED(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "VerificationLevel");
  }
  /**
   * <code>VERIFICATION_UNSPECIFIED = 0;</code>
   */
  public static final int VERIFICATION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>VERIFICATION_THIRD_PARTY_REPORTED = 1;</code>
   */
  public static final int VERIFICATION_THIRD_PARTY_REPORTED_VALUE = 1;
  /**
   * <code>VERIFICATION_SELF_REPORTED = 2;</code>
   */
  public static final int VERIFICATION_SELF_REPORTED_VALUE = 2;
  /**
   * <code>VERIFICATION_RESPONDER_VERIFIED = 3;</code>
   */
  public static final int VERIFICATION_RESPONDER_VERIFIED_VALUE = 3;
  /**
   * <code>VERIFICATION_AUTHORITY_VERIFIED = 4;</code>
   */
  public static final int VERIFICATION_AUTHORITY_VERIFIED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VerificationLevel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VerificationLevel forNumber(int value) {
    switch (value) {
      case 0: return VERIFICATION_UNSPECIFIED;
      case 1: return VERIFICATION_THIRD_PARTY_REPORTED;
      case 2: return VERIFICATION_SELF_REPORTED;
      case 3: return VERIFICATION_RESPONDER_VERIFIED;
      case 4: return VERIFICATION_AUTHORITY_VERIFIED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VerificationLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VerificationLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VerificationLevel>() {
          public VerificationLevel findValueByNumber(int number) {
            return VerificationLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.helius.core.protocol.v1.FoundPerson.getDescriptor().getEnumType(1);
  }

  private static final VerificationLevel[] VALUES = values();

  public static VerificationLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VerificationLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:helius.v1.VerificationLevel)
}

