// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/biomarker.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

/**
 * <pre>
 * Análisis e Interpretación de Biomarcadores (AIB) — Sección 11. Dueño: Alex/Laura.
 * Naming obligatorio: NUNCA "vitals", "triage", "diagnóstico", "signos vitales médicos".
 * Todo resultado es evidencia con incertidumbre — ver docs/glossary.md.
 * </pre>
 *
 * Protobuf type {@code sismomesh.v1.BiomarkerEvidence}
 */
@com.google.protobuf.Generated
public final class BiomarkerEvidence extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sismomesh.v1.BiomarkerEvidence)
    BiomarkerEvidenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BiomarkerEvidence");
  }
  // Use BiomarkerEvidence.newBuilder() to construct.
  private BiomarkerEvidence(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BiomarkerEvidence() {
    source_ = "";
    modelVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.sismomesh.core.protocol.v1.BiomarkerEvidence.class, co.sismomesh.core.protocol.v1.BiomarkerEvidence.Builder.class);
  }

  private int bitField0_;
  public static final int PULSE_BPM_FIELD_NUMBER = 1;
  private double pulseBpm_ = 0D;
  /**
   * <code>optional double pulse_bpm = 1;</code>
   * @return Whether the pulseBpm field is set.
   */
  @java.lang.Override
  public boolean hasPulseBpm() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional double pulse_bpm = 1;</code>
   * @return The pulseBpm.
   */
  @java.lang.Override
  public double getPulseBpm() {
    return pulseBpm_;
  }

  public static final int PULSE_CI_LOW_FIELD_NUMBER = 2;
  private double pulseCiLow_ = 0D;
  /**
   * <pre>
   * intervalo de confianza
   * </pre>
   *
   * <code>double pulse_ci_low = 2;</code>
   * @return The pulseCiLow.
   */
  @java.lang.Override
  public double getPulseCiLow() {
    return pulseCiLow_;
  }

  public static final int PULSE_CI_HIGH_FIELD_NUMBER = 3;
  private double pulseCiHigh_ = 0D;
  /**
   * <code>double pulse_ci_high = 3;</code>
   * @return The pulseCiHigh.
   */
  @java.lang.Override
  public double getPulseCiHigh() {
    return pulseCiHigh_;
  }

  public static final int SQI_FIELD_NUMBER = 4;
  private double sqi_ = 0D;
  /**
   * <pre>
   * Signal Quality Index [0,1]
   * </pre>
   *
   * <code>double sqi = 4;</code>
   * @return The sqi.
   */
  @java.lang.Override
  public double getSqi() {
    return sqi_;
  }

  public static final int SOURCE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * "camera_ppg" | "certified_device"
   * </pre>
   *
   * <code>string source = 5;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "camera_ppg" | "certified_device"
   * </pre>
   *
   * <code>string source = 5;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_VERSION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelVersion_ = "";
  /**
   * <code>string model_version = 6;</code>
   * @return The modelVersion.
   */
  @java.lang.Override
  public java.lang.String getModelVersion() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string model_version = 6;</code>
   * @return The bytes for modelVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelVersionBytes() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBSERVED_AT_FIELD_NUMBER = 7;
  private long observedAt_ = 0L;
  /**
   * <code>uint64 observed_at = 7;</code>
   * @return The observedAt.
   */
  @java.lang.Override
  public long getObservedAt() {
    return observedAt_;
  }

  public static final int WINDOW_MS_FIELD_NUMBER = 8;
  private int windowMs_ = 0;
  /**
   * <code>uint32 window_ms = 8;</code>
   * @return The windowMs.
   */
  @java.lang.Override
  public int getWindowMs() {
    return windowMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeDouble(1, pulseBpm_);
    }
    if (java.lang.Double.doubleToRawLongBits(pulseCiLow_) != 0) {
      output.writeDouble(2, pulseCiLow_);
    }
    if (java.lang.Double.doubleToRawLongBits(pulseCiHigh_) != 0) {
      output.writeDouble(3, pulseCiHigh_);
    }
    if (java.lang.Double.doubleToRawLongBits(sqi_) != 0) {
      output.writeDouble(4, sqi_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, modelVersion_);
    }
    if (observedAt_ != 0L) {
      output.writeUInt64(7, observedAt_);
    }
    if (windowMs_ != 0) {
      output.writeUInt32(8, windowMs_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, pulseBpm_);
    }
    if (java.lang.Double.doubleToRawLongBits(pulseCiLow_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, pulseCiLow_);
    }
    if (java.lang.Double.doubleToRawLongBits(pulseCiHigh_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, pulseCiHigh_);
    }
    if (java.lang.Double.doubleToRawLongBits(sqi_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, sqi_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(modelVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, modelVersion_);
    }
    if (observedAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, observedAt_);
    }
    if (windowMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, windowMs_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.sismomesh.core.protocol.v1.BiomarkerEvidence)) {
      return super.equals(obj);
    }
    co.sismomesh.core.protocol.v1.BiomarkerEvidence other = (co.sismomesh.core.protocol.v1.BiomarkerEvidence) obj;

    if (hasPulseBpm() != other.hasPulseBpm()) return false;
    if (hasPulseBpm()) {
      if (java.lang.Double.doubleToLongBits(getPulseBpm())
          != java.lang.Double.doubleToLongBits(
              other.getPulseBpm())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getPulseCiLow())
        != java.lang.Double.doubleToLongBits(
            other.getPulseCiLow())) return false;
    if (java.lang.Double.doubleToLongBits(getPulseCiHigh())
        != java.lang.Double.doubleToLongBits(
            other.getPulseCiHigh())) return false;
    if (java.lang.Double.doubleToLongBits(getSqi())
        != java.lang.Double.doubleToLongBits(
            other.getSqi())) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getModelVersion()
        .equals(other.getModelVersion())) return false;
    if (getObservedAt()
        != other.getObservedAt()) return false;
    if (getWindowMs()
        != other.getWindowMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPulseBpm()) {
      hash = (37 * hash) + PULSE_BPM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPulseBpm()));
    }
    hash = (37 * hash) + PULSE_CI_LOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPulseCiLow()));
    hash = (37 * hash) + PULSE_CI_HIGH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPulseCiHigh()));
    hash = (37 * hash) + SQI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSqi()));
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + MODEL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModelVersion().hashCode();
    hash = (37 * hash) + OBSERVED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getObservedAt());
    hash = (37 * hash) + WINDOW_MS_FIELD_NUMBER;
    hash = (53 * hash) + getWindowMs();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.sismomesh.core.protocol.v1.BiomarkerEvidence prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Análisis e Interpretación de Biomarcadores (AIB) — Sección 11. Dueño: Alex/Laura.
   * Naming obligatorio: NUNCA "vitals", "triage", "diagnóstico", "signos vitales médicos".
   * Todo resultado es evidencia con incertidumbre — ver docs/glossary.md.
   * </pre>
   *
   * Protobuf type {@code sismomesh.v1.BiomarkerEvidence}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sismomesh.v1.BiomarkerEvidence)
      co.sismomesh.core.protocol.v1.BiomarkerEvidenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.sismomesh.core.protocol.v1.BiomarkerEvidence.class, co.sismomesh.core.protocol.v1.BiomarkerEvidence.Builder.class);
    }

    // Construct using co.sismomesh.core.protocol.v1.BiomarkerEvidence.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pulseBpm_ = 0D;
      pulseCiLow_ = 0D;
      pulseCiHigh_ = 0D;
      sqi_ = 0D;
      source_ = "";
      modelVersion_ = "";
      observedAt_ = 0L;
      windowMs_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.sismomesh.core.protocol.v1.Biomarker.internal_static_sismomesh_v1_BiomarkerEvidence_descriptor;
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.BiomarkerEvidence getDefaultInstanceForType() {
      return co.sismomesh.core.protocol.v1.BiomarkerEvidence.getDefaultInstance();
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.BiomarkerEvidence build() {
      co.sismomesh.core.protocol.v1.BiomarkerEvidence result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.BiomarkerEvidence buildPartial() {
      co.sismomesh.core.protocol.v1.BiomarkerEvidence result = new co.sismomesh.core.protocol.v1.BiomarkerEvidence(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.sismomesh.core.protocol.v1.BiomarkerEvidence result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pulseBpm_ = pulseBpm_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pulseCiLow_ = pulseCiLow_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pulseCiHigh_ = pulseCiHigh_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sqi_ = sqi_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.modelVersion_ = modelVersion_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.observedAt_ = observedAt_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.windowMs_ = windowMs_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.sismomesh.core.protocol.v1.BiomarkerEvidence) {
        return mergeFrom((co.sismomesh.core.protocol.v1.BiomarkerEvidence)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.sismomesh.core.protocol.v1.BiomarkerEvidence other) {
      if (other == co.sismomesh.core.protocol.v1.BiomarkerEvidence.getDefaultInstance()) return this;
      if (other.hasPulseBpm()) {
        setPulseBpm(other.getPulseBpm());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPulseCiLow()) != 0) {
        setPulseCiLow(other.getPulseCiLow());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPulseCiHigh()) != 0) {
        setPulseCiHigh(other.getPulseCiHigh());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getSqi()) != 0) {
        setSqi(other.getSqi());
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getModelVersion().isEmpty()) {
        modelVersion_ = other.modelVersion_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getObservedAt() != 0L) {
        setObservedAt(other.getObservedAt());
      }
      if (other.getWindowMs() != 0) {
        setWindowMs(other.getWindowMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              pulseBpm_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              pulseCiLow_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              pulseCiHigh_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              sqi_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              modelVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              observedAt_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              windowMs_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double pulseBpm_ ;
    /**
     * <code>optional double pulse_bpm = 1;</code>
     * @return Whether the pulseBpm field is set.
     */
    @java.lang.Override
    public boolean hasPulseBpm() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional double pulse_bpm = 1;</code>
     * @return The pulseBpm.
     */
    @java.lang.Override
    public double getPulseBpm() {
      return pulseBpm_;
    }
    /**
     * <code>optional double pulse_bpm = 1;</code>
     * @param value The pulseBpm to set.
     * @return This builder for chaining.
     */
    public Builder setPulseBpm(double value) {

      pulseBpm_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional double pulse_bpm = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPulseBpm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pulseBpm_ = 0D;
      onChanged();
      return this;
    }

    private double pulseCiLow_ ;
    /**
     * <pre>
     * intervalo de confianza
     * </pre>
     *
     * <code>double pulse_ci_low = 2;</code>
     * @return The pulseCiLow.
     */
    @java.lang.Override
    public double getPulseCiLow() {
      return pulseCiLow_;
    }
    /**
     * <pre>
     * intervalo de confianza
     * </pre>
     *
     * <code>double pulse_ci_low = 2;</code>
     * @param value The pulseCiLow to set.
     * @return This builder for chaining.
     */
    public Builder setPulseCiLow(double value) {

      pulseCiLow_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * intervalo de confianza
     * </pre>
     *
     * <code>double pulse_ci_low = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPulseCiLow() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pulseCiLow_ = 0D;
      onChanged();
      return this;
    }

    private double pulseCiHigh_ ;
    /**
     * <code>double pulse_ci_high = 3;</code>
     * @return The pulseCiHigh.
     */
    @java.lang.Override
    public double getPulseCiHigh() {
      return pulseCiHigh_;
    }
    /**
     * <code>double pulse_ci_high = 3;</code>
     * @param value The pulseCiHigh to set.
     * @return This builder for chaining.
     */
    public Builder setPulseCiHigh(double value) {

      pulseCiHigh_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double pulse_ci_high = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPulseCiHigh() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pulseCiHigh_ = 0D;
      onChanged();
      return this;
    }

    private double sqi_ ;
    /**
     * <pre>
     * Signal Quality Index [0,1]
     * </pre>
     *
     * <code>double sqi = 4;</code>
     * @return The sqi.
     */
    @java.lang.Override
    public double getSqi() {
      return sqi_;
    }
    /**
     * <pre>
     * Signal Quality Index [0,1]
     * </pre>
     *
     * <code>double sqi = 4;</code>
     * @param value The sqi to set.
     * @return This builder for chaining.
     */
    public Builder setSqi(double value) {

      sqi_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signal Quality Index [0,1]
     * </pre>
     *
     * <code>double sqi = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSqi() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sqi_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * "camera_ppg" | "certified_device"
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "camera_ppg" | "certified_device"
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "camera_ppg" | "certified_device"
     * </pre>
     *
     * <code>string source = 5;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "camera_ppg" | "certified_device"
     * </pre>
     *
     * <code>string source = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "camera_ppg" | "certified_device"
     * </pre>
     *
     * <code>string source = 5;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object modelVersion_ = "";
    /**
     * <code>string model_version = 6;</code>
     * @return The modelVersion.
     */
    public java.lang.String getModelVersion() {
      java.lang.Object ref = modelVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model_version = 6;</code>
     * @return The bytes for modelVersion.
     */
    public com.google.protobuf.ByteString
        getModelVersionBytes() {
      java.lang.Object ref = modelVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model_version = 6;</code>
     * @param value The modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string model_version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelVersion() {
      modelVersion_ = getDefaultInstance().getModelVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string model_version = 6;</code>
     * @param value The bytes for modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long observedAt_ ;
    /**
     * <code>uint64 observed_at = 7;</code>
     * @return The observedAt.
     */
    @java.lang.Override
    public long getObservedAt() {
      return observedAt_;
    }
    /**
     * <code>uint64 observed_at = 7;</code>
     * @param value The observedAt to set.
     * @return This builder for chaining.
     */
    public Builder setObservedAt(long value) {

      observedAt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 observed_at = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      observedAt_ = 0L;
      onChanged();
      return this;
    }

    private int windowMs_ ;
    /**
     * <code>uint32 window_ms = 8;</code>
     * @return The windowMs.
     */
    @java.lang.Override
    public int getWindowMs() {
      return windowMs_;
    }
    /**
     * <code>uint32 window_ms = 8;</code>
     * @param value The windowMs to set.
     * @return This builder for chaining.
     */
    public Builder setWindowMs(int value) {

      windowMs_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 window_ms = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowMs() {
      bitField0_ = (bitField0_ & ~0x00000080);
      windowMs_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sismomesh.v1.BiomarkerEvidence)
  }

  // @@protoc_insertion_point(class_scope:sismomesh.v1.BiomarkerEvidence)
  private static final co.sismomesh.core.protocol.v1.BiomarkerEvidence DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.sismomesh.core.protocol.v1.BiomarkerEvidence();
  }

  public static co.sismomesh.core.protocol.v1.BiomarkerEvidence getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BiomarkerEvidence>
      PARSER = new com.google.protobuf.AbstractParser<BiomarkerEvidence>() {
    @java.lang.Override
    public BiomarkerEvidence parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BiomarkerEvidence> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BiomarkerEvidence> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.sismomesh.core.protocol.v1.BiomarkerEvidence getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

