// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/biomarker.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public final class Biomarker extends com.google.protobuf.GeneratedFile {
  private Biomarker() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Biomarker");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_BiomarkerEvidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_BiomarkerEvidence_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034sismomesh/v1/biomarker.proto\022\014sismomes" +
      "h.v1\"\302\001\n\021BiomarkerEvidence\022\026\n\tpulse_bpm\030" +
      "\001 \001(\001H\000\210\001\001\022\024\n\014pulse_ci_low\030\002 \001(\001\022\025\n\rpuls" +
      "e_ci_high\030\003 \001(\001\022\013\n\003sqi\030\004 \001(\001\022\016\n\006source\030\005" +
      " \001(\t\022\025\n\rmodel_version\030\006 \001(\t\022\023\n\013observed_" +
      "at\030\007 \001(\004\022\021\n\twindow_ms\030\010 \001(\rB\014\n\n_pulse_bp" +
      "mB!\n\035co.sismomesh.core.protocol.v1P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sismomesh_v1_BiomarkerEvidence_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sismomesh_v1_BiomarkerEvidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_BiomarkerEvidence_descriptor,
        new java.lang.String[] { "PulseBpm", "PulseCiLow", "PulseCiHigh", "Sqi", "Source", "ModelVersion", "ObservedAt", "WindowMs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
