// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public interface BundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sismomesh.v1.Bundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sismomesh.v1.BundleHeader header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>.sismomesh.v1.BundleHeader header = 1;</code>
   * @return The header.
   */
  co.sismomesh.core.protocol.v1.BundleHeader getHeader();
  /**
   * <code>.sismomesh.v1.BundleHeader header = 1;</code>
   */
  co.sismomesh.core.protocol.v1.BundleHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>.sismomesh.v1.EmergencyStatus status = 10;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.sismomesh.v1.EmergencyStatus status = 10;</code>
   * @return The status.
   */
  co.sismomesh.core.protocol.v1.EmergencyStatus getStatus();
  /**
   * <code>.sismomesh.v1.EmergencyStatus status = 10;</code>
   */
  co.sismomesh.core.protocol.v1.EmergencyStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.sismomesh.v1.MotionEvidence motion = 11;</code>
   * @return Whether the motion field is set.
   */
  boolean hasMotion();
  /**
   * <code>.sismomesh.v1.MotionEvidence motion = 11;</code>
   * @return The motion.
   */
  co.sismomesh.core.protocol.v1.MotionEvidence getMotion();
  /**
   * <code>.sismomesh.v1.MotionEvidence motion = 11;</code>
   */
  co.sismomesh.core.protocol.v1.MotionEvidenceOrBuilder getMotionOrBuilder();

  /**
   * <pre>
   * NUNCA "vitals" — ver docs/glossary.md
   * </pre>
   *
   * <code>.sismomesh.v1.BiomarkerEvidence biomarker = 12;</code>
   * @return Whether the biomarker field is set.
   */
  boolean hasBiomarker();
  /**
   * <pre>
   * NUNCA "vitals" — ver docs/glossary.md
   * </pre>
   *
   * <code>.sismomesh.v1.BiomarkerEvidence biomarker = 12;</code>
   * @return The biomarker.
   */
  co.sismomesh.core.protocol.v1.BiomarkerEvidence getBiomarker();
  /**
   * <pre>
   * NUNCA "vitals" — ver docs/glossary.md
   * </pre>
   *
   * <code>.sismomesh.v1.BiomarkerEvidence biomarker = 12;</code>
   */
  co.sismomesh.core.protocol.v1.BiomarkerEvidenceOrBuilder getBiomarkerOrBuilder();

  /**
   * <code>.sismomesh.v1.PeerObservation observation = 13;</code>
   * @return Whether the observation field is set.
   */
  boolean hasObservation();
  /**
   * <code>.sismomesh.v1.PeerObservation observation = 13;</code>
   * @return The observation.
   */
  co.sismomesh.core.protocol.v1.PeerObservation getObservation();
  /**
   * <code>.sismomesh.v1.PeerObservation observation = 13;</code>
   */
  co.sismomesh.core.protocol.v1.PeerObservationOrBuilder getObservationOrBuilder();

  /**
   * <code>.sismomesh.v1.RawSensorChunk raw = 14;</code>
   * @return Whether the raw field is set.
   */
  boolean hasRaw();
  /**
   * <code>.sismomesh.v1.RawSensorChunk raw = 14;</code>
   * @return The raw.
   */
  co.sismomesh.core.protocol.v1.RawSensorChunk getRaw();
  /**
   * <code>.sismomesh.v1.RawSensorChunk raw = 14;</code>
   */
  co.sismomesh.core.protocol.v1.RawSensorChunkOrBuilder getRawOrBuilder();

  /**
   * <pre>
   * DTN inversa, ver Sección 8.6
   * </pre>
   *
   * <code>.sismomesh.v1.ResponderMessage responder = 15;</code>
   * @return Whether the responder field is set.
   */
  boolean hasResponder();
  /**
   * <pre>
   * DTN inversa, ver Sección 8.6
   * </pre>
   *
   * <code>.sismomesh.v1.ResponderMessage responder = 15;</code>
   * @return The responder.
   */
  co.sismomesh.core.protocol.v1.ResponderMessage getResponder();
  /**
   * <pre>
   * DTN inversa, ver Sección 8.6
   * </pre>
   *
   * <code>.sismomesh.v1.ResponderMessage responder = 15;</code>
   */
  co.sismomesh.core.protocol.v1.ResponderMessageOrBuilder getResponderOrBuilder();

  /**
   * <pre>
   * Ed25519 sobre header||payload
   * </pre>
   *
   * <code>bytes signature = 20;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  co.sismomesh.core.protocol.v1.Bundle.PayloadCase getPayloadCase();
}
