// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public final class BundleOuterClass extends com.google.protobuf.GeneratedFile {
  private BundleOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BundleOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_Bundle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_Bundle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_BundleHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_BundleHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_ClockEvidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_ClockEvidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_RawSensorChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_RawSensorChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_ResponderMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_ResponderMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_RelayMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_RelayMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031sismomesh/v1/bundle.proto\022\014sismomesh.v" +
      "1\032\031sismomesh/v1/common.proto\032\031sismomesh/" +
      "v1/status.proto\032\031sismomesh/v1/motion.pro" +
      "to\032\034sismomesh/v1/biomarker.proto\032\036sismom" +
      "esh/v1/observation.proto\"\201\003\n\006Bundle\022*\n\006h" +
      "eader\030\001 \001(\0132\032.sismomesh.v1.BundleHeader\022" +
      "/\n\006status\030\n \001(\0132\035.sismomesh.v1.Emergency" +
      "StatusH\000\022.\n\006motion\030\013 \001(\0132\034.sismomesh.v1." +
      "MotionEvidenceH\000\0224\n\tbiomarker\030\014 \001(\0132\037.si" +
      "smomesh.v1.BiomarkerEvidenceH\000\0224\n\013observ" +
      "ation\030\r \001(\0132\035.sismomesh.v1.PeerObservati" +
      "onH\000\022+\n\003raw\030\016 \001(\0132\034.sismomesh.v1.RawSens" +
      "orChunkH\000\0223\n\tresponder\030\017 \001(\0132\036.sismomesh" +
      ".v1.ResponderMessageH\000\022\021\n\tsignature\030\024 \001(" +
      "\014B\t\n\007payload\"\373\001\n\014BundleHeader\022\017\n\007version" +
      "\030\001 \001(\r\022\023\n\013disaster_id\030\002 \001(\t\022\021\n\tbundle_id" +
      "\030\003 \001(\014\022\017\n\007node_id\030\004 \001(\014\022\020\n\010sequence\030\005 \001(" +
      "\004\022\022\n\ncreated_at\030\006 \001(\004\022\022\n\nexpires_at\030\007 \001(" +
      "\004\022\021\n\thop_count\030\010 \001(\r\022(\n\010priority\030\t \001(\0162\026" +
      ".sismomesh.v1.Priority\022*\n\005clock\030\n \001(\0132\033." +
      "sismomesh.v1.ClockEvidence\"Y\n\rClockEvide" +
      "nce\022\024\n\014monotonic_ms\030\001 \001(\003\022\035\n\020observed_sk" +
      "ew_ms\030\002 \001(\003H\000\210\001\001B\023\n\021_observed_skew_ms\"W\n" +
      "\016RawSensorChunk\022\014\n\004tier\030\001 \001(\t\022\r\n\005chunk\030\002" +
      " \001(\014\022\023\n\013chunk_index\030\003 \001(\r\022\023\n\013chunk_count" +
      "\030\004 \001(\r\"&\n\020ResponderMessage\022\022\n\nciphertext" +
      "\030\001 \001(\014\"\217\001\n\rRelayMetadata\022\025\n\rreceived_fro" +
      "m\030\001 \001(\014\022\021\n\ttransport\030\002 \001(\t\022\020\n\010rssi_dbm\030\003" +
      " \001(\005\022\024\n\014rx_timestamp\030\004 \001(\004\022\024\n\014observer_g" +
      "eo\030\005 \001(\014\022\026\n\016observer_acc_m\030\006 \001(\001B!\n\035co.s" +
      "ismomesh.core.protocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          co.sismomesh.core.protocol.v1.Common.getDescriptor(),
          co.sismomesh.core.protocol.v1.Status.getDescriptor(),
          co.sismomesh.core.protocol.v1.Motion.getDescriptor(),
          co.sismomesh.core.protocol.v1.Biomarker.getDescriptor(),
          co.sismomesh.core.protocol.v1.Observation.getDescriptor(),
        });
    internal_static_sismomesh_v1_Bundle_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sismomesh_v1_Bundle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_Bundle_descriptor,
        new java.lang.String[] { "Header", "Status", "Motion", "Biomarker", "Observation", "Raw", "Responder", "Signature", "Payload", });
    internal_static_sismomesh_v1_BundleHeader_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sismomesh_v1_BundleHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_BundleHeader_descriptor,
        new java.lang.String[] { "Version", "DisasterId", "BundleId", "NodeId", "Sequence", "CreatedAt", "ExpiresAt", "HopCount", "Priority", "Clock", });
    internal_static_sismomesh_v1_ClockEvidence_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sismomesh_v1_ClockEvidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_ClockEvidence_descriptor,
        new java.lang.String[] { "MonotonicMs", "ObservedSkewMs", });
    internal_static_sismomesh_v1_RawSensorChunk_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sismomesh_v1_RawSensorChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_RawSensorChunk_descriptor,
        new java.lang.String[] { "Tier", "Chunk", "ChunkIndex", "ChunkCount", });
    internal_static_sismomesh_v1_ResponderMessage_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sismomesh_v1_ResponderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_ResponderMessage_descriptor,
        new java.lang.String[] { "Ciphertext", });
    internal_static_sismomesh_v1_RelayMetadata_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sismomesh_v1_RelayMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_RelayMetadata_descriptor,
        new java.lang.String[] { "ReceivedFrom", "Transport", "RssiDbm", "RxTimestamp", "ObserverGeo", "ObserverAccM", });
    descriptor.resolveAllFeaturesImmutable();
    co.sismomesh.core.protocol.v1.Common.getDescriptor();
    co.sismomesh.core.protocol.v1.Status.getDescriptor();
    co.sismomesh.core.protocol.v1.Motion.getDescriptor();
    co.sismomesh.core.protocol.v1.Biomarker.getDescriptor();
    co.sismomesh.core.protocol.v1.Observation.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
