// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/identity.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

/**
 * <pre>
 * Un blob cifrado por destinatario (nunca un único blob "para cualquiera").
 * El relay transporta bytes opacos; no puede leer ni el nombre ni el contenido.
 * </pre>
 *
 * Protobuf type {@code sismomesh.v1.EncryptedIdentityProfile}
 */
@com.google.protobuf.Generated
public final class EncryptedIdentityProfile extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sismomesh.v1.EncryptedIdentityProfile)
    EncryptedIdentityProfileOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "EncryptedIdentityProfile");
  }
  // Use EncryptedIdentityProfile.newBuilder() to construct.
  private EncryptedIdentityProfile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EncryptedIdentityProfile() {
    recipientClass_ = 0;
    recipientPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    ciphertext_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.class, co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.Builder.class);
  }

  /**
   * Protobuf enum {@code sismomesh.v1.EncryptedIdentityProfile.RecipientClass}
   */
  public enum RecipientClass
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_RECIPIENT = 0;</code>
     */
    UNKNOWN_RECIPIENT(0),
    /**
     * <code>FAMILY = 1;</code>
     */
    FAMILY(1),
    /**
     * <code>RESCUE_AUTHORITY = 2;</code>
     */
    RESCUE_AUTHORITY(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "RecipientClass");
    }
    /**
     * <code>UNKNOWN_RECIPIENT = 0;</code>
     */
    public static final int UNKNOWN_RECIPIENT_VALUE = 0;
    /**
     * <code>FAMILY = 1;</code>
     */
    public static final int FAMILY_VALUE = 1;
    /**
     * <code>RESCUE_AUTHORITY = 2;</code>
     */
    public static final int RESCUE_AUTHORITY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RecipientClass valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RecipientClass forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_RECIPIENT;
        case 1: return FAMILY;
        case 2: return RESCUE_AUTHORITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RecipientClass>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RecipientClass> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RecipientClass>() {
            public RecipientClass findValueByNumber(int number) {
              return RecipientClass.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.getDescriptor().getEnumType(0);
    }

    private static final RecipientClass[] VALUES = values();

    public static RecipientClass valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RecipientClass(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sismomesh.v1.EncryptedIdentityProfile.RecipientClass)
  }

  public static final int RECIPIENT_CLASS_FIELD_NUMBER = 1;
  private int recipientClass_ = 0;
  /**
   * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
   * @return The enum numeric value on the wire for recipientClass.
   */
  @java.lang.Override public int getRecipientClassValue() {
    return recipientClass_;
  }
  /**
   * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
   * @return The recipientClass.
   */
  @java.lang.Override public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass getRecipientClass() {
    co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass result = co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.forNumber(recipientClass_);
    return result == null ? co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.UNRECOGNIZED : result;
  }

  public static final int RECIPIENT_PUBLIC_KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString recipientPublicKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * a qué clave X25519 va cifrado este blob
   * </pre>
   *
   * <code>bytes recipient_public_key = 2;</code>
   * @return The recipientPublicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRecipientPublicKey() {
    return recipientPublicKey_;
  }

  public static final int CIPHERTEXT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
   * </pre>
   *
   * <code>bytes ciphertext = 3;</code>
   * @return The ciphertext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCiphertext() {
    return ciphertext_;
  }

  public static final int POLICY_VERSION_FIELD_NUMBER = 4;
  private long policyVersion_ = 0L;
  /**
   * <code>uint64 policy_version = 4;</code>
   * @return The policyVersion.
   */
  @java.lang.Override
  public long getPolicyVersion() {
    return policyVersion_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (recipientClass_ != co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.UNKNOWN_RECIPIENT.getNumber()) {
      output.writeEnum(1, recipientClass_);
    }
    if (!recipientPublicKey_.isEmpty()) {
      output.writeBytes(2, recipientPublicKey_);
    }
    if (!ciphertext_.isEmpty()) {
      output.writeBytes(3, ciphertext_);
    }
    if (policyVersion_ != 0L) {
      output.writeUInt64(4, policyVersion_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (recipientClass_ != co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.UNKNOWN_RECIPIENT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, recipientClass_);
    }
    if (!recipientPublicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, recipientPublicKey_);
    }
    if (!ciphertext_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, ciphertext_);
    }
    if (policyVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, policyVersion_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.sismomesh.core.protocol.v1.EncryptedIdentityProfile)) {
      return super.equals(obj);
    }
    co.sismomesh.core.protocol.v1.EncryptedIdentityProfile other = (co.sismomesh.core.protocol.v1.EncryptedIdentityProfile) obj;

    if (recipientClass_ != other.recipientClass_) return false;
    if (!getRecipientPublicKey()
        .equals(other.getRecipientPublicKey())) return false;
    if (!getCiphertext()
        .equals(other.getCiphertext())) return false;
    if (getPolicyVersion()
        != other.getPolicyVersion()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECIPIENT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + recipientClass_;
    hash = (37 * hash) + RECIPIENT_PUBLIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getRecipientPublicKey().hashCode();
    hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getCiphertext().hashCode();
    hash = (37 * hash) + POLICY_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPolicyVersion());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.sismomesh.core.protocol.v1.EncryptedIdentityProfile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Un blob cifrado por destinatario (nunca un único blob "para cualquiera").
   * El relay transporta bytes opacos; no puede leer ni el nombre ni el contenido.
   * </pre>
   *
   * Protobuf type {@code sismomesh.v1.EncryptedIdentityProfile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sismomesh.v1.EncryptedIdentityProfile)
      co.sismomesh.core.protocol.v1.EncryptedIdentityProfileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.class, co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.Builder.class);
    }

    // Construct using co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recipientClass_ = 0;
      recipientPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      policyVersion_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.sismomesh.core.protocol.v1.Identity.internal_static_sismomesh_v1_EncryptedIdentityProfile_descriptor;
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile getDefaultInstanceForType() {
      return co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.getDefaultInstance();
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile build() {
      co.sismomesh.core.protocol.v1.EncryptedIdentityProfile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile buildPartial() {
      co.sismomesh.core.protocol.v1.EncryptedIdentityProfile result = new co.sismomesh.core.protocol.v1.EncryptedIdentityProfile(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.sismomesh.core.protocol.v1.EncryptedIdentityProfile result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recipientClass_ = recipientClass_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.recipientPublicKey_ = recipientPublicKey_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ciphertext_ = ciphertext_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.policyVersion_ = policyVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.sismomesh.core.protocol.v1.EncryptedIdentityProfile) {
        return mergeFrom((co.sismomesh.core.protocol.v1.EncryptedIdentityProfile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.sismomesh.core.protocol.v1.EncryptedIdentityProfile other) {
      if (other == co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.getDefaultInstance()) return this;
      if (other.recipientClass_ != 0) {
        setRecipientClassValue(other.getRecipientClassValue());
      }
      if (!other.getRecipientPublicKey().isEmpty()) {
        setRecipientPublicKey(other.getRecipientPublicKey());
      }
      if (!other.getCiphertext().isEmpty()) {
        setCiphertext(other.getCiphertext());
      }
      if (other.getPolicyVersion() != 0L) {
        setPolicyVersion(other.getPolicyVersion());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              recipientClass_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              recipientPublicKey_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ciphertext_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              policyVersion_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int recipientClass_ = 0;
    /**
     * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
     * @return The enum numeric value on the wire for recipientClass.
     */
    @java.lang.Override public int getRecipientClassValue() {
      return recipientClass_;
    }
    /**
     * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
     * @param value The enum numeric value on the wire for recipientClass to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientClassValue(int value) {
      recipientClass_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
     * @return The recipientClass.
     */
    @java.lang.Override
    public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass getRecipientClass() {
      co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass result = co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.forNumber(recipientClass_);
      return result == null ? co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass.UNRECOGNIZED : result;
    }
    /**
     * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
     * @param value The recipientClass to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setRecipientClass(co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      recipientClass_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientClass() {
      bitField0_ = (bitField0_ & ~0x00000001);
      recipientClass_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString recipientPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * a qué clave X25519 va cifrado este blob
     * </pre>
     *
     * <code>bytes recipient_public_key = 2;</code>
     * @return The recipientPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRecipientPublicKey() {
      return recipientPublicKey_;
    }
    /**
     * <pre>
     * a qué clave X25519 va cifrado este blob
     * </pre>
     *
     * <code>bytes recipient_public_key = 2;</code>
     * @param value The recipientPublicKey to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      recipientPublicKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * a qué clave X25519 va cifrado este blob
     * </pre>
     *
     * <code>bytes recipient_public_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientPublicKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      recipientPublicKey_ = getDefaultInstance().getRecipientPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @return The ciphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }
    /**
     * <pre>
     * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @param value The ciphertext to set.
     * @return This builder for chaining.
     */
    public Builder setCiphertext(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ciphertext_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
     * </pre>
     *
     * <code>bytes ciphertext = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCiphertext() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ciphertext_ = getDefaultInstance().getCiphertext();
      onChanged();
      return this;
    }

    private long policyVersion_ ;
    /**
     * <code>uint64 policy_version = 4;</code>
     * @return The policyVersion.
     */
    @java.lang.Override
    public long getPolicyVersion() {
      return policyVersion_;
    }
    /**
     * <code>uint64 policy_version = 4;</code>
     * @param value The policyVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyVersion(long value) {

      policyVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 policy_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPolicyVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      policyVersion_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sismomesh.v1.EncryptedIdentityProfile)
  }

  // @@protoc_insertion_point(class_scope:sismomesh.v1.EncryptedIdentityProfile)
  private static final co.sismomesh.core.protocol.v1.EncryptedIdentityProfile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.sismomesh.core.protocol.v1.EncryptedIdentityProfile();
  }

  public static co.sismomesh.core.protocol.v1.EncryptedIdentityProfile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptedIdentityProfile>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedIdentityProfile>() {
    @java.lang.Override
    public EncryptedIdentityProfile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EncryptedIdentityProfile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedIdentityProfile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.sismomesh.core.protocol.v1.EncryptedIdentityProfile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

