// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/identity.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public interface EncryptedIdentityProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sismomesh.v1.EncryptedIdentityProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
   * @return The enum numeric value on the wire for recipientClass.
   */
  int getRecipientClassValue();
  /**
   * <code>.sismomesh.v1.EncryptedIdentityProfile.RecipientClass recipient_class = 1;</code>
   * @return The recipientClass.
   */
  co.sismomesh.core.protocol.v1.EncryptedIdentityProfile.RecipientClass getRecipientClass();

  /**
   * <pre>
   * a qué clave X25519 va cifrado este blob
   * </pre>
   *
   * <code>bytes recipient_public_key = 2;</code>
   * @return The recipientPublicKey.
   */
  com.google.protobuf.ByteString getRecipientPublicKey();

  /**
   * <pre>
   * AEAD sobre IdentityProfilePlaintext (ver docs/security/THREAT-MODEL.md)
   * </pre>
   *
   * <code>bytes ciphertext = 3;</code>
   * @return The ciphertext.
   */
  com.google.protobuf.ByteString getCiphertext();

  /**
   * <code>uint64 policy_version = 4;</code>
   * @return The policyVersion.
   */
  long getPolicyVersion();
}
