// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/common.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public interface GeoPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sismomesh.v1.GeoPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double lat = 1;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lon = 2;</code>
   * @return The lon.
   */
  double getLon();

  /**
   * <code>optional double acc_m = 3;</code>
   * @return Whether the accM field is set.
   */
  boolean hasAccM();
  /**
   * <code>optional double acc_m = 3;</code>
   * @return The accM.
   */
  double getAccM();

  /**
   * <pre>
   * relativa al nivel del suelo del edificio si se conoce, si no MSL/GNSS
   * </pre>
   *
   * <code>optional double altitude_m = 4;</code>
   * @return Whether the altitudeM field is set.
   */
  boolean hasAltitudeM();
  /**
   * <pre>
   * relativa al nivel del suelo del edificio si se conoce, si no MSL/GNSS
   * </pre>
   *
   * <code>optional double altitude_m = 4;</code>
   * @return The altitudeM.
   */
  double getAltitudeM();

  /**
   * <pre>
   * ASSUMED hasta calibración — ver docs/validation/VALIDATION.md
   * </pre>
   *
   * <code>optional double altitude_acc_m = 5;</code>
   * @return Whether the altitudeAccM field is set.
   */
  boolean hasAltitudeAccM();
  /**
   * <pre>
   * ASSUMED hasta calibración — ver docs/validation/VALIDATION.md
   * </pre>
   *
   * <code>optional double altitude_acc_m = 5;</code>
   * @return The altitudeAccM.
   */
  double getAltitudeAccM();

  /**
   * <code>optional .sismomesh.v1.AltitudeSource altitude_source = 6;</code>
   * @return Whether the altitudeSource field is set.
   */
  boolean hasAltitudeSource();
  /**
   * <code>optional .sismomesh.v1.AltitudeSource altitude_source = 6;</code>
   * @return The enum numeric value on the wire for altitudeSource.
   */
  int getAltitudeSourceValue();
  /**
   * <code>optional .sismomesh.v1.AltitudeSource altitude_source = 6;</code>
   * @return The altitudeSource.
   */
  co.sismomesh.core.protocol.v1.AltitudeSource getAltitudeSource();
}
