// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/incident.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public final class Incident extends com.google.protobuf.GeneratedFile {
  private Incident() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Incident");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sismomesh_v1_IncidentConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sismomesh_v1_IncidentConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033sismomesh/v1/incident.proto\022\014sismomesh" +
      ".v1\"\250\001\n\016IncidentConfig\022\023\n\013incident_id\030\001 " +
      "\001(\014\022\034\n\024confirmed_bundle_ids\030\002 \003(\014\022\035\n\025pri" +
      "ority_weights_json\030\003 \001(\014\022\034\n\024authority_pu" +
      "blic_key\030\004 \001(\014\022&\n\036safety_instructions_ci" +
      "phertext\030\005 \001(\014B!\n\035co.sismomesh.core.prot" +
      "ocol.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sismomesh_v1_IncidentConfig_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sismomesh_v1_IncidentConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sismomesh_v1_IncidentConfig_descriptor,
        new java.lang.String[] { "IncidentId", "ConfirmedBundleIds", "PriorityWeightsJson", "AuthorityPublicKey", "SafetyInstructionsCiphertext", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
