// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/bundle.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

@com.google.protobuf.Generated
public interface RawSensorChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sismomesh.v1.RawSensorChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "T2"
   * </pre>
   *
   * <code>string tier = 1;</code>
   * @return The tier.
   */
  java.lang.String getTier();
  /**
   * <pre>
   * "T2"
   * </pre>
   *
   * <code>string tier = 1;</code>
   * @return The bytes for tier.
   */
  com.google.protobuf.ByteString
      getTierBytes();

  /**
   * <code>bytes chunk = 2;</code>
   * @return The chunk.
   */
  com.google.protobuf.ByteString getChunk();

  /**
   * <code>uint32 chunk_index = 3;</code>
   * @return The chunkIndex.
   */
  int getChunkIndex();

  /**
   * <code>uint32 chunk_count = 4;</code>
   * @return The chunkCount.
   */
  int getChunkCount();
}
