// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sismomesh/v1/common.proto
// Protobuf Java Version: 4.35.1

package co.sismomesh.core.protocol.v1;

/**
 * Protobuf enum {@code sismomesh.v1.ResponseState}
 */
@com.google.protobuf.Generated
public enum ResponseState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>SAFE = 1;</code>
   */
  SAFE(1),
  /**
   * <code>NEEDS_HELP = 2;</code>
   */
  NEEDS_HELP(2),
  /**
   * <code>TRAPPED = 3;</code>
   */
  TRAPPED(3),
  /**
   * <code>UNCONFIRMED = 4;</code>
   */
  UNCONFIRMED(4),
  /**
   * <pre>
   * Prohibido agregar DEAD/ALIVE/INJURED — ver Sección 1.3 y docs/glossary.md.
   * </pre>
   *
   * <code>NO_RECENT_EVIDENCE = 5;</code>
   */
  NO_RECENT_EVIDENCE(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ResponseState");
  }
  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>SAFE = 1;</code>
   */
  public static final int SAFE_VALUE = 1;
  /**
   * <code>NEEDS_HELP = 2;</code>
   */
  public static final int NEEDS_HELP_VALUE = 2;
  /**
   * <code>TRAPPED = 3;</code>
   */
  public static final int TRAPPED_VALUE = 3;
  /**
   * <code>UNCONFIRMED = 4;</code>
   */
  public static final int UNCONFIRMED_VALUE = 4;
  /**
   * <pre>
   * Prohibido agregar DEAD/ALIVE/INJURED — ver Sección 1.3 y docs/glossary.md.
   * </pre>
   *
   * <code>NO_RECENT_EVIDENCE = 5;</code>
   */
  public static final int NO_RECENT_EVIDENCE_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResponseState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResponseState forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return SAFE;
      case 2: return NEEDS_HELP;
      case 3: return TRAPPED;
      case 4: return UNCONFIRMED;
      case 5: return NO_RECENT_EVIDENCE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResponseState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResponseState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResponseState>() {
          public ResponseState findValueByNumber(int number) {
            return ResponseState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.sismomesh.core.protocol.v1.Common.getDescriptor().getEnumType(1);
  }

  private static final ResponseState[] VALUES = values();

  public static ResponseState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResponseState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:sismomesh.v1.ResponseState)
}

